### ISSUE TITLE
Organization （プロジェクト全体）に関する相談窓口はどこ？

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#1]
_From @hidao80 on September 23, 2017 4:48_

おそらくこの Organizations は

1. BOT のコードリポジトリ (my-first-qiita/BOT が作られる or my-first-qiita/PHP に配置される？)
2. BOT 運用および Organizations 運用に関する取り決めをまとめるリポジトリ (my-first-qiita/COMMON が相当する？)
3. BOT が投稿するコンテンツ群のリポジトリ (my-first-qiita/items が相当する？)

の 3 つのリポジトリで運用されるようになると考えていますが、リポジトリまたぎの相談や特定のリポジトリに対して起こすと不適当な issue (当 issue のようなもの) は、どのリポジトリで管理しますか？

それとも、プロジェクトマネジメント用の別システムを用意しますか？

_Copied from original issue: my-first-qiita/common#1_

**Comment by KEINOS** [comment]
そうですね。各リポジトリをふかんでディスカッションできる場所が必要ですね。

Qiita縛りを逆にQiitaの利点にしたいのでMastodonをSlack的な使い方にしたいとは考えているのですが、リポジトリとOrganizationの構成・関係をまずは明確にしたいと思います。

**Comment by hidao80** [comment]
提案・相談の窓口（Issue の登録先）の割り振りを提案をします。

1. BOT の仕様、実装、にかかわることは scripts へ　例）○○機能追加の提案、実装方法の相談
2. その他の相談・提案は items へ　例）Organization 運営、記事フォーマットの改善提案

お互い Github のコラボ機能が把握しきれていない様なので、この issue がある items リポジトリを Organization に関する汎用ディスカッションスペースに仮定すると、悩まないでよいと思います。

困ったときは、とりあえず items に issue を投げる！って感じで。

**Comment by KEINOS** [comment]
BOT関連以外の異臭を放っているものはitemsで了解です。👍

コラボのイメージ明確化に関しても、まずはメンバーが思う「必須の機能」「実装したい機能」「実装のアイデア」などをあげて行くところからスタートはどうでしょう？

**Comment by hidao80** [comment]
そうですね。

まずは「[相談] BOT のコンセプト・目的」issue でも立ち上げて、「この BOT が運用開始すると、どのような便益があるのか」を決めていきましょうか。

追記：
issue #4 に上記トピックを立ち上げました。

**Comment by hidao80** [comment]
この issue はクローズしてもよさそうですね。

私が立てた issue なので、私にはクローズすることができません。

**Comment by hidao80** [comment]
違った。コピーしていただいて、私の issue **ではいから** クローズできないのか。

**Comment by KEINOS** [comment]
現在のルールとして以下が決まったので、一旦クローズとします。

・アイデア、気づいた点等、まずはProjectのノートから始める
・ノートをissue化する際は、BOT関連以外は`items`リポジトリに置く
