### ISSUE TITLE
Organization の説明文＠GitHub

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#10]
現在の「Organization」の説明文は以下の通りになっています。

    Qiita/Qiitadonユーザー共同制作によるQiita記事をコレクションして「はじめての●●」の目次を作るプロジェクト。

上記は以前の趣旨のままなので、取り急ぎ下記のように変えてみてはどうでしょう？

    QiitaとQiitadonのユーザ間のコラボレーションを支援するためのBOTを共同で作るためのOrganizationです。

**Comment by hidao80** [comment]
賛成です。

**Comment by KEINOS** [comment]
Organizationの説明文をアップデートしました。
https://github.com/Qiita-BOTch

一旦クローズですが、もっとキャッチーな文があれば、ぜひ！その際には再オープンします。
