### ISSUE TITLE
TravisCI のビルドで Composer のリポジトリに GitHub を追加すると失敗する

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#104]
## 概要

Qithub-CORE のコミット・プッシュで TravisCI が失敗します。

Composer でインストールするパッケージの、検索リポジトリに GitHub の repo を追加した場合、ローカルではちゃんと動く（パッケージがインストールされる）ので、 TravisCI の問題である可能性が高く、他のリポジトリでも発生する可能性があります。

今後の追跡（トレース）用に issue を立てただけですので、温かくお見守りください。

## 手順

**Qithub-CORE で Qithub コマンドの動作テストを行うため**に以下を行いました。（Qithub-**CMD** を開発時の追加パッケージとしてインストールしています）

- 対象リポジトリ： [Qithub-BOT/Qithub-CORE](https://github.com/Qithub-BOT/Qithub-CORE/)
- 対象ファイル　：[Qithub-CORE の composer.json](https://github.com/Qithub-BOT/Qithub-CORE/blob/09649478b44bcfeb09191cb188597273ab6c90d7/composer.json)
- Qithub-CORE の composer.json に "repositories" で  [Qithub-CMD リポジトリを追加](https://github.com/Qithub-BOT/Qithub-CORE/blob/09649478b44bcfeb09191cb188597273ab6c90d7/composer.json#L17-L22)
- Qithub-CORE の composer.json に "require-dev" で[インストールする開発パッケージとして  "qithub/cmd" を追加](https://github.com/Qithub-BOT/Qithub-CORE/blob/09649478b44bcfeb09191cb188597273ab6c90d7/composer.json#L28)（※１）

Qithub-CORE のローカル clone 下で `composer install`（もしくは `update`）すると "vendor/qithub/cmd/" 下に Qithub コマンド群（Qithub-CMD repo の内容）が無事インストールされます。

しかし、この設定のコミットをプッシュすると、TravisCI のチェックで失敗するのです。

（※１）"qithub/cmd"は [Qithub-**CMD** のパッケージ名](https://github.com/Qithub-BOT/Qithub-CMD/blob/master/composer.json#L2)です。

## エラー内容

Travis 上で、Composer が追加パッケージをインストールしようとするタイミングで認証エラー（"GitHub credentials" を手動で設定するように指示されるエラー）が発生し、パッケーイのインストールに失敗し、ビルドが止まってしまう。

- 失敗ビルド： https://travis-ci.org/Qithub-BOT/Qithub-CORE/jobs/384521042

```bash
$ composer install
Loading composer repositories with package information
Failed to clone the git@github.com:Qithub-BOT/Qithub-CMD.git repository, try running in interactive mode so that you can enter your GitHub credentials
                                                                                                                                                                
  [RuntimeException]                                                                                                                                            
  Failed to execute git clone --mirror 'git@github.com:Qithub-BOT/Qithub-CMD.git' '/home/travis/.composer/cache/vcs/git-github.com-Qithub-BOT-Qithub-CMD.git/'  
                                                                                                                                                                
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
The command "composer install" failed and exited with 1 during .
Your build has been stopped.
```

## 考えられる原因

ローカルで Qithub-CMD のパッケージがインストールできて、Travis 上で失敗するのは、おそらく git クローン時の認証と思われます。

ローカルでは、自身の GitHub アカウントで clone しますが、Travisは `git@github.com` でアクセスするからです。

['.travis.yml' の設定ファイルに GitHub のトークンを記載すれば回避できる](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml)らしいのですが、公開リポジトリであるため、自身のアカウントとトークンを記載するのは、あまり良い解決方法とは言えません。

[同じ issue は見つけた](https://github.com/yiisoft/yii2/issues/12987)のですが、[そこで提案された解決法](https://github.com/yiisoft/yii2/issues/12987#issuecomment-264029954)を試しても NG でした。Issue は close されているのですが、追記で解決しないとコメントは付いているものの、「別 issue にしろ」と特に追加情報はありませんでした。

GitHub から `git clone` するためだけに認証ファイルは必要ないはずなので、アノニマス（ゲスト？）的な設定がある気がします。

## 気になる点

気になるのは、 TravisCI で（ソースの変更なく）再ビルドを行うと、[PHP7.x でパスしちゃったりすることがある](https://travis-ci.org/Qithub-BOT/Qithub-CORE/jobs/384524344)のです。

このパターンの場合、ビルド中にインストールで使われるリポジトリの応答が原因だったりするのですが、現在謎です。

## 備考：Qithub コマンド（Qithub-CMD）の入れ方

Qithub-CMD repo にあるコマンド群を composer でインストールするには、以下の `composer.json` 設定で `$ composer install` すると導入されます。

```composer.json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:Qithub-BOT/Qithub-CMD.git"
        }
    ],
    "require": {
        "qithub/cmd": "master@dev"
    }
}
```

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2018/05/28 現在）

- @hidao80 氏のアドバイスで [GitHub のパーソナル・トークンを設定して回避](#issuecomment-392412171)
- 次回 PR 時に TravisCI のテストがパスしたら close

**Comment by KEINOS** [comment]
`.travis.yml` に `sudo: false` を追加（失敗）→ 削除したら、PHP v7.2.4 を除いてパスした。。。

これは Travis 側のキャッシュの問題なのか？

https://travis-ci.org/Qithub-BOT/Qithub-CORE/builds/384551326

むふぅ、、、

**Comment by hidao80** [comment]
フラッシュアイデアですが、Travis の環境変数に

```
token=[2段階認証トークン]
```

として、`comporser.json`の`repositories": [ {  "url": `に、

```
$ git clone https://{ユーザ名}:$token@github.com/XXXXX.git
```

としたらうまく行きそうな気がします。

**Comment by hidao80** [comment]
https://www.previousnext.com.au/blog/managing-composer-github-access-personal-access-tokens

この記事のトークンを Travis の環境変数に入れてしまうのはどうでしょう？

**Comment by KEINOS** [comment]
> トークンを Travis の環境変数に入れてしまうのはどうでしょう？

このコミットで、それも頭によぎったのですが、一歩設定間違えるとビルドの公開ログにトークンが表示されちゃうらしいので怖いところです。ダミーのトークン作って試してみるか。

https://github.com/Qithub-BOT/Qithub-CORE/commit/c475fb801abc42c5dd892308e600f61f051c4ee5

理屈では Travis から GitHub への Push は発生させない（自動リリースさせない）ので、トークンはいらないはずなので、ちょいとした設定なんだと思うんだどもなー。

ただ、同じソースなのに、ビルドがパスしたり失敗したりするところが突破口なんだと思うんですよね。

**Comment by KEINOS** [comment]
トークンを環境変数に入れて再ビルドしてみましたが、ダメでやんした。(＞＜)／
https://travis-ci.org/Qithub-BOT/Qithub-CORE/builds/384551326

なんだろなー、なんだろなー。もっと調べてみるでやんす

**Comment by KEINOS** [comment]
ただ、トークンを環境変数に設定するだけでは NG みたい。エスケープせなあかんの、か？

```
$ export COMPOSER_AUTH=[secure]
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.
```

**Comment by KEINOS** [comment]
トークン通ったし、テストも通った！ 🎉 
本 issue は次回の PR でパスしたら close させます。

https://travis-ci.org/Qithub-BOT/Qithub-CORE/builds/384551326

今後は **TravisCI の環境設定にトークンを設定しておくのが無難**と思われます。

ただ、このことからユーザが一般的に composer でローカルに GitHub からインストールするときにローカルの `.gitconfig` などいじらないといけないのか要検証です。（まっさらな環境でストレートにインストールできるかなど）

### 環境変数に記載するときのポイント

1.  Value の値をシングルクォーテーションで囲う
1. JSON配列の文字列で渡す

<kbd><img width="824" alt="2018-05-28 14 43 58" src="https://user-images.githubusercontent.com/11840938/40598959-b900ea52-6285-11e8-9fe1-a4b3b76b9f12.png"></kbd>

設定内容の置き換えは、`{$Name} = "{$Value}"`という処理ではなく`{$Name} = {$Value}`という処理らしく、自動で囲うわけではないらしい。

エラーにあった「エスケープをチェック」とは、逆の意味でクォーテーションについて考えろということだったみたい。

### トークンの漏洩

「Display value in build log」が、**オフになっていれば値の表記が `[secure]` に置き換わり設定値が漏れない**ことも確認。

### トークンを設定するメリット

**TravisCI のテスト速度が上がりました**。おそらくGitHub のトークンがあることで各種 repo の失敗までのレスポンス待ちが減ったことによると思われる。 

---

#### 成功例 1
- NAME: `COMPOSER_AUTH`
- VALUE: `'{"github-oauth": {"github.com": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}}'`
#### NG な例 1
- NAME: `COMPOSER_AUTH`
- VALUE: `{"github-oauth": {"github.com": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}}`
#### NG な例 2
- NAME: `COMPOSER_AUTH`
- VALUE: `{\"github-oauth\": {\"github.com\": \"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\"}}`
#### NG な例 3
- NAME: `COMPOSER_AUTH`
- VALUE: `COMPOSER_AUTH='{"github-oauth": {"github.com": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}}'`
#### NG な例 4
- NAME: `COMPOSER_AUTH`
- VALUE: `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`
#### NG な例 5
- NAME: `github-oauth`
- VALUE: `"github.com": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"`

**Comment by hidao80** [comment]
trusty に php 7.2 って、インストールできましたっけ？

**Comment by KEINOS** [comment]
デフォルトのイメージにはないみたいです。
https://docs.travis-ci.com/user/reference/trusty/#PHP-images

でも、yml に設定したら入っちゃいましたね。`sudo` の指定なしだから `trusty` なはずなのに？
https://github.com/Qithub-BOT/Qithub-CORE/blob/master/.travis.yml

プリ・インストールされてないってだけで、新たにインストールさせてるからテストがモッタリしてたのかも。

**Comment by KEINOS** [comment]
やっぱり、新たにインストールしてました。
https://travis-ci.org/Qithub-BOT/Qithub-CORE/jobs/384551330#L424-L429

プリ・インストール済みのイメージを特定すればビルドも早いということか。

任意のイメージを作成するには有料アカウントが必要？

**Comment by KEINOS** [comment]
どうやら、GitHub で Composer のパッケージを配布する場合は、ローカル側にも GitHub のアカウントは必須のようです。なので、TravisCI でのテストは @hidao80 さんの手法が最速な解決法と思われます。

下記考察から、当面この**プライベート・トークンを TravisCI の環境設定で指定して行う**ことにしたいと思います。

---

Composer でパッケージをインストールする際、

```
Root （ローカルの/自身の composer.json ）パッケージ情報読み取り
 → 依存情報読み取り → 依存の依存情報読み取り → ・・・
 → 依存をダウンロード → 依存の依存をダウンロード・・・
```
と再帰的に処理していくそうなのですが、**Root より後のパッケージは git でなくAPI を叩く**のだそうです。これは、依存解決のため `composer.json` のみを先に読み取りに行くからとのこと。

そのため、カスタム・リポジトリである GitHub リポジトリに依存する GitHub リポジトリのパッケージには GitHub OAuth のトークンが必要という順番みたいです。

現在の Qithub のパッケージの依存は以下のようになっているので、今回の現象が出たもよう。

- Qithub-API →（依存）→ Qithub-CMD
- Qithub-CMD →（依存）→ Qithub-CORE

回避法としては、以下の３通りあるようです。

1. Packagist に載せてもらうように審査依頼を行いパッケージを公開する
2. 有料の Private Packagist でパッケージを公開する
3. カスタム・リポジトリの依存を Root からみて１階層目に収める
4. composer 実行時に API のトークンを指定する（今回は TravisCI の環境設定で指定）

Packagist に載せるような汎用ライブラリ開発をしているわけではないので、3 および 4 になると思います。

逆に言えば、配布パッケージ（Root パッケージ）に依存も含めて配布してしまえばいいということでもあります。デメリットは、依存先のアップデートがあるたびに Root パッケージも更新しないといけないことです。

基本的にサーバーで動かすことが最初の前提なので以下の２つの方向が妥当と思われます。

1. TravisCI のテストは (4) のトークン指定で行う（つまり従来通り）
2. Qithub クライアントなど、派生アプリでで使う場合は (3) の、依存を内包して配布

---

### 参考情報

- [Why can't Composer load repositories recursively?](https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md) @ getcomposer.org
- [Composerでgithubの認証を求められたときの対策](http://blog.inoaki.com/2015/06/phpcomposergithub.html) @ Akilno Blog
- [ComposerでGitHubのリポジトリをHTTPSで追加したときの認証設定](https://qiita.com/fivestar/items/fc15e0bb379c791ff6b2) @ Qiita
