### ISSUE TITLE
【報告】時報トゥートアカウント用のアイコン

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#105]
## 提案・報告

時報トゥートを行うアカウントのアイコンを作成しました。
改善要望があればぜひ。特になければ close でお願いし 💪 

<img src="https://raw.githubusercontent.com/Qithub-BOT/Qithub-ORG/master/images/Icon_Qiitime/Qiitime_512x512.png" width=150>

各種マスターの画像をリポジトリに公開しました。→ #106 

## TS;DR

「新着Qiita記事のお知らせトゥート」がタイムラインを汚しているという事案（下記関連issue参照）に対し、「時報トゥート」と「新着のお知らせ」のアカウントを分ける対策で、モチベアップのためにアイコンを作成しました。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue: 
    - [Qithub-API （旧 scripts）issue #92](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-92) 「新着Qiita記事 ハッシュタグ検索が機能しない件について」@ Wiki
    - [Qithub-API （旧 scripts）issue #93](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-93) 「Make tag list toots unlisted」@ wiki
    - [Qithub-API （旧 scripts）issue #94](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-94) 「Qithub-BOT の一時停止と体制の見直し」 @ Wiki

----------------

## TL;DR（結論 2018/06/14 現在）

- 確認済み

**Comment by hidao80** [comment]
👍😎🙏
