### ISSUE TITLE
【報告】各種ロゴ／アイコンのマスターを公開

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#106]
## 報告

Qithub のロゴやアイコンを当リポジトリの以下のパスに公開しました。

- マスター画像の保存（公開）先<br>https://github.com/Qithub-BOT/Qithub-ORG/tree/master/images

問題なければ close お願いし 💪 

## 概要

- `.mdp` ファイル： [FireAlpaca](http://firealpaca.com/ja/)というフリーのラスタ系ペイント・ツールのフォーマットです。基本的にこれがマスターとなります。
- `.png` ファイル： 「タイトル_サイズ.png」のフォーマットでリリース（公開）されたものです。
- 画像のライセンスは当リポジトリと同等とします。

業界でデファクト・スタンダードのフォトショ（`.psd`）フォーマットは~~面倒なので~~公開してません。
必要なようであれば PR お願いします。

## TL;DR（結論 2018/06/14 現在）

- 確認済み

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連issue:
    - #18 Qithub のロゴやキャラクター
    - #105 時報トゥート用のアイコン

**Comment by hidao80** [comment]
👍😎🙏

QiiTime 、フクロウモチーフですか。（ですよね？）

夜いっぱりになりそうw

**Comment by KEINOS** [comment]
> QiiTime 、フクロウモチーフですか。（ですよね？）

そう言われると、フクロウに見えてきたw
太った鳩にするには、もう一工夫ってとこですかね？w

**Comment by hidao80** [comment]
目の周りのフチが耳の外側まであったのが鳩っぽくなかったのかな？

耳がある時点で、フクロウ有利…

**Comment by KEINOS** [comment]
目の周りのフチの線って、実はクチバシを付けるためのヒモを耳にかけてるつもりだったんです。orz

フクロウと思ってしまうと、そうしか見えない。紐と耳が改善ポイントっすな。w #105
