### ISSUE TITLE
【相談】時報トゥートのアカウント名の命名（「QiiTime」はどうか）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#107]
## 相談

時報トゥートのアカウント名／表示名を「QiiTime」にしたいと思うのですがいかがでしょう？

- 登録名（メンション名）： `@qiitime`
- 表示名：「QiiTime」

上記は Qiitadon / Qiita 共に同じ。

## 理由

1. 「時報トゥート」と「新着Qiita記事のトゥート」のアカウントをわける。
1. 時報トゥートに対して別アカウントから新着のお知らせを返信する。<br>（ ∴「公開」ステータスでも LTL に流れない）
1. 記事のタグは「<タグ名>_qiita」に置換してトゥートする<br> （例：Electron_qiita 、[Qithub-API 旧 scripts issue #92](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-92#379895555) @ Wiki)

上記は本文下部にある関連 issue により決定した内容ですが、時報トゥートのアカウントを新規作成するにあたり、命名の確認をしたいです。問題なければ、アカウント作成後、close し 💪 

## 補足

自身のテスト用アカウントを使おうかとも思いましたが、メンションするときに `KEINOS` が含まれてしまうため

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue: 
    - [Qithub-API （旧 scripts）issue #92](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-92) 「新着Qiita記事 ハッシュタグ検索が機能しない件について」@ Wiki
    - [Qithub-API （旧 scripts）issue #93](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-93) 「Make tag list toots unlisted」@ wiki
    - [Qithub-API （旧 scripts）issue #94](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-94) 「Qithub-BOT の一時停止と体制の見直し」 @ Wiki

----------------

## TL;DR（進捗 2018/09/04 現在）

- [x] アカウント名は「QiiTime」で確定
- [x] Qiita アカウントの作成
- [x] Qiitadon アカウントの作成
- [ ] アカウント情報のドキュメント化 @ Wiki
- [x] アカウント・アイコンを緑のフクロウから太った鳩に改善

**Comment by hidao80** [comment]
👍😎🙏

**Comment by KEINOS** [comment]
時報アカウントのロゴをフクロウから、より鳩っぽくしてみました。いかがでしょう？

<kbd><img src="https://raw.githubusercontent.com/Qithub-BOT/Qithub-ORG/b3a9822c529d1e6142dc9d57e7c99ce90c3db7e9/images/Icon_Qiitime/Qiitime_512x512.png"></kbd>

**Comment by hidao80** [comment]
LGTM! より鳩っぽいです！ 👍

**Comment by KEINOS** [comment]
一連のアカウント作成から実装を行いました。

QiiTime のアカウント情報（パスワードなど）を共有したいのですが、とりあえずこの issue は Close でいいかな、と思います。無問題であればおてすきで Close お願いし 💪

**Comment by hidao80** [comment]
👍
