### ISSUE TITLE
【報告】開発・検証用にリポジトリをサーバにクローンできるようにしました

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#109]
## 報告

開発用ドメイン https://dev.qithub.tk に、任意のリポジトリをマウントして Web からアクセスできるようにしました。

### 概要

開発用ドメインの本体である [Qithub-DEV](https://github.com/Qithub-BOT/Qithub-DEV) リポジトリに**個別リポジトリのクローン機能を実装**しました。

Qithub-DEV リポジトリにある設定用の JSON ファイル "[repos_user.json](https://github.com/Qithub-BOT/Qithub-DEV/blob/master/repos_user.json)" に、マウントさせたいリポジトリ情報（URL など）を記載すると、お遊びサーバの `https://dev.qithub.tk/_<リポジトリ名>` にマウントできます。**実装前の検証や開発にお使いください**。

### マウント手順

以下を行うと、指定したリポジトリが [Webサーバ](https://dev.qithub.tk/)にマウントされ、ブラウザからアクセス可能になります。

1. [JSON ファイル](https://github.com/Qithub-BOT/Qithub-DEV/blob/master/repos_user.json)にマウントしたいリポジトリを記載
1. Push/PullRequest & マージする
1. 下記更新 URL が WebHook で叩かれる（サーバにクローンされる）

    #### 更新 URL （2018/09/13現在）
    ```
    https://dev.qithub.tk/tools/update/
    ```

アンマウントは、JSON ファイルからリポジトリ情報を削除して同じ手順です。

### マウントしたリポジトリの URL

`https://dev.qithub.tk/_<リポジトリ名>`

`clone` 時、設定したリポジトリ名の頭に `_` を付けて `DocumentRoot` 直下に `clone` されます。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue94  [新年度（2018）の Organization のリポジトリ整理](https://github.com/Qithub-BOT/Qithub-ORG/issues/94)

----------------

## TL;DR（進捗 2019/06/12 現在）

- ~~マウントされたリポジトリの更新の挙動が怪しい~~
- Core OS に移行するため不要な機能になるのでクローズ

**Comment by hidao80** [comment]
質問です。
1. fork したリポジトリをサーバにプッシュできるのですか？
2. 本リポジトリのJSONファイルを配列にして追記するイメージですか？
3. Webhook の設定は fork したリポジトリでも必要ですか？

**Comment by KEINOS** [comment]
> 1. fork したリポジトリをサーバにプッシュできるのですか？

**はい**。`https://github.com/〜/〜.git` の URL であれば何でもマウントできます。

> 2. 本リポジトリのJSONファイルを配列にして追記するイメージですか？

**はい**。 [README.md のページ下部の記述サンプル](https://github.com/Qithub-BOT/Qithub-DEV#%E8%A8%98%E8%BF%B0%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB)が参考になると思います。

> 3. Webhook の設定は fork したリポジトリでも必要ですか？

**いいえ**。一度 WEB サーバにマウントされたリポジトリの更新は URL を開けばいいだけなので**必須ではありません**。

ただ、fork しているリポジトリの Webhook 設定（更新 URL を登録）をする方が毎度叩かなくていいので楽だと思います。

<kbd>
<img width="750" alt="2018-06-30 15 48 12" src="https://user-images.githubusercontent.com/11840938/42122477-77ef0b36-7c7d-11e8-8211-a1e5d3ed64f7.png">
</kbd>

**Comment by KEINOS** [comment]
改めて Issue 内容を読むとわかりづらかったので修正しました。

しかし、JSON で指定したリポジトリの初回マウント（`clone`）まではいいのですが、マウント済みのリポジトリの更新（`pull`）の挙動がどうも怪しいのでチェックいたします。 → TL;DR 追記済み

**Comment by KEINOS** [comment]
これも OS 移行で不要になるので、クローズしたいと思います。
