### ISSUE TITLE
BOT のトゥートの公開範囲を決めましょう

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#11]
これはQiitadonユーザに関する問題なので`items`リポジトリに issue をあげました。

基本「公開トゥートはしない」が無難だと思いますが、Mastodonには「ミュート」や「ブロック」という機能があるため、**少し攻めてもいいかな**とも思います。

BOTアカウントの説明文に「邪魔と感じる場合はブロックしてください」的なメッセージを入れておくとか。

ただ、なんでもかんでも公開トゥートはよくないと思うので、「公開」の線引きとしては

    トゥートに含むハッシュタグを検索対象にしたい（タグストリームに表示させたい）場合は「公開」ステータスでトゥート

はいかがでしょう。

また、以下は公開範囲の対象（定義が必要なもの）の一覧です。

| ステータス | 範囲 | 条件 |
| --- | --- | --- |
| 公開 | 全体に公開 | ハッシュタグを検索対象にしたい（仮） |
| 未収載 | 誰でもみれるが検索対象にされない | （未定義） |
| 非公開 | フォロワーだけが見れる。検索にもでない | （未定義）|
| ダイレクト | メンション相手だけが見れる | （未定義） |

-----------

## TL;DR（結論： 2017/11/17 現在）

> ユーザーのキュレーションにより「**このボットは面白い記事ばかりブーストされてるな**」と思ってもらえること

#### トゥートの基本公開範囲
- 基本は**非公開**とし、フォロワーのみが閲覧可能とする
- フォロワーに関するものは**未収載**とし、フォロワー意外でも閲覧可能にする
- フォロワーからの一定評価があった内容に関しては**公開**でトゥートする

#### 新着Qiita記事の公開範囲
- 定時（朝、昼、晩）トゥートは開始のアナウンスのみとし、**公開**でトゥート
- cronによる定期チェックにより、新着Qiita記事のお知らせは定時トゥートに**非公開**で返信
- 特例として、新着Qiita記事がフォロワーの記事の場合は**未収載**で返信
- cronの定期チェックで「ブースト数」「お気に入り数」が一定数を超えたものは**公開**で別途トゥート

※ 以下の機能に関しては、**基本の実装が出来てからの拡張案件**とし、別途 issue を立てることとします。
> 「フォロワーから個別にメンションされたタグを含む新着Qiita記事は、個別にフォロワーへダイレクト・トゥートする」機能

**Comment by hidao80** [comment]
公開の線引きが非常に危ういことを危惧します。

本システムを使って記事を公開しようとするコラボレータは PV 増やしたいのが本音だと思うので、すべての投稿に「公開キーとなるタグ」か付けられると予想します。

「大量に LTL に流して（しかも同じアカウントで）ヘイトを買うようなことはしない方がいい」と言うのが私の意見です。

### 代案

まずは非公開で始めて、一日3回（朝昼晩）LTL に「BOT やってるよ！ フォローしてね！」と cron でトゥートするのはどうでしょう？

余計にヘイトを買うかなぁ…

**Comment by KEINOS** [comment]
新着Qiita記事の通知に特化して話します。

> 非公開で始めて、一日3回（朝昼晩）LTL に「BOT やってるよ！ フォローしてね！」

この路線が良いと思います。
色々考えてみたのですが、以下のような形式であればLTLも汚さないのかな、と。

① 朝一のトゥート（公開トゥート）
```
おはようございマストドン。本日のQiitaの新着記事のトゥートをはじめるよ！

このトゥートに非公開で返信していくから、興味のある人はフォローしてね！
```
② 以降のトゥートは非公開で①に返信
```
「RaspberryPiで玉子を焼いてみた」 ＠hidao80
https://qiita.com/hidao80/items/xxxxxxxxxxx
#RPi #ヒーター #機械制御
```
```
etc...以下同文
```

③ 昼と晩に、以下のようなとりまとめを公開で①に返信トゥート
```
本日（2018/09/xx）の08:00〜12:00の間に投稿されたQiitaの新着記事に含まれたタグを報告するよ！
[CW]
#rpi #ヒーター #機械制御 #php #python #RNN
[/CW]
```

実際にやってみると抜けがあるかもですが、、、

**Comment by KEINOS** [comment]
#13 のissueで思いついたのですが、`PV 増やしたいのが本音`も確かにあるので

    公開範囲の基本は非公開

でOK 👌 

なのですが、「新着Qiita記事のお知らせ」のうち、フォロワーのものであれば、それを未収載でトゥートし、その通知に付いた 👍 やブーストの数によって公開トゥートを改めてトゥートさせるのはどうでしょう？

それであれば、PV目的をある程度抑えられると思います。

仕組みが複雑かしら。

**Comment by hidao80** [comment]
未収載いいアイデアだと思います。

公開トゥートをしない方がいいというのは、フォロワーのブーストに任せたほうが「bot の評価が上がる」と考えられるためです。

bot をメディアに、フォロワーをキュレーターにする戦略です。

1. フォロワーにブーストされる→公開される
2. ブーストされない記事はPV伸びない→キュレートされている状態
3. LTL からは「**このボットは面白い記事ばかりブーストされてるな**」という風に見える
4. 「ソースをフォローするべ」と思わせる
5. フォロワーを獲得する
6. 完 全 勝 利

…となったらいいな。

それ以上に、「すべて定時トゥートに返信する」という方式が会心のひらめき、もしかしたらエポックメイキングかもしれません。

というのも、定時トゥートに返信をつけまくる事で、LTL もホームも汚さないタイムライン、すなわち「新しい別次元のタイムライン」を生み出しているからです！（フォロワー除く）

これはtwittet でもList機能相当のものがないとできず、Mastdon では現在この方法しかないと思います。

この返信の流れの中でフォロワー同士がボットを絡めてメンションし合えば「未収載より狭く、DMより公開範囲が広いトゥート」ができるのでは？ と感じています。（要検証）

オラ、ワクワクしたきたぞ！

**Comment by KEINOS** [comment]
> bot をメディアに、フォロワーをキュレーターにする戦略です。

`フォロワーをキュレーターに`なってもらうのは良い考えですね！

> オラ、ワクワクしたきたぞ！

ですね！ 😄 👍 

アカウント類の準備はできたので、いよいよBOTに取りかかれますね！

確認ですが「**BOTのトゥートの公開範囲**」は以下でとりあえずOKクローズでしょうか。
実際には要検証ですが、NGの場合は再オープンするということで。

## トゥートの基本公開範囲
- 基本は**非公開**とし、フォロワーのみが閲覧可能とする
- フォロワーに関するものは**未収載**とし、フォロワー意外でも閲覧可能にする
- フォロワーからの一定評価があった内容に関しては**公開**でトゥートする

## 新着Qiita記事の公開範囲
- 定時（朝、昼、晩）トゥートは開始のアナウンスのみとし、**公開**でトゥート
- cronによる定期チェックにより、新着Qiita記事のお知らせは定時トゥートに**非公開**で返信
- 特例として、新着Qiita記事がフォロワーの記事の場合は**未収載**で返信
- cronの定期チェックで「ブースト数」「お気に入り数」が一定数を超えたものは**公開**で別途トゥート

「フォロワーから個別にメンションされたタグを含む新着Qiita記事は、個別にフォロワーへダイレクト・トゥートする」機能に関しては、基本の実装ができてからの拡張案件とし、別途 issue を立てることとします。

**Comment by hidao80** [comment]
:thumbsup:

**Comment by KEINOS** [comment]
# Tootの公開範囲の仕様
## トゥートの基本公開範囲
- 基本は**非公開**とし、フォロワーのみが閲覧可能とする
- フォロワーに関するものは**未収載**とし、フォロワー意外でも閲覧可能にする
- フォロワーからの一定評価があった内容に関しては**公開**でトゥートする

## 新着Qiita記事の公開範囲
- 定時（朝、昼、晩）トゥートは開始のアナウンスのみとし、**公開**でトゥート
- cronによる定期チェックにより、新着Qiita記事のお知らせは定時トゥートに**非公開**で返信
- 特例として、新着Qiita記事がフォロワーの記事の場合は**未収載**で返信
- cronの定期チェックで「ブースト数」「お気に入り数」が一定数を超えたものは**公開**で別途トゥート

※ 以下の機能に関しては、**基本の実装が出来てからの拡張案件**とし、別途 issue を立てることとします。
> 「フォロワーから個別にメンションされたタグを含む新着Qiita記事は、個別にフォロワーへダイレクト・トゥートする」機能
