### ISSUE TITLE
【報告】Qithub-API リポジトリを削除します

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#110]
## 報告と確認

 [Qithub-API](https://github.com/Qithub-BOT/Qithub-API) のリポジトリを明日（2018/~~06/30~~ 07/01 日曜）削除いたします。問題なければ 😎 👌 ？

Issue #98 で議論されたように `https://api.qithub.tk/` は排除し `https://qithub.tk/api/` で動かすことになったので、リポジトリ自体が不要になったのと混乱を避けるためです。

これに伴い、今後のフロントエンド向けのエンドポイントが変わります。（一回も使ってなかったけど）

また、Qithub-API にあるコードは `script` や `plugins` などの古い仕様や表現に沿った作りになっているので、基本的に作り直しになりますが、基本的な仕様は変わりません。

## TL;DR（結論 2018/07/01 現在）

- 2018/07/01 07:58 削除いたしました

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- Issue #98 「[サイト Qithub.tk のディレクトリ構造とサイトの自動更新](https://github.com/Qithub-BOT/Qithub-ORG/issues/98)」

**Comment by hidao80** [comment]
👍👌😎🙏

余談：6/30 は土曜やで…

**Comment by KEINOS** [comment]
> 6/30 は土曜やで…

Σ(- -ﾉ)ﾉ ﾊｯ!?

**Comment by KEINOS** [comment]
Qithub-API のリポジトリ削除いたしましたので Close いたし 💪
