### ISSUE TITLE
【報告】Qithub-CMD の Wiki を Qithub-ORG に引っ越しました

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#111]
## 報告

- [Qithub-CMD の Wiki](https://github.com/Qithub-BOT/Qithub-CMD/wiki) → Qithub-ORG の Wiki に[引っ越しました](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E9%96%8B%E7%99%BA-Wiki--%5BTOP%5D)。
- Qithub-ORG の Wiki リポジトリ内のファイルを整頓しました。（ディレクトリにわけました）

- Qithub-ORG の Wiki repo:  https://github.com/Qithub-BOT/Qithub-ORG.wiki.git

## 詳細

Qithub コマンドの仕様を Qithub-CMD の Wiki 上に記載していたのですが、情報量が思ったより増え、やはり横断検索が不便なので、Qithub-API の issue の時と同様に **Qithub-ORG に Wiki も統一しました**。

その際に、既存ファイル（Wikiの中身）を以下のように整理しました。Wiki の Repo をクローンされていましたら、ローカルの更新をお願いします。

```
━┳━ Home.md （Wikiのトップ）
　┣━ _Sidebar.md （サイドバー）
　┣━ rules-general / （いままでのファイルはここ）
　┃　　┣ ライセンス.md
　┃　　┣ ラベルのルール.md
　┃　　⋮
　┣━ rules-command / （Qithub-CMD の Wiki 引っ越し先）
　┃　　┣ コマンドの命名規約.md
　┃　　┣ コマンド開発の基本概要.md
　┃　　⋮
　┣━ issues / （Qithub-API の 旧 issue 一覧）
　┃　　┣ Issue list of Qithub-API.md
　┃　　┣ Qithub-API Issue 1.md
　┃　　⋮
　⋮
```

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue #96 [Qithub-API（旧scripts）の issue 引っ越しは必要か](https://github.com/Qithub-BOT/Qithub-ORG/issues/96)

----------------

## TL;DR（結論 2018/07/01 現在）

- 確認済み

**Comment by hidao80** [comment]
LGTM！👍

…ですが、wikiリポジトリへのリンク(<https://github.com/Qithub-BOT/Qithub-ORG.wiki.git>)がデッドリンクですよ…。

**Comment by KEINOS** [comment]
ほんとだ、開かないですね。ただ、ダブルチェックしても同じ URL でした。（[Wiki](https://github.com/Qithub-BOT/Qithub-ORG/wiki)の右下にあるリンク）

Git のプロトコルか何かで反応があるものなのかもしれないですですね。

**Comment by KEINOS** [comment]
Wiki を引っ越したのはいいのですが、リンクが絶対パスになっていたため デッドリンクになっていたものを修正しました。
