### ISSUE TITLE
【報告】Qithub-ORG/tools/ 下に GitHub の公開鍵を用いたファイルの暗号ツールを公開しました

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#112]
## 報告

事後報告ですが Organization のメンバー間でセンシティブなファイルのやりとりが必要な場合の **GitHub 公開鍵を使った暗号ツール群を作成しました**。[Qithub-ORG/tools/crypt/](https://github.com/Qithub-BOT/Qithub-ORG/tree/master/tools/crypt) に設置しています。

- Bash による CLI アプリです。
- OpenSSL のコマンドのラッパーです。
- 現在 macOS でしか検証していませんが、他の OS にも対応させていきたいと思います。

### @KEINOS が @hidao80 氏にファイルを送る場合の暗号化
（[@hidao80 氏の GitHub 公開鍵](https://github.com/hidao80.keys)の一番上の鍵を使って暗号化）

```
$ enc hidao80 himitsu.txt himitsu.txt.enc
```

### @hidao80 氏が受け取った暗号ファイルの復号
（@hidao80 氏のローカルの秘密鍵で復号。GitHub の公開鍵とペアのもの）
```
$ dec ~/.ssh/id_rsa himitsu.txt.enc himitsu.txt
```

その他、ファイルのRSA署名（`sign`）や署名の確認（`verify`）などがあります。[Gitea のような GPG署名（`.asc`）](https://github.com/go-gitea/gitea/releases)は macOS 標準の機能ではできなさそうなので検討中です。

## 補足

長らくペンディング issue になっている #92 `Qithub CLI クライアント` に関しても、同じようにこのリポジトリ内の "tools" で提供するという方向で #92 をクローズしてはと思うのですがいかがでしょう？

## TL;DR（結論 2018/07/26 現在）

- CLI クライアントは ["tools"](https://github.com/Qithub-BOT/Qithub-ORG/tree/master/tools)ディレクトリ下で提供する。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- #92 Qithub CLI クライアントの作成とリポジトリの引っ越し

**Comment by hidao80** [comment]
@KEINOS LGTM👍

カギ自体はいつ準備するんだろう？ と思っていましたが、GitHub で準備（生成）できるんですね。

公開カギの受け渡しが自動でできるのはありがたいです。

補足についても同意します。

**Comment by KEINOS** [comment]
> 公開カギの受け渡しが自動でできるのはありがたいです。

はい。簡単に生成できるだけでなく、GitHub を利用（頻繁に Push/PR ）してる人はすでに公開鍵を登録している人が多いと思うので GitHub オリエンテッドなコマンドにしてシンプルにしました。

コマンドの不具合、他 OS 対応などは適宜 issue をたてたり Push/RP していきますので、この issue はクローズしまーす。 > TL;DR 済
