### ISSUE TITLE
【報告】QiiTime を実装しました

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#115]
## 報告

QiiTime（ https://qiitadon.com/@QiiTime ）の実装を行いました。

- BOT のトリガー URL： https://qithub.tk/api/v1/qiitime/
- BOT のREADME： https://github.com/Qithub-BOT/Qithub-ORG/tree/master/api/v1/qiitime
- BOT のソース： https://github.com/Qithub-BOT/Qithub-ORG/blob/master/api/v1/qiitime/index.php

トリガーされると以下の動作を行います。

- １時間ごとに時報トゥートする。
- 同時間内でトゥート済みの場合は何もしない。
- 時間内・外、いずれも **URL が叩かれると最後のトゥート ID などの情報が返ってくる**。

## TL;DR（結論 2018/09/04 現在）

現在は未収載でトゥートしています。明日（2018/09/04 水）まで様子を見て、安定しているようであれば、ステータスを公開に変更した PR で Close したいと思います。気になる点などがあれば、おてすきにぜひぜひ〜

- コミット 36d2b63 で Close しマスター

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue : #107 【相談】時報トゥートのアカウント名の命名（「QiiTime」はどうか）

**Comment by hidao80** [comment]
👍
