### ISSUE TITLE
【報告】Cron を用意しました（Hourly）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#116]
## 報告

QiiTime を叩くのに１時間ごとに Cron で叩ける環境を作りました。

下記ファイルに実行したい `bash` コマンドを記述すると、１時間ごとに呼び出されるようになります。

https://github.com/Qithub-BOT/Qithub-ORG/blob/master/tools/cron/hourly.sh

- Commit 6d06ea8

## TL;DR（結論 2018/09/04 現在）

- 確認済み

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue ：　#115 「QiiTimeを実装しました」

**Comment by hidao80** [comment]
👍
