### ISSUE TITLE
【報告】QiiTime のトゥートステータスを変更しても反映されない

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#117]
## 報告

QiiTime の [`visibility` を `public` に変更](https://github.com/Qithub-BOT/Qithub-ORG/commit/36d2b634080296b92951bf47e33bb5751deefec2)しても[反映されない](https://qiitadon.com/@QiiTime/100670924570260701)。

https://github.com/Qithub-BOT/Qithub-ORG/blob/36d2b634080296b92951bf47e33bb5751deefec2/api/v1/qiitime/index.php#L39-L49

## 原因

デフォルトの設定が使われるのが初回トゥート時のみであるため。

以降はキャッシュされたデータを元に稼働するので、デフォルト値を変更しただけでは反映されないことが原因。

https://github.com/Qithub-BOT/Qithub-ORG/blob/36d2b634080296b92951bf47e33bb5751deefec2/api/v1/qiitime/index.php#L78-L82

## 暫定回避

とりあえず SSH 接続で手動でキャッシュ・データを修正しました。

## 抜本対策案A

- API リクエスト時に、アクセストークンと一緒に設定が渡された場合は、設定変更を適用する。

## TL;DR（結論 2019/06/12 現在）

- 現状のスクリプトは未対策ですが、[コンテナ化した QiiTime](https://github.com/Qithub-BOT/QiiTime) は抜本的な対策済みなのでクローズ

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue #115 「QiiTimeを実装しました」

**Comment by hidao80** [comment]
#148 で対応済みとしてCloseし💪？

**Comment by KEINOS** [comment]
@hidao80 

実は、これまだ根本的に修正できてないんですよね。。。
Close すると忘れちゃうので、もうしばらく置いておいてください。 🙇

**Comment by KEINOS** [comment]
現状のスクリプトは不具合が残ったままですが、[コンテナ化した QiiTime](https://github.com/Qithub-BOT/QiiTime) は抜本的な対策がされているので、クローズします。
