### ISSUE TITLE
【報告】Wiki の目次の自動作成

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#119]
## 報告

せっかく @hidao80 さんが [Qithub-ORG の Wiki リポジトリ](https://github.com/Qithub-BOT/Qithub-ORG/wiki)にドキュメント化してくれているのに、いささか探しづらいと感じたので以下を[自動で行うスクリプト](https://raw.githubusercontent.com/wiki/Qithub-BOT/Qithub-ORG/generateIndex.php)を Wiki のリポジトリに設置しました。

- Wiki のリポジトリ内にディレクトリを作成すると、ディレクトリ内のファイル一覧が作成される。
-  右サイドに、ディレクトリ別の目次を追加する。

### イメージ

![home qithub bot qithub org wiki](https://user-images.githubusercontent.com/11840938/45165824-943cff80-b230-11e8-85d5-fa36761820d0.png)

### 詳細

Issue #111 の [Wiki リポジトリの整理を行った](https://github.com/Qithub-BOT/Qithub-ORG/issues/111) 際に、リポジトリ内に作成したディレクトリですが、ディレクトリ内のファイル一覧が作成されるようにしました。

Wiki のリポジトリをローカルにクローンして、ジェネレーターをコマンドラインから実行してください。

以下は現在の Wiki のディレクトリの構成イメージです。

```
.
├── Home.md                ← Wiki トップページ
├── _Sidebar.md            ← サイドの目次ファイル
├── generateIndex.php      ← 目次ジェネレーター・スクリプト
│
├── Qithub コマンド Wiki.md ← ディレクトリ内のファイル一覧
├── rules-command.json     ← 並び順ファイル
├── rules-command
│   ├── Qithub-コマンド開発-Wiki--[TOP].md
│   ├── ...
│   └── 同一コマンドを別のプログラム言語で開発する.md
│
├── Qithub ORG ルール.md   ← ディレクトリ内のファイル一覧
├── rules-general.json    ← 並び順ファイル
├── rules-general
│   ├── BOT-の動作.md
│   ├── ...
│   ├── 記事のフォーマット（タグとライセンス）.md
```

- ジェネレーター・スクリプト: https://github.com/Qithub-BOT/Qithub-ORG/wiki/generateIndex.php
- 並び順ファイル: https://github.com/Qithub-BOT/Qithub-ORG/wiki/rules-general.json

### 項目の並び替え

JSON ファイル内の並び順を変えて、再度ジェネレーターを走らせると、Markdown の並びもそれに追従します。

### 問題点

GitHub 上から目次（Markdown）を修正しても、ジェネレーターを走らせた場合、上書きされるので、自動生成された旨も記載した方がいいかもしれません。

## TL;DR（結論 2018/09/11 現在）

- JSON の目次並びの管理ファイルを `index.json.md` に統一
- 並び順は Wiki 上から変更可能
- 現在は、目次の更新はローカルで手動で行う。（将来的には WebHook で実行＆PUSH予定）

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue： #111 【報告】Qithub-CMD の Wiki を Qithub-ORG に引っ越しました 
- 関連 issue：  #96  Qithub-API（旧scripts）の issue 引っ越しは必要か

**Comment by hidao80** [comment]
👌  😎 🙏

**Comment by hidao80** [comment]
Wiki に新しいページを追加したのを hook して自動化できないもんですかねぇ…

**Comment by KEINOS** [comment]
なんか GitHub のリポジトリの WebHook に Wiki がおる。

![webhook https qithub tk tools update](https://user-images.githubusercontent.com/11840938/45169821-5c868580-b239-11e8-865c-0e01d0d51b36.png)

となると、サーバーが Hook を受けたらクローンしている Wiki リポジトリをフェッチーのして一覧の更新までは行けるーの、としても問題は Push か、、、

**Comment by alice1017** [comment]
Wikiの更新をすると、Webhookに `Gollum` というイベントがくるらしいです

>Event Types & Payloads | GitHub Developer Guide - https://developer.github.com/v3/activity/events/types/#gollumevent

**Comment by KEINOS** [comment]
@hidao80 

「[目次生成スクリプト](https://github.com/Qithub-BOT/Qithub-ORG/wiki/generateIndex.php)」を走らせると、ディレクトリを見つけた際に同階層に「ディレクトリ名.json」が作成されます。（これが目次の並び順ファイルになります）

そして、ディレクトリ名に対する日本語表記名（上記イメージ図だと「Qithub ORG ルール」のタイトル部分）は生成スクリプト本体に記述する仕様になっています。

以下に変更仕様と思うのですが、ドキュメンターとしていかがですか？現状でも問題なさ SAW？

- 同階層でなくディレクトリ下に「ディレクトリ名.json」を作成。
- ディレクトリ名の日本語表記（一覧のタイトル）は「ディレクトリ名.json」に記述する。（スクリプト本体をいじらなくてもよい）
- 目次ファイルは現状維持（「ディレクトリ名（日本語）.md」として同階層に作成）

**Comment by hidao80** [comment]
むむむ、ツールのコードを見ていないのでめんどくささがわかりませんが、ドキュメントルートに`index.json`を生成して、1ファイルにまとめると不都合がありますか？

jsonを分割すると、目次md生成と同じタイミングでオンメモリのデータを流用できる気がするので現在の仕様になっていると思われますが、**手動メンテナンス性(しないと思いますが)を考えると、全体目次jsonファイルは単一であった方が好ましい**と考えますがいかがでしょうか。🤔

ディレクトリ内を走査したときに、mdファイル以外のノイズが入らなくなるという副次効果も得られると考えます。

**Comment by KEINOS** [comment]
> `index.json` を生成して、1ファイルにまとめると不都合がありますか？

大丈夫です。JSON の分割は、ディレクトリ毎の処理をループさせて横着しているだけなので。

では、**ドキュメントルートに `index.md` という JSON データを吐き出させる**ようにします。
それであれば GitHub 上からも順番を変更できると思うので。

**Comment by hidao80** [comment]
`index.md`⁉️ jsonですよね。typo?

**Comment by KEINOS** [comment]
`index.md` です。
拡張子が `.md` になると GitHub 上から編集できるんです。（はず
まぁ、開いたらただの JSON なのですが。

**Comment by KEINOS** [comment]
で、保存したら hook が飛んでポロンと一覧が、、、みたいな。

**Comment by hidao80** [comment]
そうか、Wiki 内では md ファイル以外編集できないんですね。知らなかった。😓(確認しました)

なるほど、それなら拡張子は md ですね。

欲を言えば、`index.json.md`の方が良いのかなぁ？

**Comment by KEINOS** [comment]
> `index.json.md` の方が良いのかなぁ？ @hidao80 

あぁ、そっちの方が直感的ですね。開いたら JSON がっ！とならずに済みますね。

１ファイルにディレクトリを含めると以下のフォーマットになりそうですが、いかがでしょう？`items` の並びを変えると一覧の並びも変わります。

```json
{
    "0": "ルートにあるファイル名1",
    "1": "ルートにあるファイル名2",
    "name_dir1": {
        "name_ja": "ディレクトリ名１",
        "items": [
            "Dir1内のドキュメント１",
            "Dir1内のドキュメント２",
            "Dir1内のドキュメント N"
        ]
    },
    "name_dir2": {
        "name_ja": "ディレクトリ名２",
        "items": [
            "Dir2内のドキュメント１",
            "Dir2内のドキュメント２",
            "Dir2内のドキュメント N"
        ]
    }
}
```

**Comment by KEINOS** [comment]
@hidao80 @alice1017

[Qithub-ORG の Wiki](https://github.com/Qithub-BOT/Qithub-ORG/wiki) の目次作成スクリプトを改善しました。
目次の並び順を「`index.json.md`」の１ファイルに統一し、並び順の編集を Wiki からできるようにしました。

<kbd>![qithub-org wiki](https://user-images.githubusercontent.com/11840938/45330503-c340d180-b5a0-11e8-93a7-7a1086b981c5.png)</kbd>

### 並び順の変更
<kbd>![qithub-org_wiki indexjson](https://user-images.githubusercontent.com/11840938/45330689-94772b00-b5a1-11e8-8a6b-4513d6f4579a.png)</kbd>

ただ、まだ WebHook での更新に対応していないので、目次の並び順の変更や新規ページの追加があった場合は手動で更新（ローカルでスクリプト実行＆`PUSH`）する必要があります。

お手すきにご確認いただき、問題ナッシングであれば 👍 ２つで Close します。

**Comment by KEINOS** [comment]
> [👌 😎 🙏](https://github.com/Qithub-BOT/Qithub-ORG/issues/119#issuecomment-419146291)

でしたね。では Close いたし 💪
