### ISSUE TITLE
プロジェクト メンバーの勧誘基準

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#12]
「来るもの拒まず」は当然としても、こっちサイドからのアプローチは難しい問題です。

まずは**BOTのフォロワーをどう増やすかが勧誘につながる**と思います。

つまり基準として「我々がやっていることを面白そうと感じる人」です。

というのも、以前（前身）の「新着Qiita記事のトゥートBOT」で大きく実感したのは、以下の２点です。

- 間違えて公開でトゥートしまくった時に他のインスタンスからのフォローが一気に増えた

- 「こいつ何か面白そうなことをやってるな。ダメダメだけど」と興味を持ってもらえるようになった

GitHubの場合、プルリクやissue立ち上げは必ずしもメンバーでなくてもコントリビュートできます。

そのうえで、**Organizationメンバーでないと出来ないこと**を考えると、現時点でわかっているのは以下の３点だと思います。

- ラベリング含むissueの采配
- issueの取り扱い
- プロジェクト進行

つまり、**ある程度の責任が発生する事項**なので、最初からOrganizationの参加を募集すると躊躇して厳しい気がします。自分がそうだったので。

逆に「BOTをフォローして、リプライやダイレクト・トゥートを行うことがプロジェクトに参加している」というくらいの基準でスタートするのもいいと思います。

まだイメージですが、以下のような感じでBOTを触ってもらって「面白い」とか「もっと●●させたい」と思ってもらえたらベストですよね。

```
@BOTch #create:issue 
タイトルとURLの間に改行を入れて欲しいです
```
↑ issueが発行された旨と、issue番号＋URLが返信される

```
@BOTch #help
```
↑ BOTで使えるコマンド一覧が返信される

```
@BOTch #find:qiita #PHP
```
↑ 「PHP」タグのついた人気Qiita記事 n 件が返信される

```
@BOTch #add:tag #PHP #RaspberryPi #RPi
```
↑ 自分に届く新着Qiita記事のフィルターを追加

```
@BOTch #create:qiita
#DeepLearning #NNR
はじめてのディープラーニング
- ディープラーニングと機械学習の違い[qiita:xxxxxxxxxxx]
- Pythonで画像認識してみた[qiita:yyyyyyyyyyyy]
- （略）
```
↑ 新規Qiitaコラボ記事が作成された旨が返信される

**Comment by hidao80** [comment]
### エコシステムのレイヤイメージ

オラオラ感がパネェ見出しになってしまった（汗

閑話休題。私が持つ、関係者とbotとの距離感のイメージは次のようなものです。
core（プロジェクトメンバ）が中心、contributor（コラボレータ）、follower（botをフォローしてくれているユーザ）の順に同心円にかぶさっているイメージです。
図が無くて申し訳ない。

### 求人方法

で、「もっとbotにうんぬんしたい・させたい」という範囲の人たちに訴求するのは、提案どおりのbot UI の追加だと思います。

まずはフォロワーの獲得からですね。「使って楽しい」がキーワードかもですね。

**Comment by KEINOS** [comment]
> 「使って楽しい」がキーワードかもですね。

「**使って楽しい**」いいですね！ 👍 

バームクーヘンのように外側の人の方が楽しめるのがいいですね。

中心が欲しければ作り手に加わる的な感じで。

**Comment by hidao80** [comment]
まさに！

だれも「メンテナさせてください！」とは言わんとです…

**Comment by KEINOS** [comment]
> だれも「メンテナさせてください！」とは言わんとです…

んだんだ。なので、現時点の「プロジェクトメンバーの勧誘基準」は以下で暫定制定してはどうでしょう？

    Qithubを『使って楽しい』と思ってくれた人を中心にアプローチしていく

**Comment by hidao80** [comment]
> Qithubを『使って楽しい』と思ってくれた人を中心にアプローチしていく

方針としては賛成ですが、定数的でないのが気になります。

なので、以下を勧誘基準として対案とします。

```
Qithub をフォローしており、投票一回以上、改善要求（トゥート、プルリク問わず）を一回以上している人の中から、Organizationメンバーの推薦を受けた人
```

で、どうでしょう？

キモは

- フォロワーの方が loyalty が高そう
- 意見を出してくる人は開発・仕様策定への興味がより強そう
- Organization のだれも知らない人を引き入れるのはちょっとコワい
- bot を勧誘したくない :)

**Comment by KEINOS** [comment]
以下でOKクローズでしょうか？

## Organizationへの勧誘基準

以下の条件を満たした人のうち、Organizationのメンバーから推薦を受けた人にお声がけする。

- [ ]  Qithub をフォローしている
- [ ] 投票および改善要求を一回以上している

なお、これはこちらからアプローチする場合の基準であり、自発的に参加希望がある場合は、これを拒まない。

**Comment by KEINOS** [comment]
閉じちゃった・・・

**Comment by hidao80** [comment]
:thumbsup:

**Comment by KEINOS** [comment]
👌
