### ISSUE TITLE
【相談】qiitime の CW メッセージ内に Org の告知文 or link を入れてはどうか

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#121]
## 提案

qiitime がいい具合に注目を集めているようです。

現在、qiitime の CW 内メッセージには API リファレンスへのリンクとトゥート ID へのリンクが含まれていますが、ここに Qithub-BOT/Qithub-ORG へのリンクも追記し、コラボレータ候補の方へ参加を促す告知してはどうでしょうか。

## 自分の案

- 時報トゥートの中に「本botはプロジェクト Qithub により開発・運営されています。プロジェクト Qithub は GitHub の公開リポジトリ(url)で活動しています。」という文言を入れてはどうでしょうか。

## 補足

- 上記文言中の「プロジェクト」という言葉は、正確には「Organization」ですが、GitHub慣れしていない方々への説明としては「プロジェクト」という表現のほうが理解しやすいかと考えています。

## TL;DR（結論 2018/09/08 現在）

- Mastodonクライアントによって CW が折り畳まれないため、CW メッセージは短くすることに。
- 代わりに固定メッセージとプロフィールを活用することに。

以下その内容

### CW 内メッセージ

> QiiTime は Qiita/Qiitadon の同人サークル Qithub のコラボ作品です。詳細は {固定トゥートURL} へ。コラボ・メンバー募集中！ :qiitan: #{Y_m_d_H} #{$Y_m_d} #{$Y_m}

### 固定トゥートメッセージ

> ​#QiiTimeとは Qiitadon インスタンスの時報 BOT です。
> 
> ニュースやメモなどのトゥートで LTL や FTL を汚したくない。でも後日ハッシュタグで検索対象にしたい。そんなトゥートがあれば、時報トゥートに公開で返信してね。
> 
> Mastodon API 経由で返信する場合は以下を参照してね。
> \- 最新の時報トゥートID： https://qithub.tk/api/v1/qiitime/ (JSON)
> \- QiiTime API に関して： https://github.com/Qithub-BOT/Qithub-ORG/tree/master/api/v1/qiitime
> 
> P.S. 利用方法、返信内容やインスタンスも問わないけど、ウチ（Qiitadon のインスタンス）をピンポンダッシュするようなことはしないでね。
> 
> 【QiiTime は Qiita/Qiitadon の同人サークル Qithub のコラボ作品です。】【コラボラー絶賛募集中！】
> 

### プロフィール

> Qiitadon で時報をトゥートするだけの BOT です。ポロッポー、ポロッポー
>
> 最新のトゥートID： https://qithub.tk/api/v1/qiitime/
> この BOT の詳細は https://qiitadon.com/@QiiTime/100691414720855633

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
QiiTime 、なんか良い感じで稼働してますね！

TL が活発になったので、以前のように誰もいなくなったビルの中で一人 Qiitan が時報を呟いていた感じがなくなった気がします。

> Qithub-BOT/Qithub-ORG へのリンクも追記し、コラボレータ候補の方へ参加を促す告知してはどうでしょうか。

いいですね。

「Organization」よりは「プロジェクト」の方が理解しやすいには全面同意ですが、プロジェクトというと進捗管理に縛られるイメージがあるので、もっと（実際にそうですが）「マッタリやってます感」が欲しいです。「同人サークル」とかはいかがでしょう？

「本 BOT は Qiita/Qiitadon の同人サークル Qithub により開発・運営されています。Qithub は GitHub の公開リポジトリで活動しています。(url)」

### 参加の敷居についての所感

本 Organization のリポジトリは「Qiita/Qiitadon ユーザーなら誰でも PR できるよ」としています。

それ自体は良いのですが、立ち上げ当初の「GitHub の OSS のコラボレーションって自分のせいで何か壊したら怖い」という者同士で「コラボの練習がてら、気兼ねなく参加できる公開リポジトリを立てよう」として始めたことを考えると、同じ敷居の高さのイメージを与えてしまっているのではないか、と感じるようになりました。

特に BOT などは１つ間違えると暴走するものなので、自分個人であれば自己責任で何とかなりますが、自分の PR のせいで暴走したヤヴァンゲリオンと化すかもと思うと気が引ける、みたいな。

もしかすると、我々が気づかない、コラボしづらい他の敷居もあるのかもしれません。

だから何をするという話はないのですがね。そんな気持ちの金曜日ということで。

**Comment by alice1017** [comment]
お疲れ様です。

### Qiitimeの本文について

ブラウザで閲覧している場合は内容が隠されますが、自分が使っているMastodonクライアントの場合は以下の画像のように表示されます。

<img src="https://user-images.githubusercontent.com/465679/45192766-53bba100-b285-11e8-8fc5-0def3e46a488.PNG" height="500px">

ブラウザでQiitadonを閲覧している人も多いとは思いますが、このようなクライアントで閲覧している場合はこれ以上本文を増やすとTLの邪魔（言い方が悪くてすみません :sweat: )になってしまうかもしれません。

**Comment by KEINOS** [comment]
@alice1017 

あー、非表示であっても、開く前にコンテンツの長さがわかるようになっているんですか！

確かに PWA の方だと開くまでコンテンツ量がわからないので、開いたらドバッと表示されるので、そのアプリの仕様はわかる気がします。

以下のようなイメージとばかりだと思ってました。重いコンダラです。そんな大きな区切りが毎回入るのはよろしくない（CWする意味もない）ですな。

<img src='https://user-images.githubusercontent.com/11840938/45193647-11489300-b28a-11e8-8734-ec1404f2570d.png' width='300px'>

では、CW 内のメッセージはサークルの紹介程度にして、プロフィールに詳細を記載する方向ではどうでしょう？

**Comment by alice1017** [comment]
@KEINOS 

いいと思います！
自分は、時報以外にも**定期**でサークルの紹介やQithub-BOT orgの紹介をトゥートしてもいいかなと思いました。

**Comment by hidao80** [comment]
@alice1017 

情報ありがとうございます！ 👍 

CW が伏せられている状態で表示領域を大きくとっていることは想定していませんでした。これは大変邪魔くさいですね… ぜひ改善したいです。

*****

@KEINOS 

## トゥート内容について

そうですね、プロフィールやBOTの扱い方に関しては、文言はともかく「プロフィール画面見て！(url)」くらいにしておいた方が良いでしょう。

また、qiitime が同人サークルによって運営されていて、コラボレータを募集していることは、朝昼晩の日に3度程度トゥートに含むことができれば more better ですね（めんどくさい注文）。

## 敷居の高さについて

確かに、暴走マシンを野に放ってしまうリスクを内包しているとなると、敷居が高く感じられてしまいますね。

**PR に対してはコードレビューをしている** (?)ことを明示した上で、レビュアーチームを置いて品質を担保できれば多少無謀な PR でも悪影響を出さずに運営できるのではないかと考えます。  PR を棄却する可能性を匂わせる必要がありますが。  
初期のレビュアーチームメンバは @KEINOS さんと私で良いのではないかと考えています。

PR に限らず、issue やリアクション( 👍 等)、Qiitadon 内でリクエストや「いいね！」だけでも嬉しい！ みたいな広告をした方がサークル参加の敷居が下がるかもしれませんね。

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

では　CW の内容は以下のような感じでどうでしょう？（Qiita/Qiitadon ファンは Qiitan ファン？）

> QiiTime は Qiitan の同人サークル Qithub のコラボ作品です。QiiTime や Qithub について詳しくはプロフィールをご覧ください。コラボ・メンバー募集中！ :qiitan: #2018_09_07_17 #2018_09_07 #2018_09

**Comment by hidao80** [comment]
# 赤ペン先生、推参。

## 代案 B

@KEINOS さん案を校正して、代案とします。

> QiiTime は Qiita/Qiitadon の同人サークル Qithub のコラボ作品です。詳細は {固定トゥートURL} へ。コラボ・メンバー募集中！ :qiitan: #2018_09_07_17 #2018_09_07 #2018_09

どや。

「Qiitan の同人サークル」って言う表現に引っかかりました。
別にキータンマニアという自覚がなかったもので…

## 追記

現行のトゥート内容は固定トゥートにした方がいいかもしれません。
プロフィール内容はたしか180文字までだったのでそんなに長く書けないかも…

**Comment by KEINOS** [comment]
> 「Qiitan の同人サークル」って言う表現に引っかかりました。
> 別にキータンマニアという自覚がなかったもので…

カタカナで「キータンマニア」と書くと怪しい点に引っかかりました。 😳

**Qiitan で遊ぶ**というか、Qiitan を神輿にした方が同人っぽいし参加しやすいのかな、とのフラッシュアイデアでした。（成果物が Qiitan のロゴの方が多いし 😅）

> 現行のトゥート内容は固定トゥートにした方がいいかもしれません。
> プロフィール内容はたしか180文字までだったのでそんなに長く書けないかも…

これは QiiTime の詳細トゥートを手動で一発打っておいて、固定トゥートにするということでしょうか。
それとも、最新の時報トゥートを固定にする？

**Comment by hidao80** [comment]
> これは QiiTime の詳細トゥートを手動で一発打っておいて、固定トゥートにするということでしょうか。
> それとも、最新の時報トゥートを固定にする？

手動で QiiTime の詳細や Org へのリンクを含むトゥートを一発打って、それを固定トゥートにするイメージです。言葉足らずでしたね🙇‍♂️

**Comment by KEINOS** [comment]
> 手動で QiiTime の詳細や Org へのリンクを含むトゥートを一発打って、それを固定トゥートにするイメージです。

🙆‍♂️ では、こんな感じ？↓

## CW 内メッセージ

> QiiTime は Qiita/Qiitadon の同人サークル Qithub のコラボ作品です。詳細は {固定トゥートURL} へ。コラボ・メンバー募集中！ :qiitan: #{Y_m_d_H} #{$Y_m_d} #{$Y_m}

## 固定トゥートメッセージ

> ​#QiiTimeとは Qiitadon インスタンスの時報 BOT です。
> 
> ニュースやメモなどのトゥートで LTL や FTL を汚したくない。でも後日ハッシュタグで検索対象にしたい。そんなトゥートがあれば、時報トゥートに公開で返信してね。
> 
> Mastodon API 経由で返信する場合は以下を参照してね。
> \- 最新の時報トゥートID： https://qithub.tk/api/v1/qiitime/ (JSON)
> \- QiiTime API に関して： https://github.com/Qithub-BOT/Qithub-ORG/tree/master/api/v1/qiitime
> 
> P.S. 利用方法、返信内容やインスタンスも問わないけど、ウチ（Qiitadon のインスタンス）をピンポンダッシュするようなことはしないでね。
> 
> 【QiiTime は Qiita/Qiitadon の同人サークル Qithub のコラボ作品です。】【コラボラー絶賛募集中！】
> 

## プロフィール

> Qiitadon で時報をトゥートするだけの BOT です。ポロッポー、ポロッポー
> 
> LTL を汚さず、かつタグ検索でヒットさせたいトゥートがある場合は、時報トゥートに公開で返信してください。
> 最新のトゥートID： https://qithub.tk/api/v1/qiitime/
> 詳細は {固定トゥートURL} へ

**Comment by hidao80** [comment]
👍

我が意を得たり😏

**Comment by KEINOS** [comment]
> このトゥートの除外フィルターは「QiiTime」です。

の一文も入れた方がいいかしら。

**Comment by hidao80** [comment]
んー、じつはトゥートのフィルタ方法はクライアントによって微妙な差異があるので、明言しにくいところはあります。

それに、現在では Mastodon 自体にアカウント単位のミュート機能も実装されているため、**こちらからフィルター方法を提示しなくても良いのでは**と考えます。

**Comment by KEINOS** [comment]
> こちらからフィルター方法を提示しなくても良いのではと考えます。

👍 まずは上記を適用して、フィルターに関しては別途流れを見て、ということにしますか。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

TL;DR 更新しました。

今晩、手動トゥート（固定するトゥート）とプロフィール変更を終えたのち、QiiTime のスクリプトで CW 内容変更の Push で本 issue を Close します。 😎👌？（メンテナ特権でマージまで勝手に進めてOK？）

**Comment by hidao80** [comment]
👌😎🙏

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

短くなった CW 内容と、固定トゥートを実施いたしました。マージで Isuue Close しました。
なお、プロフィールが長かったので短くしました。> TL;DR 更新済み。

<img width="636" alt="2018-09-09 3 00 18" src="https://user-images.githubusercontent.com/11840938/45257163-9643c180-b3dc-11e8-8a3c-fb83eae21b9d.png">

**Comment by alice1017** [comment]
おそくなりましたが 👍
