### ISSUE TITLE
【相談】リポジトリを作るべきか、既存に組み込むべきか、それが問題です

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#122]
> 1つ質問があるのですが、こちらのQithub-BOTではPHPを主に使っている様ですが、
自分はPythonistaなので、もしbotなどをPythonで開発することができた場合は、
こちらQithub-BOT内にリポジトリを作っても良いのでしょうか？
https://github.com/Qithub-BOT/Qithub-ORG/issues/14#issuecomment-418974247 by @alice1017 さん

## 相談

Issues は[ここ](https://github.com/Qithub-BOT/Qithub-ORG/issues)にあげることを前提であれば、リポジトリは自由に作成できるという方針はどうか。

## 経緯

現在、サークル内ではペチャパー（PHPer）が多いため、某パイ星人（Pythonista）の方が参加しようにも嗜好が合わないということがありそうです。

確かにジャズ（JS）好きの人が同人サークルを覗いてみたらビジュアル系（VBA）だった、みたいな状態だと、「気にすんなYO！セッションしよう ZE！」と言われ入ろうにも難しいだろうなと思います。

（というか、とっとと Qithub BOT のエンジンを完成させて、多言語でコマンドが実行できるようになればいいだけなのですが、、、）

また、[夢の皮算用リスト](https://github.com/Qithub-BOT/Qithub-ORG/issues/14)を実現したい場合に、リポジトリをわけた方が開発しやすいというのもあると思います。

しかし、組織としての管理が難しくなるという反面もあるので難しいのですが、そんな組織だってもいないので Issue であげてくれたらリポジトリを作成しまっせくらいのゆるさでもいいのかな、と。

## TL;DR（結論 2018/09/08 現在）

リポジトリを作成したい場合は Organization のメンバーになっていただくことに。並びに、Organization メンバーになるための要件を以下のように制定。

- **Organizaton メンバーの要件**<br>Organization 内にリポジトリを建てたい場合は Org のメンバーになってもらいリポジトリの管理者になってもらう。

- **Organization メンバーの条件**<br>その場合のリポジトリの運用には 基本 Qithub の運用ポリシー に同意してもらう。Issue は１箇所、Qithub 3大 Moe 要素など。Qiitanista/Qiitadonian であること。

- **Organization メンバーの役割**<br>他のメンバーのフォロー（レビューや issue などにも参加、意見参加）をすること。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue: #14 「機能拡張 なくてもいいけど、あるとよりよい機能は？」
- 関連issue: #123 「コミットメッセージの言語について」

**Comment by hidao80** [comment]
@KEINOS 

リポジトリ追加、次の副作用を懸念しています。

1. Organization にリポジトリを追加する場合、リポジトリ管理者を Organization のメンバに加えなければアクセス権を付与できない
2. 追加したリポジトリのオーナー権限において、Issues や Wiki を乱立されてしまう可能性がある
 
1\. は、Orgのメンバになる前提なら問題はありません。ただし、それ相応の権限が与えられるので、「Org内の Repo をまたいで活動する場合」等のお約束を準備しておく必要があります。  
現在、行動指針はありますが「べからず集」的なものがないので混乱を引き起こす可能性を考慮する必要があると考えます。

2\. は Org の運営方針にひびが入る可能性を内包しており、Issues が複数になる悲劇は繰り返したくないと考えています。

## 代案

1. 可能であれば、兄弟分の別 Org/ 別 Repo として立ち上げていただいた方が良いのではないかと考えます。
2. Org 内に Repo を追加するのであれば、我々のニの轍を踏ませない「バッドプラクティス集」のようなものを準備しておく/準備していくことを提案します。

**Comment by alice1017** [comment]
@KEINOS @hidao80 

１の「Organization にリポジトリを追加する場合、リポジトリ管理者を Organization のメンバに加えなければアクセス権を付与できない」についてですが、Qithub-BOT Organizationのメンバーに参加するためのの要件などは現在あるのでしょうか？

**Qithubサークルに参加するための条件** は[こちら](https://github.com/Qithub-BOT/Qithub-ORG#qithub-%E3%81%A8%E3%81%AF)にありますが、**Qithub-BOT Organizationのメンバーに参加するためのの要件** の記載が見つからなかったので…

そういう要件をwikiなどに記載して頂けると、参加させてもらう側としてありがたいなと思いました。

**Comment by KEINOS** [comment]
@alice1017  @hidao80 

> Qithub-BOT Organizationのメンバーに参加するためのの要件 

メンバー管理が `_(:⁍」 )_` というのが本音ですが、Organization のメンバーはどちらかと言うと鯖管的な感じだったので、[メンバーが気になった人にアプローチする](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E5%8B%A7%E8%AA%98%E6%96%B9%E9%87%9D)以外は特に決めていなかったです。

### 代案 B

リポ管とでもいうのでしょうか。こんな感じにシンプルでどうでしょう？

- Organizaton メンバーの**要件**<br>Organization 内にリポジトリを建てたい場合は Org のメンバーになってもらいリポジトリの管理者になってもらう。

- Organization メンバーの**条件**<br>その場合のリポジトリの運用には 基本 [Qithub の運用ポリシー](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-ORG-%E3%83%AB%E3%83%BC%E3%83%AB) に同意してもらう。Issue は１箇所、[Qithub 3大 Moe 要素](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC%E3%80%81%E3%82%B3%E3%83%B3%E3%82%BB%E3%83%97%E3%83%88)など。Qiitanista/Qiitadonian であること。

- Organization メンバーの**役割**<br>他のメンバーのフォロー（レビューや issue などにも参加、意見参加）をすること。

**Comment by hidao80** [comment]
@KEINOS @alice1017

代案B 👍

私の代案は昼休憩ギリギリの時間だったので安直だった感は否めない…（いいわけ

まさか Org の中に新規リポジトリ作りたいと申し出てくださる剛の者がいるとは思いもよらず、ひるんでました。😓

@KEINOS さんのアイデアである**Qithubメンバー 3 原則**（仮）は非常に秀逸かつ既存のルールに沿ったものなので、私も代案 B を推します。

本issueがcloseした時点で Wiki にドキュメント化します。

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

では**ダイアン B.を起用**ということで Close します。> TL;DR 済

[Wiki の「勧誘方針」](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E5%8B%A7%E8%AA%98%E6%96%B9%E9%87%9D) をリネームしてドキュメント化するのが良いと思います。 @hidao80 > 😎🙏 🙇 

※ 目次作成スクリプトの挙動がおかしかったり、わかりづらいことがあれば issue お願いします。対応いたします。

ORG repo の README.md にある「[Qithubとは](https://github.com/Qithub-BOT/Qithub-ORG#qithub-%E3%81%A8%E3%81%AF)」も修正が必要ですね。これはアチキが変更させていただき 💪

やっぱり新しい人の意見が入ると気づかない目線があって新鮮！ @alice1017 さん、他にも気づいたことがあったら、お手すきにドンドンお願いしますドン。
