### ISSUE TITLE
【相談】コミットメッセージの言語について

### ISSUE THREAD

**Issue by alice1017** [Qithub-BOT/Qithub-ORG#123]
## 相談

Qithub-BOT内にあるリポジトリの**コミットメッセージの言語**を**日本語 or 英語に統一**した方が良いのではないでしょうか。

## 現状

現状では[Qithub-BOT/Qithub-ORG](https://github.com/Qithub-BOT/Qithub-ORG/commits/master)でも、[Qithub-BOT/Qithub-DEV](https://github.com/Qithub-BOT/Qithub-DEV/commits/master)でも、コミットメッセージに英語と日本語が混じっています。今後新規にQithub-BOTに参加したい方々がContributeする際に迷うと思います。

## 自分の案

 - 自分は**日本語に統一**してもいいかなと思います。
 
 ### 日本語に統一するメリット
 
 - 英語に不慣れな初心者でも安心して参加できる
 - 脳直で書ける（推敲は必要ですが。）
 - 多少複雑な表現でも理解できる。
 
 ### デメリット
 
 - 英語圏の人がContributeできない
 - （英語圏の人が参加する可能性は限りなく低いとは思いますが、一応Qiitaを英語で投稿してる人もいますので…）

## 補足

コミットメッセージの頭につける、`fix` や `docs` などは英語のままでいいと思います。

## TL;DR（進捗・結論 2018/09/07 現在）

-  以下のコメント内容を元に、 @hidao80 が wiki に記事を書く。書き終わり次第本 issue を close する。
    - https://github.com/Qithub-BOT/Qithub-ORG/issues/123#issuecomment-419603447
    - https://github.com/Qithub-BOT/Qithub-ORG/issues/123#issuecomment-419605047

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
コミット言語の統一に 👍 ただしリポジトリごとに決めるに 👍 

---

正直、気分で書いてました 😅 このサークルも、もともと OSS にコントリビュートする練習台として始めたところがあるので、「英語のコミットの練習をしなければ」という気持ちと、`_(:⁍」 )_` になった時とで明確な使い分けをしてなかったです。

ただ本当に英語の勉強というなら、[Gitbucket のリポジトリ](https://github.com/gitbucket/gitbucket)くらい徹底的にやらないといけないのかもしれませんね。（無理

Organization のリポジトリ全体で縛るのではなく、リポジトリごとに決める方向でどうでしょう？

その場合、現在あるリポジトリに関しては日本語のコミットで統一でいいのではないか、と。 😄

**Comment by hidao80** [comment]
私も

> コミット言語の統一に 👍 ただしリポジトリごとに決めるに 👍

です。

***

私も「短文なら英語脳になる練習するチャンス！」とばかりに深く考えずなんちゃって英語でコミットメッセージ垂れ流すことがありました…

今後、**メンバーが増えていくことを考慮すると、日本語でコミットメッセージを書くことを徹底してた方が良い**と考えます。

一方、リポジトリごとの個性や方針を尊重するという意味合いで**使用言語決定の裁量は各リポジトリオーナーに帰属させた方が良いのではないか**とも考えます。

むしろ「やっべ、こんなに Cool な Organization に参加するなら、日本語勉強しなきゃだな！」と思わせたいですね 😎

**Comment by hidao80** [comment]
ところで、

- Org のポリシー
     - Qithub 3原則（仮）など
- リポジトリのポリシー
     - コミットメッセージ言語制約 など

をそれぞれ明示する必要性を感じ始めました。

しかもそれらは**各リポジトリ内に明記しないと気付いてもらえないのでは？** と考えます。

## 案B

1. Org 内リポジトリには、
README.md 内にリポジトリポリシーの節を必須としてはどうか
2. ポリシーの種類にコードネームをつけて、Qithub-ORG リポジトリの Wiki にポリシーコード内容詳細ページをリンク等で参照してもらうのはどうか

2\. はクリエイティブ・コモンズのイメージです。

### 例

こんなの。

[![Policy](http://img.shields.io/badge/policy-Qithub%203原則-blue.svg?style=flat)](#url) [![locale](http://img.shields.io/badge/locale-ja%5FJP-blue.svg?style=flat)](#url)

参考: https://qiita.com/dtan4/items/13b0ea9edf5b99926446

**Comment by KEINOS** [comment]
> 1. Org 内リポジトリには、
> README.md 内にリポジトリポリシーの節を必須としてはどうか

👍 

> 2. ポリシーの種類にコードネームをつけて、Qithub-ORG リポジトリの Wiki にポリシーコード内容詳細ページをリンク等で参照してもらうのはどうか

別途制定しておいて、リンク参照に 👍 
変更の度に README.md を書き換えるの`_(:⁍」 )_` ですものね。

```
「このリポジトリは次の Qithub ポリシーに準規します： [POL-001-JA](/path/to/POL-JA)」
```
```
「This repository complies with the following Qithub standards: [POL-001-EN](/path/to/POL-EN)」
```

制定ポリシーの設置先とリンク先は Wiki のルール下はどうでしょう？
[Qithub ORG のルール](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-ORG-%E3%83%AB%E3%83%BC%E3%83%AB) @ Wiki

**Comment by hidao80** [comment]
コメント編集中に先を越されてしまった…

先の私のコメントに**バッジを付ける案と例**を追記しましたので、ご高覧ください。

**Comment by hidao80** [comment]
@KEINOS

Qithub-ORG のルールページ、**開発ルールと運営ルールが混在していて冗長である**と感じました。ってか項目多すぎ！

### 案B 補足1
Qithub 3 原則（仮）と Wiki の「ポリシー、コンセプト」ページの内容の転記だけページを別途作成した方が KISS じゃないでしょうか。

**Comment by KEINOS** [comment]
@hidao80 

> **開発ルールと運営ルールが混在していて冗長である**と感じました。ってか項目多すぎ！

BOT のルールは[ Qithub コマンドWiki](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89-Wiki) などに引っ越すべきですね。

> ポリシーの種類にコードネームをつけて

とあったので、運営ルールを取りまとめたページを作成して名前を付けるのかと思っていました。

[![Policy](https://img.shields.io/badge/Policy-POL--001--EN-green.svg)](#url) (https://img.shields.io/)

個別のバッジを組み合わせるのとどちらが良いですかね。 > @hidao80 @alice1017 
個別は自由な反面、組み合わせを把握するのも大変なような。

**Comment by alice1017** [comment]
@hidao80 
バッジ案とてもいいと思います！ 👍 
locale: ja_JPがあると英語圏の人もわかりやすいですね。
クリエイティブ・コモンズのライセンスもバッジで明記できるといいと思いました 😄

**Comment by KEINOS** [comment]
> locale: ja_JPがあると英語圏の人もわかりやすいですね。

あー、なるほど。となると個別バッジの組み合わせの方が良さげですな。

バッジの各種制定は別 issue にするとして、コミットメッセージの言語に関するバッジはもう少し具体的な方が良いと思います。「Locale」だけだとドキュメント類もその locale と同じと思われるからです。

[![Policy](https://img.shields.io/badge/Commit%20Locale-en--JA-green.svg)](#url)

**Comment by KEINOS** [comment]
en-JA 🤔

**Comment by hidao80** [comment]
なるほど、バッジの記述ルールは別 issue で議論しましょう。

では、結論を確認します。

## 案C

1. 言語の指定はリポジトリ単位で、オーナー権限で指定できる
2. コミットメッセージ言語はバッジで表記する
3. コミットメッセージ言語とリポジトリ内のドキュメント等に記述される言語は独立して指定できる
4. バッジは複数併記できる

で 👌❓ > @KEINOS  @alice1017

**Comment by alice1017** [comment]
@hidao80 

>3.コミットメッセージ言語とリポジトリ内のドキュメント等に記述される言語は独立して指定できる

もう一つ、**コード内のコメント**をする**言語**もリポジトリで指定したほうがいいと思います。
これも決めないと日本語と英語が混在しそうですし。

あとは 👍 👍 👍

**Comment by hidao80** [comment]
なるほど、たしかにコード内コメントも統一した方が好ましいですね。

## 案D

1. 言語の指定はリポジトリ単位で、オーナー権限で指定できる
2. コミットメッセージ言語はバッジで表記する
3. コミットメッセージ言語とリポジトリ内のドキュメント等に記述される言語は独立して指定できる
4. バッジは複数併記できる
5. コード内のコメントをする言語もリポジトリで指定できる

でファイナル・アンサー？ > @KEINOS @alice1017 

合意が取れたら close しましょう。

**Comment by KEINOS** [comment]
@alice1017 @hidao80 

コード内コメントの統一も 👍 

こんな感じ？

1. 言語の指定はリポジトリ単位で、オーナー権限で指定できる
1. 言語はバッジで表記する（複数併記可。下記参照）
1. 以下の記述言語は個別に指定できる
    - コミットメッセージの言語（`LOCALE:Commit` or `LANG:Commit`）
    - コード内コメントの言語（`LOCALE:Comment` or `LANG:Comment`）
    - その他ドキュメント類の言語（`LOCALE:Doc` or `LANG:Doc`）

**Comment by hidao80** [comment]
`locale`だと「居所的・日付表記フォーマット的」な意味合いが付与されるイメージなので、`lang`の方が適切かと思われますがいかがでしょうか？

**Comment by alice1017** [comment]
@KEINOS @hidao80 
自分も `lang` でいいと思います 👍

**Comment by hidao80** [comment]
`ja_JP`と表記すると言語パターンであることがプログラマ界隈では自明なので、

[![commit lang](http://img.shields.io/badge/commit--msg-ja_JP-green.svg?style=flat)](#)
[![documents lang](http://img.shields.io/badge/docs-ja_JP-green.svg?style=flat)](#)

とかでも良さげですが、どんなもんでしょう？

余計Localeっぽいですかね…

**Comment by KEINOS** [comment]
１つにしちゃうとか。

[![Lang](https://img.shields.io/badge/In%20Ja--JP-Docs%20%7C%20Commit%20Msg%20%7C%20Comment%20Msg-brightgreen.svg?style=flat)](#)

**Comment by alice1017** [comment]
@hidao80 

Localeっぽさをなくすなら、いっそ `ja` だけでもいいのでは？
![a](https://img.shields.io/badge/commit_msg-ja-brightgreen.svg)

**Comment by hidao80** [comment]
@KEINOS 

一つにまとめるのはやだなぁw 部品としての再利用性が下がると考えます。

@alice1017 

`ja`だけって言うのは良いですね！ その発想はなかった。😅

**Comment by KEINOS** [comment]
> 部品としての再利用性が下がると考えます。 @hidao80 

確かに。ただバッジが多すぎても目に入らないのかなぁ、と。まぁ、バッジのバーゲンセール状態になったら、別途話し合いましょう。

> いっそ ja だけでもいいのでは？ @alice1017 

なーるーほーどー。シンプルで良い。 👍 

すごいレベルを求めるコミットメッセージの場合だとこんな感じ？

![JS](https://img.shields.io/badge/commit%20msg-js-brightgreen.svg)

**Comment by hidao80** [comment]
コミットメッセージをプログラム言語で書く狂気w

**Comment by hidao80** [comment]
@KEINOS さんの

https://github.com/Qithub-BOT/Qithub-ORG/issues/123#issuecomment-419603447

の案に、 @alice1017 さんの

https://github.com/Qithub-BOT/Qithub-ORG/issues/123#issuecomment-419605047

表記法でドキュメントまとめます。

記事が出来次第、close します。

**Comment by alice1017** [comment]
@hidao80 

よろしくおねがいします！:pray:

**Comment by KEINOS** [comment]
>> 開発ルールと運営ルールが混在していて冗長であると感じました。ってか項目多すぎ！ @hidao80 
> 
> BOT のルールは Qithub コマンドWiki などに引っ越すべきですね。

BOT の開発ルールの引っ越し用にブランチ切りました。→[KEINOS-Wiki-ToC-Generator-As-OneFile-20180908](https://github.com/Qithub-BOT/Qithub-ORG/tree/KEINOS-Wiki-ToC-Generator-As-OneFile-20180908)

俺様のブランチ状態ですが、何かあれば遠慮なく横からコミットしてください。

**Comment by hidao80** [comment]
@KEINOS 

merge しました。

**Comment by KEINOS** [comment]
> BOT の開発ルールの引っ越し用にブランチ切りました。→KEINOS-Wiki-ToC-Generator-As-OneFile-20180908 @KEINOS

どうやら、Wiki の方のリポジトリにブランチを切らないと行けなかったのに、この（Qithub-BOT/Qithub-ORG）のリポジトリで切ってしまっていました。（意味ナッシング！）

> merge しました。 @hidao80 

どのリポジトリにマージされました？`KEINOS-Wiki-ToC-Generator-As-OneFile-20180908` だと消しちゃったかもしんない、、、すみません、、、

**Comment by hidao80** [comment]
その時、一つだけあったブランチなので、`KEINOS-Wiki-ToC-Generator-As-OneFile-20180908`だと思われます。

**Comment by KEINOS** [comment]
> その時、一つだけあったブランチ @hidao80 

あいや。たぶん消しちゃったかも、、、ブランチがそちらに残っていたら Push していただけますか？
こちらで統合いたします。 🙇

**Comment by KEINOS** [comment]
@hidao80 @alice1017

https://github.com/Qithub-BOT/Qithub-ORG/issues/135#issuecomment-424367932 にもカキコしましたが Wiki に「[各リポジトリの README.md に使うバッジ](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E5%90%84%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE-README.md-%E3%81%AB%E4%BD%BF%E3%81%86%E3%83%90%E3%83%83%E3%82%B8)」を記載しました。

本リポジトリの README.md にコミット言語のバッジを適用したらこのIssue も Close しましょう！
