### ISSUE TITLE
【提案・報告】Qithub-BOTヘッダー画像を作ってみた

### ISSUE THREAD

**Issue by alice1017** [Qithub-BOT/Qithub-ORG#124]
## 提案・報告

最近のGithubでは、プロジェクトに関連するヘッダー画像をREADMEのトップにつけるリポジトリを多く見受けられます。（ref: [pytheory](https://github.com/kennethreitz/pytheory) , [mas](https://github.com/mas-cli/mas) , [browsh](https://github.com/browsh-org/browsh) , ...etc)

ということで、このQithub-BOT Organizationのリポジトリにもヘッダー画像をつけてみてはどうでしょうか。

## 自分の案

私が作ってみたのがこちら

![qithub-bot](https://user-images.githubusercontent.com/465679/45249003-9cda2680-b353-11e8-8e9f-215151fb854b.jpg)

 - 画像内の文字がQithub-BOTになっているのは、サンプルのためです。
 - リポジトリによって画像内の文字を変えてもいいと思います。
 - 背景色はQiitaのヘッダーと同じ色です。
 - Qiita-BOTの下に簡単な説明文を日本語でつけてもいいかもしれません。
 - Qiitanの画像はQiitadonの左下にいるやつに彩度をあげたものです

## TL;DR（進捗・結論 2018/09/08 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
ヘッダー画像追加は賛成です。

で、追加案と懸念を少し。

## 追加案

説明文は画像に**埋め込まない**方が良いと考えます。ググラビリティが高まるためです。

## 懸念

既存画像の転用は著作権的・ライセンス的にセーフでしょうか？

若干の加工はしていますが、権利者(インクリメント社様)になんか言われた時が厄介そうです。
およそ何も言われないと思われますし、 @KEINOS さんが書かれたものは2次創作に近いのでまだ大丈夫かな？ と考えていますが、本 issue の図案は権利的安全性が厳しいと考えます。

Qiitan が CC BY-SA 4.0 とかなら無問題なんですが。

**Comment by alice1017** [comment]
権利関係を全く考えていなかったので今すごく反省しております。

**Comment by KEINOS** [comment]
ヘッダー画像いいですね！歓待感が増すと思います。 👍 

@hidao80 さんが指摘したように、まんまキータンを使うとオフィシャルと誤解が出てきそうです。
以下のロゴを使ってみてどうでしょう。
https://github.com/Qithub-BOT/Qithub-ORG/tree/master/images/Icon_Qithub

**Comment by alice1017** [comment]
現在第二弾を製作中です
![_2018_09_08_11_54](https://user-images.githubusercontent.com/465679/45249599-f3e4f900-b35d-11e8-8030-ed94db465046.jpg)

**Comment by KEINOS** [comment]
おぉ。いいっすねー！ 👍 

気になるのが Qithub-ORG がいいのか、Qithub-BOT がいいのか。

本当は Organization 名を Qithub-ORG にして、このリポジトリを Qithub-BOT にスイッチするのがわかりやすいのですが、、、

[空いていれば変更は可能](https://help.github.com/articles/renaming-an-organization/)らしいのですが、既存のリンクが、、、
（空いてはいるみたい → https://github.com/Qithub-ORG 、Qithub は NG → `https://github.com/Qithub`）

**Comment by alice1017** [comment]
良いデザインが思い浮かばなかったので、大胆に構造を変えてみました

![qithub-bot_v2](https://user-images.githubusercontent.com/465679/45249756-b897f980-b360-11e8-8815-c56fa561c60e.jpg)

**Comment by KEINOS** [comment]
大胆だwww なんかクラタスと勝負できそうw

バナーサイズを先に決めておいて、定期的に変更して良いんじゃないかしら。

設置先用意しました。→ https://github.com/Qithub-BOT/Qithub-ORG/tree/master/images/Banner_Qithub

**Comment by hidao80** [comment]
@alice1017 👍

リポジトリの README.md に画像は貼れますが、Organization のトップ画面に画像って貼れましたっけ… ＞ @KEINOS 

まずは BOT 名義で画像作っていただけてるので、Qithub-BOT リポジトリの README.md に採用してみてはどうでしょう。

**Comment by KEINOS** [comment]
@hidao80 

> Qithub-BOT リポジトリの README.md

Qithub-ORG リポジトリの README.md でなくて？

Organization 総合トップのここが良いんジャマイカ↓
https://github.com/Qithub-BOT/Qithub-ORG

**Comment by alice1017** [comment]
@KEINOS 

バナー置き場にバナー画像を置いてPRだしますね 👍

**Comment by hidao80** [comment]
@KEINOS 
ああ、そうか！ Qithub-ORG の README.md が適切ですね。

いや、勘違い。

**Comment by KEINOS** [comment]
> バナー置き場にバナー画像を置いてPRだしますね 👍 @alice1017 

よろぴくー！ 設置のルールはないですが、同階層の他のディレクトリを参考によろぴくです。
何かあれば PR のレビュー時に明確にしていきましょー

> いや、勘違い。 @hidao80 

間違えやすくなってきましたよね。これも歴史かw

どうします？ Organization 名を Qithub-ORG にして、リポジトリ名を Qithub-BOT にします？

**Comment by alice1017** [comment]
@hidao80 @KEINOS 
READMEにバナー貼った状態でPR出してもいいですか？

**Comment by hidao80** [comment]
@alice1017 
はい。PR お願いします！

**Comment by hidao80** [comment]
#125 がmerge されましたので close しまーす。
