### ISSUE TITLE
【提案】サークルメンバーをREADMEに記述するのはどうでしょう？

### ISSUE THREAD

**Issue by alice1017** [Qithub-BOT/Qithub-ORG#127]
## 提案

Qithub-BOT Organizationのメンバー（メンテナ）はOrganizationのPeopleを見ればわかりますが、メンテナではないQithubサークル**メンバーの一覧**がないなと思いました。

## 自分の案

- 案①：**READMEの最後**にメンバーを書く
- 案②：Qithub-ORGのリポジトリに**MEMBERS.md** というファイルを作り、そこに書く

## TL;DR（進捗・結論 2018/09/09 現在）

- 案②の `MEMBERS.md` を使用する。
- `MEMBERS.md` に名前とプロフィールを書き、Qithub-ORGリポジトリに**ＰＲ**し、それが**マージされたらメンバーになる。**
- つまり、 `MEMBERS.md` に書かれている人たちがQithubサークルのメンバーとなる。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
@alice1017 

## TL;DR

コントリビューターが増えて来たら[サークル・メンバーのリンク](https://github.com/Qithub-BOT/Qithub-ORG/graphs/contributors)をコントリビューターに貼るでどうでしょう？

## TS;DR

> メンテナではないQithubサークル**メンバーの一覧**がない

わかります。ただ**正直な話しをすると僕らだけ**だったりします。😳

たまーに[本家（Increments）の方が、BOT 制御のために PR してくださったり](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-API-Issue-93)する感じで、、、

[１年まったり](https://github.com/Qithub-BOT/Qithub-ORG/issues/1)とやっていて、やっと @alice1017 さんが来てくれたというのが現状です。
（なので内部では　ｷﾀ━━━ヽ(∀ﾟ )人(ﾟ∀ﾟ)人( ﾟ∀)人(∀ﾟ )人(ﾟ∀ﾟ)人( ﾟ∀)ノ━━━!!!　となっています）

Qithub BOT も半年前に見直しをするために振り出しに戻ったので、QiiTime が最近の成果となります。ただ、やはり今回の QiiTime のように BOT が動けば人も動いてくれるんだなぁと実感しています。

Qithub BOT はCLI で動くプログラムを、プラグイン的なイメージでコマンドとして稼働させることで**プログラム言語を問わずにコラボできる**という野望がありますし、QiiTime のように cron で叩いて動かすような単体 BOT もどんどん作っていければと思います。

これが実現できたらコントリビューターも増える気がするのです。 @alice1017 さんが来てモチベもあがったので、これからだと思います！

色んな BOT 作って行きましょう。もう [BOTch ボッチじゃない](https://github.com/Qithub-BOT/Qithub-ORG/issues/9)し！

**Comment by hidao80** [comment]
対案を提示にするにあたり、Organization 参加者をステータスによって呼び分けたいので、ここで使う用語を仮に宣言します。正式な用語ではないので悪しからず。
Wiki にある定義と相違があったらゴメンナサイ。

# TL;DR

## 本コメント内の用語の定義

- メンテナ：Organization の People に登録されているメンバ。Organization 運営の義務と、案件の決裁権を持つ。
- コントリビュータ：People には登録されていないが、**コミットおよび PR を行った履歴がある**メンバ（＝Contributors ページに表示されている）。  
  運営の義務と決裁権はないが、issue・PR・レビューによる提案とコメントに対するリアクションができる。
- コラボレータ：People に登録されておらず、コミット・PR 履歴がないメンバ。  
  運営の義務と決裁権はないが、issue・PR・レビューによる提案とコメントに対するリアクションができる。
- サークルのメンバ：メンテナ、コントリビュータ、コラボレータの総称。

## 懸案

1. 「サークルのメンバにはなりたいが、匿名希望」のコラボレータがいるのではないか（リアクション等からバレますが）。
2. メンテナとコントリビュータは repo 内のどこかしらのページに自動的に表示されるので、**メンテが追いつかない members.md を作るリスクを下げる必要はない**のではないか

- 注：「リスク」とは「不確実性」というのが本来の意味なので、「リスクを下げる＝確実性が高まる」とご理解ください。

## 対案A

Qithub-ORG repo のルートに「members_profile」ディレクトリを切り、その中に**サークルのメンバーであることを公開したいメンバのみ、**`{GitHubアカウント名}.{拡張子}` **ファイルを設置する**という方法でメンバーリストおよび各メンバのプロフィールを公開してはどうか。

## 対案A の TL;DR

members_profile ディレクトリ内ファイル名リストを見れば、公開了承メンバのアカウント名一覧ページになります。また、各メンバのプロフィールファイルの内容を見れば自己紹介や実績、当人が抱えている repo や blog へのリンク、SNS アカウントや所属団体などがわかるようになっていれば良いと考えます。

### プロフィールファイル仕様のキモ

プロフィールファイルは原則フォーマット自由とし、md に限らず html や PDF、PNG、mp4、mp3 などを使っても良いことにすると面白いかもしれません。もちろん、ファイル名のみで内容が白紙でも OK とします。

**Comment by KEINOS** [comment]
> 懸案
> 1.「サークルのメンバにはなりたいが、匿名希望」のコラボレータがいるのではないか @hidao80 

Qithub は Qiita/Qiitadon のユーザー限定のサークルであるため、匿名希望は難しいと思います。

Qithub は OSS であるため Fork されることを考えてペンティングになっていた（忘れていた） Issue #93 の[OAuth による認証](https://github.com/Qithub-BOT/Qithub-ORG/issues/93)を再検討してもいいかもしれません。それを踏まえての対案。

## 対案A'

1. 対案 A の 「members_profile」ディレクトリ＋プロフィール・ファイルの設置から始める。
2. OAuth を実装する。
3. 「Qiita」「Qiitadon」のOAuth ボタン or リンク を README に設置し、ポチッと押したらサークルのメンバーに追加されるようにする。（OAuth の公開情報が 「members_profile」にプロフィールとして保存される）
4. サークルのメンバーになると「GitHub」ボタンが現れ OAuth を行うと「メンテナ」もしくは「コラボレーター」のメンバーになれる。

## OAuth したい理由

１番の理由は鯖管のわがままなのですが、なるべく **Qiita/Qiitadon ユーザーのみにアクセスを制限したい**のです。

というのも、トゥート経由でリポジトリを知ったと思われる誰か（BOTかも）が、[サーバーのバージョン情報ページ](https://qithub.tk/tools/version/) を見てイタズラをしているらしく、このページはリアルタイムで情報を取得し表示させていたため、何度かサーバーやバックアップ用の自宅の WebDAV サーバーがハングしました。（空き容量の情報確認のリクエスト過多）

現在は、リアルタイムで表示させずにキャッシュ表示させて安定して動いています。

そのため、OAuth で Qiita/Qiitadon のユーザーだけに限定させたいのですが、今回の件で「あ、OAuth させたらサークルのメンバーでいいじゃん 😎」と思った次第です。

ただ、例のごとく OAuth の実装にも時間がかかりそうなので対案 A からスタートがいいのかな、と。

**Comment by hidao80** [comment]
うーん、対案A の表現が誤解を生んでいる気がする。
ので、補足します。

1. 対案Aにおける「コラボレータ」とは、**ざっくり言うとソースを触らずに、アイデア出し and/or リアクションだけする人**を指します。
2. プロフィールファイルは「実行されるサーバ上のみで保管される、API 実行権限を与えられた人を表すもの」**ではなく**、あくまで**Github 上で全世界に公開される Org 参加者名簿でしかない**前提で考慮されている
3. プロフィールファイルは、**リポジトリに登録される公開情報**かつ **「Org 参加者名簿でしかない」前提で設計されている**ため、**BOT 等の成果物に対する権限管理に流用するべきではない**と考えています。実行権限管理をするなら**リポジトリ内ではなく、実稼働サーバ内にのみ存在するアカウント管理用のファイル or DB を用意するのが筋**だと考えます。

対案Aでは「issue/PR レビューにチャチャを入れたい」「コードは書かない/書けない」「👍だけしたい」という参加者を「コラボレータ」と定義しており、その人たちには**名簿にサイン（＝プロフィールファイルを公表）しなくても Org に干渉できる**自由（対案Aでいう「匿名希望」）を残しておきたいと考えています。

もちろん、Github にリアクションする時点で**完全な匿名は担保されません**が、**リアクション一つするのにリポジトリにユーザ登録を要求して、かつ PR or OAuth を必要とするのはやりすぎではないか**と考えています。

- - - 

対案Aにおいては、「メンテナ」「コラボレーター」は**Github (=Qithub-BOT Org) に対する関わり方を表す概念**と位置付けており、**Qithub-BOT の成果物が動作する環境に関わる権限を表す概念ではありません**。
ですので、「Org の開発 or 運営への参加者」と「Org の成果物の利用者」は大変近い関係ですが、**重複する部分があるが、別のグループである**と認識しています。
そのため、「Org の開発 or 運営への参加者」と「Org の成果物の利用者」を**イコールにしないことができる余地**を残しておきたいと言う考え方です。

**これはサークル運営の方針に関わってくる重要な事案だと認識している**ので、納得いただけるまで説明したいと思います。
不明点や違和感があれば、ご意見をいただきたいです。

P.S.
絵文字を入れるタイミングがなくて、めちゃめちゃカタい文章になってしまいました。楽しい文面にしたいのですが、難しいですなぁ。😓

**Comment by KEINOS** [comment]
> これはサークル運営の方針に関わってくる重要な事案だと認識しているので、納得いただけるまで説明したいと思います。

👍 

この **issue のメインテーマは「サークルのメンバーの明示化」という点**です。（まぁ３人しかいないのに何を熱くと思われるかもしれませんが 😆こういうディスカッションも GitHub ならでわということで）

今回の @alice1017 さんの issue でハッとしたのが、issue #93 の元になった『Organization （運営）メンバーが非表示なので、**誰が運営しているかわからないから反応がない**のでは』という過去の悩みと似ていることです。

つまり、本 issue により『サークル（参加）メンバーが表示されていないので、**誰が参加しているかわからないから反応がない**のでは』という、似てはいるものの次のステップに来たという、サークルだけにクルクルまわっているのではなく、スパイラル・アップしているんだなという、気づきをもらえたと感じています。

その上で、同じ方法論で「コントリビューターをサークル・メンバーにすればいい」という安易な発想をしてしまいました。

これでは、ちょっと issue に意見したり 👍 しただけで組織の一員や関係者にされてしまうって、「どこの宗教団体 or ヤクザ団体かよ！」状態ですよね。

> 「Org の開発 or 運営への参加者」と「Org の成果物の利用者」を**イコールにしないことができる余地**を残しておきたいと言う考え方です。

この意見にも同意します。これを参加までの流れにすると、おそらく以下が現在の参加までのフローだと思います。

`① Org の成果物の利用者` → `② Org の開発参加者` → `③ Org の開発者` → `④ Org の運営`

つまり、上記のどの段階から「サークルのメンバーとみなすか」がポイントになると思います。

より深く各役割について話す前に、**「サークルのメンバーは誰か」「誰はサークルのメンバーでないか」を定義する必要はありませんか**ね？

現在のままだと、宗教やヤクザでないにしても、某「なんとかティー」や某「フリーなんちゃら」といった会員数不明の秘密結社みたいな状態ですし。（むしろ鷹の爪団？）

**Comment by alice1017** [comment]
すいません編集中間違ってコメント投稿してしまいました 💦

**Comment by KEINOS** [comment]
南斗ヒエー拳！Σ(￣◇￣ﾉ)ﾉ

、、、って、どのコメント？！

**Comment by alice1017** [comment]
# 意見のまとめ

わかりにくくなってきたのでなってきたのでまとめます。

## 前提

- `members_profile` ディレクトリに**プロフィールファイル**を置く形でサークルメンバーの明示化をする

## @KEINOS さんの意見

- Qithubサークルメンバーは**Qiita/Qiitadon ユーザーのみにアクセスを制限したい**
- そのため、Qiita/QiitadonユーザーがOAuthすることでメンバーに参加できるようにしたい

## @hidao80 さんの意見

- プロフィールファイルは**Github 上で全世界に公開される Org 参加者名簿でしかない**
- BOT 等の成果物に対する権限管理に流用するべきではない
- プロフィールファイルを公表しなくても **Org に干渉できる自由**（対案Aでいう「匿名希望」）を残しておきたい
- リアクション一つするのにリポジトリにユーザ登録を要求して、かつ PR or OAuth を必要とするのはやりすぎでは。

## そして私の意見

- 私もOAuthはしなくてもいいのではと思います。
- Qithubサークルの良い所は **なにかやりたい！という気持ちに寄り添っている** ところだと私は思います。
- このサークルやリポジトリに参加したいと思った人が、自発的にプロフィールファイルをPRしてマージするほうがいいかなと思いました。

**Comment by hidao80** [comment]
> より深く各役割について話す前に、「サークルのメンバーは誰か」「誰はサークルのメンバーでないか」を定義する必要はありませんかね？

👍

その通りですね！ どうしましょう、「サークルのメンバーの要件定義」は本 issue の趣旨と乖離するような気がするので、別 issue にした方がいいでしょうか？

**Comment by hidao80** [comment]
@alice1017 さん、議論のまとめ、ありがとうございます！
とても見通しが良くなりました。

> このサークルやリポジトリに参加したいと思った人が、自発的にプロフィールファイルをPRしてマージするほうがいい

この考え方に賛成です。

## 案B

「自発的にプロフィールを PR する」となると、**個人ごとにファイルを作らなくても、単一の md ファイルで十分なのではないか**と思うようになりました。
参加表明したい方が自ら名簿ファイルの編集を行うことになり、名簿ファイルのメンテナが不要になるためです。これなら当初の懸念事項であった「名簿管理担当者による記載漏れ」は原理的に起こりえないのではないか、と考えています。

また、**サークルのメンバーリストに名前を乗せる前に、お試しで気軽に活動に参加したい**需要にも対応できると考えます。

- - -

結局 @alice1017 さんの原案に立ち戻る形ですが、考察・配慮が深まったように感じています。
ご意見お待ちしています。

**Comment by KEINOS** [comment]
> わかりにくくなってきたのでなってきたのでまとめます。 @alice1017 

とりまとめありがとうございます！

１点だけ訂正したいのが OAuth により「リアクション一つするのにリポジトリにユーザ登録を要求して、かつ PR or OAuth を必要とする」意図はないことです。あくまでもサークルの参加表明として OAuth 認証を利用するというものです。

ただ、いずれにしても **OAuth はいま手がでないので現状却下**で。

どこにプロフを置くか、どう置くかに絞っていいと思います。

> 本 issue の趣旨と乖離するような気がするので、別 issue にした方がいいでしょうか？ @hidao80 

サークルメンバーの定義からの、どこにどのようにプロフを設置するかだと思うので、この issue でいいのではないでしょうか。

> このサークルやリポジトリに参加したいと思った人が、自発的にプロフィールファイルをPRしてマージするほうがいいかなと思いました。 @alice1017 

👍 案B にも 👍 

「はじめての GitHub @ Qithub」的なノリで「`MEMBERS.md` にプロフを書いて PR しよう」というのは良いですね！サークルメンバーの意志表明、コラボの最初のステップ、管理含め一石三鳥だと思います。

ってか、**サークルのメンバーの定義も「`MEMBERS.md` にプロフを書いた人」で OK** ってことに！KISS 💋

**Comment by hidao80** [comment]
> サークルのメンバーの定義も「MEMBERS.md にプロフを書いた人」で OK ってことに！KISS 💋

👍

自由意志かつ分かりやすい！ そして最大のメリットは**初 PR を `MEMBERS.md` に投げられる**ことで、**初 Merge 体験のハードルを大幅に下げることができる**ことにあると感じています。

これ、結構デカイと思います。😊
いいんじゃないでしょうか。

一周回って、 @alice1017 さんの案まんまですねw

P.S.追記
初 PR、すごい勇気が要ったような気がするけど、あまり覚えていない…

**Comment by alice1017** [comment]
@hidao80 @KEINOS 

では、`MEMBERS.md` の中身はどうしましょう？
とりあえず自分で考えたのは次のような感じです。

ヘッダー
```markdown
# このファイルについて

このMEMBERS.mdにはQithubサークルのメンバーが記載されています。
新たにメンバーになりたい人は、このファイルに自身のプロフィールを記述しPR（プルリクエスト）することで参加することができます。
Qithubの参加条件はREADME.mdを参照してください。
```

メンバーの書式
```markdown
# メンバー

- [@hidao80](https://github.com/hidao80)
- [@KEINOS](https://github.com/KEINOS)
- [@alice1017](https://github.com/alice1017)

# プロフィール

### @hidao80

【QiitaのアカウントURLや参加の意気込み？など書きたいことを書く】

### @KEINOS

【同上】

### @alice1017

【同上】
```

どうでしょうか ❓

**Comment by KEINOS** [comment]
@alice1017 @hidao80 

メンバー書式は LGTM です。ヘッダーを叩いてみました。

```
# このファイルについて

この MEMBERS.md には Qithub サークルのメンバーが記載されています。

このファイルに自身のプロフィールを記述し PR（プルリクエスト）することで Qithub サークルに参加することができます。
サークルから外れたい場合も、同様にプロフィールを削除して PR ください。

なお、サークルの参加条件については [README.md](URL) をご覧ください。
```

どうでしょうか ❓

**Comment by alice1017** [comment]
@KEINOS 

いいと思います 👍 
ただ、以下のようにREADMEに **「Qithubの参加条件」という見出し** をつけて、そのURLに対してリンクを貼れば一番わかりやすいかなと思いました。

```markdown
## Qithub とは

「Qithub」は [Qiita](https://qiita.com/) と [Qiitadon](https://qiitadon.com/) をこよなく愛する同人サークルです。以下の条件に合えば誰でも参加できます。

## Qithubの参加条件

- Qiita もしくは Qiitadon ユーザである。
- Qiita もしくは Qiitadon がもっと楽しくなることがしたい。
（以下略）
```

**Comment by hidao80** [comment]
@alice1017 
メンバー書式 LGTM です。👍

@KEINOS 
ヘッダー書式 LGTM です。👍

サークルへの参加手続きや対象者の詳細について、`README.md`へ追記するなら、「Qithubの参加条件」を新しい見出しとせず、既存の「入部方法」節以下に追記し、`MEMBERS.md`に入部方法節へのURLへリンクするほうが良い気がします。

**条件**っていう単語は適切ではあるのですが、割と当たりがキツく、排他的な印象があります…😓

**Comment by alice1017** [comment]
@hidao80 @KEINOS 

READMEの新・入部方法節案です

```markdown
## 入部方法

`MEMBERS.md` にあなたの名前とプロフィールを記入し、このリポジトリへＰＲ（プルリクエスト）して下さい。
PRがマージされたら、**晴れてあなたはQithubサークルのメンバーです。**

ＰＲのやり方など不安なことがあれば [issue](https://github.com/Qithub-BOT/Qithub-ORG/issues) を作成してメンテナに相談してください。

このサークルはそもそも GitHub/Git や OSS コラボの初心者のための練習の場として始まったので、失敗したら[ケセラセラ](https://ja.wiktionary.org/wiki/qu%C3%A9_ser%C3%A1,_ser%C3%A1)です。
```

どうでしょうか
ただの案なのでブラッシュアップしていきましょう 👍

**Comment by KEINOS** [comment]
@alice1017 @hidao80 

Qithub の参加は入部しなくても OK 的な部分もリミックスしてみました。

```
## 入部方法

このリポジトリの `MEMBERS.md` に、あなたのアカウント名とプロフィールを記入し PR（プルリク, Pull Request）してマージされたら**晴れてあなたは Qithub サークルのメンバーです**。（退部手続きも同じです）

しかし Qiita/Qiitadon ユーザであれば**入部しなくても参加は可能**ですので、どんどん issue をあげたりリポジトリを clone して PR （プルリク, Pull Request）してください。

初めての GitHub でのコラボや PR が怖いという方は、まずは `MEMBERS.md` にあなたのアカウント名とプロフィールを記入するところから始めてみてはいかがでしょう。

このサークルはそもそも GitHub/Git や OSS コラボの初心者の練習の場として始まったので、失敗したら[ケセラセラ](https://ja.wiktionary.org/wiki/qu%C3%A9_ser%C3%A1,_ser%C3%A1)です。

PR の仕方やルールなど、何か不安がある場合は遠慮なく下記の部室や溜まり場で聞いてください。Qiitadon でサークル・メンバーやメンテナにメンション or DM していただいても OK です。

なお、メンテナも随時募集中！下記「メンテナについて」をご覧ください。
```

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

変更の更新を PR #131 であげました。誤字脱字修正があれば PR に差し込んでくださーい！

MEMBERS.md も追加したのですが、この PR に追記していきますか？それとも一旦マージして、各々別途 PR します？

**Comment by hidao80** [comment]
@KEINOS

`README.md`と`MEMBERS.md`が揃ってないと機能単位の PR にならないと考えますので、両方突っ込んだ状態でコミットするのが良いと考えます。

あとは👌😎🙏

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

なんか `rebase` にチャレンジして失敗して無意味なコミットが増えてしまいましたが、とりいそぎ `MEMBERS.md` 追加できました。

- [README.md](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/README.md) @ master
- [MEMBERS.md](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/MEMBERS.md) @ master

各々、**おてすき**にプロフィールを追記したら PR お願いします。

３人のプロフィールがそろったところで Close いたします。

**Comment by KEINOS** [comment]
PR #140 で３人のプロフィールが揃ったので Close し 💪 

🎉
