### ISSUE TITLE
【報告】アクセス・トークンが外部コマンドから取得できるようにしました

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#128]
## 報告

BOT やプログラムが Qiita/Qiitadon API を叩くのに必要なアクセス・トークンをシェル経由で取得する `gettoken` コマンドをサーバー側に用意しました。

これにより単体 BOT やプログラムは**外部コマンド（シェル）経由で必要なアクセス・トークンを取得できます**。（ [Qithub コマンド](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Qithub-%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E9%96%8B%E7%99%BA-Wiki--%5BTOP%5D)は、このコマンドは利用不可です）

詳細を Wiki にアップしました。
- [アクセストークンについて](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6) @ Wiki

## 理由

QiiTime もそうですが、ソースコード上にアクセス・トークンをハードコーディングできない（すべきではない）ため、別途登録（入力＆保存）処理の実装が必要となります。

以下の理由から最新のアクセス・トークンを提供するために設置しました。

1. 毎回実装するのが面倒
2. 保存ミスでトークンが外部に見えてしまう可能性の懸念
3. アクセス・トークンはリセットされることがあるので変更時の周知が大変

## TL;DR（結論 2018/09/16 現在）

- Wiki の仕様書をわかりやすく変更し Close

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
👍

P.S.
改めてアクセス・トークン周りの仕様書を読みましたが、ものすごい複雑かつ一般名詞と同じ Qithub 用語があるので理解が難しかった…
仕様書のブラッシュアップしないと、サードパーティがつらそう…😓

**Comment by KEINOS** [comment]
> ものすごい複雑かつ一般名詞と同じ Qithub 用語があるので理解が難しかった…

先ほど改めて読んで見ました。ほんとそうですね。

しょっぱなから「Qithub コマンドがアクセス・トークンを必要とする場合」って、前提知識の敷居を上げてしまっていますね。😖
ブラッシュアップしましょう。 👍 

次回のブラッシュアップまで、本 issue は open とします。

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

アクセストークンについてブラッシュアップしました。いかがでしょう？わかりやすくなりましたかね？

- 「[アクセストークンについて](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6) 」 @ Wiki

**Comment by KEINOS** [comment]
問題なければ 👍 ２つで Close し 💪

**Comment by hidao80** [comment]
👍

**Comment by alice1017** [comment]
👍

**Comment by KEINOS** [comment]
👍 では Close しまーす
