### ISSUE TITLE
Qiitaコラボ記事「記事原稿第1版が完成しているか」を BOT から判断する方法

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#13]
BOTの基本機能「Qiita記事のコラボ」と「BOT制作のコラボ」のうち、前者の「Qiitaコラボ記事」について考えたいです。

まず、第１版を考えるときの用語の定義が必要と思います。
出版的な定義だと以下のようになります。

**初稿：** 新規Qiitaコラボ記事をリクエストしたユーザAがあげた原稿のこと。
**初校：** 他Qiitadonユーザー（BOTのフォロワー）の１回目のチェックを終えたもの
**初版：** Qiita記事のステータスが限定公開から公開になり、公開トゥートされたもの

上記を前提とすると、BOTの判断は以下でどうでしょう？

**初稿：** ユーザAが上げてきた最初のプルリク
**初校：** ユーザAのプルリクをBOTのフォロワーに通知して、一定数の :thumbsup: を超えたもの（レビューと同等？）
**初版：** レビューをクリアしてマージされたもの

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

### TL;DR (結論 2017/10/18)

1. **新規記事リクエスト**  
フォロワーは、 Qiitaコラボ記事 の「テーマ」（タイトルと概要）とリクエスト・コマンドを記載した、未収載メンショントゥートを BOT に投げる。  

>＠qithub #Qiitaコラボ記事:setTheme
>こんなテーマで記事を作成してみたいです。
> ```
>#はじめてのQiitadon
>「Mastodon に興味はあるが Qiitadon から始めてみるか」と考え
>ているQiitaユーザーに、マストドンの基本や Qiitadon の特徴など
>初めてでも入りやすい情報を提供する。
>```  

2. **新規Qiita記事の作成（Qiita側）と記事IDの取得**  
BOT が Qiita の Qithub アカウントで 1 のテーマの内容を含んだ新規記事を「下書き」で作成し、記事IDを取得する。
3. **新規Qiita記事の作成（GitHub側）と記事IDの通知**  
BOT が 2 と同内容の記事を Github に作成し、記事 ID （＝ Github ファイル名）を 1 にリプライする。（＝フォロワーにもテーマを通知）
4. **PR 競争の開始**  
3 をバージンリモート master として、初稿競作者たちが各々 バージンリモート master のブランチを作成しコミットをはじめる。必要なら Push もする。（牽制）
5. **PR と初稿および出版 ※**  
最初に PR されたものが BOT によりリモート master にマージされ（初稿＝初校＝初版）、 2 の Qiita側の記事を更新し 「公開」で保存する（外部的には第１版の出版）
6. **出版のアナウンス**  
（該当記事の）GitHub側のブランチは削除され、原稿が公開された旨を 1 にリプライする（外部アナウンスは定時処理の新着Qiita記事トゥートで行う）
7. **master に追随する**  
PR 競争に負けた人は、各々リモートの master を自身のローカルに Pullしブランチのコンフリクトを直す、もしくはブランチを破棄し、新たにブランチを作成する
8. **次版の PR 競争開始**  
各自、自身のブランチにてコミットを行う。必要なら Push もする。（牽制）
9. **前版の校正＆加筆**  
コミットが終わった者から初版ではないが手順として 5 に戻る

**Comment by hidao80** [comment]
マージ担当者が見えないですが、自動マージ（botがやる）のなら、初稿===初版 になりませんか？

それともマージコマンドをもらったとき、:thumbsup: 数がしきい値を超えていたらその時初めて初版、という流れでしょうか？

**Comment by KEINOS** [comment]
（ここではQiitaコラボ記事限定の話をしています）

> マージ担当者が見えない

そうですね。

私のイメージでは「マージ作業そのものはBOT」で「マージの決定権はBOTのフォロワー」にあり、彼らの「 👍  」数（しきい値ごえ）が「**マージをGOのサイン**」です。

そのため「`👍 数がしきい値を超えていたらその時初めて初版`になる」と同等で良いと思います。

ただ、脳内シミレーションすると、Qiitadonユーザーには初回リリースに厳しい人もいると予想されるため、公開前でしょげて（心折れて）しまう気もします。

最初から皆で完璧なものを作って初公開するよりは、「どんどん更新して叩き上げる」方がコラボ間もあるし、GitHubやQiitaのアクティビティにも影響をあたえられると思います。

そこで、

    BOTのフォロワーが上げてきた場合に限り、
    「プルリク→マージ→Qiitaに反映（公開＆更新）」まで一気に自動で行ってしまう

という思い切った仕様はどうでしょう。つまり、Wikipedia方式です。

肝心の（面白そうな） 「 👍 のカウント数による決定のシステム」ですが、**非BOTユーザからのプルリクに対して適用する**、とかが良いと思います。

これにより、マージまでのレビューが面倒な人はBOTをフォローするだろうし。

**Comment by hidao80** [comment]
Wikipedia方式にすると完全に「今のQiita の投稿とコメント」の関係になりませんか？

1. 初版は無条件で出る
2. アカウント持ちなら記事の修正案が提示できる（マージされるとは言っていない）
3. 2版以降のマージ決定権をリクエスト者独断から合議制にする

う〜ん、1.、2.までは qiita と同じだし、3. が嬉しいリクエスト者はいないと思うんですが。

他方、フォロワーが記事に対するコメントへのコミットメントが稼げると考えられる点は優れていると思います。

なんだか根幹に関わる問題のようなので、お返事を待って議論を煮詰めたいと思います。

**Comment by KEINOS** [comment]
わかりづらくてすみません。

    2版以降のマージ決定権をリクエスト者独断から合議制にする

上記の３番目がちょっと違います。

- BOTのフォロワー全員が自由にQiitaコラボ記事の本文を**いつでも**編集・更新できる
- リクエスト者はリスペクトの意味で初稿の名前は出ますが、基本的にはBOTのフォロワー全員の記事という扱い

１点だけイレギュラーがあり、**BOTのフォロワーの囲い込み**として、合議制が発動するのはBOTのフォロワー以外からQiitaコラボ記事のリクエストが来た場合のみです。

フォロワーにならないと自由に触れないWikipediaみたいな状態です。

なので本題の『「記事原稿第1版が完成している」かどうかを BOT から判断する方法』は、いささか本末転倒なのですが

    BOTのフォロワーと判断したら関係なく更新しちゃう

また、本件とは別に、公開したQiitaコラボ記事のQiita側にコメントが付いた場合、どうするかという問題がありますが別issueだと思います。

**Comment by hidao80** [comment]
> BOTのフォロワーと判断したら関係なく更新しちゃう

が本 issue の結論でいいと思います。

> 合議制が発動するのはBOTのフォロワー以外からQiitaコラボ記事のリクエストが来た場合のみ

これもいいですね。代案がなくても参加できるため、Github や Qiita の「issue（or 編集リクエスト）上げるのが恐れ多い感」が緩和されそうです。

本 issue、解決としてクローズして良いと思います。

**Comment by KEINOS** [comment]
👍

**Comment by hidao80** [comment]
クローズした issue に投稿してしまって申し訳ないです。

> 私のイメージでは「マージ作業そのものはBOT」で「マージの決定権はBOTのフォロワー」にあり、彼らの「 👍 」数（しきい値ごえ）が「マージをGOのサイン」です。
>
>そのため「👍 数がしきい値を超えていたらその時初めて初版になる」と同等で良いと思います。

しきい値を決めていませんでしたね。ドキュメントまとめていて気が付きました。で、提案。

A案. 👍 が**過半数** (= count(:thumbsup:) > round( vote / 2 ) ) )。**同数なら否決。**
B案. 👍 が**半数以上** (= count(:thumbsup:) >= round( vote / 2 ) ) )。**同数なら可決。**
C案. 👍 が 2 / 3 以上なら可決。

どれにしましょう？　対案もお待ちしています。

**Comment by KEINOS** [comment]
これは、「非フォロワーからのプルリクに対する投票」の事ですよね。

基本的には

    B案の「半数以上」

に1票です。

ただ、懸念事項として検討しておきたいのは、もし嬉しいことにフォロワーが増えた場合、100人フォロワーがいたら50人の賛同を得ないといけないわけで、**過半数超えを待つのは辛いか**な、と。:thumbsup: を反応してくれるのは最初は少ないと思うし。

ただ、「待つのが辛い人はフォローしてね！」で済む話でもあるので、私は「B案」がいいと思います。

**Comment by hidao80** [comment]
>B案の「半数以上」に1票です。
>（中略）
>ただ、懸念事項として検討しておきたいのは、もし嬉しいことにフォロワーが増えた場合、（中略）過半数超えを待つのは辛いかな、と。

なるほど。確かに、フォロワー数とアクティブユーザ数が比例しないのは SNS の常ですよね。

で、**D案**として「10 人の推薦（=:thumbsup:x10）を受けた非フォロワーからの投稿記事は**可決**としてマージされる」を提示します。

「推薦」だの「可決」だの言っていると、政治をやっている気分になりますね。:) 実際そうですが。

**Comment by KEINOS** [comment]
D案 👍 

しきい値は稼働してみないとわからないので難しいですが、まずは「 👍 x 10」でスタートは妥当だと思いました。

## 非BOTフォロワーからの投稿記事の扱い

- BOTのフォロワー数以上、もしくは１０の :thumbsup: がある場合はマージする

**Comment by KEINOS** [comment]
## 相談：長期編集を行なっていると公開しても新着に表示されない問題

<img width="50%" align="right" alt="2017-10-17 13 55 50" src="https://user-images.githubusercontent.com/11840938/31647535-dd77ba42-b343-11e7-85ab-79116fd6f9bb.png">

#55 により、本日（2017/10/17）限定共有→公開した、[WPA2のセキュリティに関する Qiitaコラボ記事](https://qiita.com/Qithub/items/17871e7f26c308ef6514)で気づいたのですが、Qiitaのトップに表示される記事は**公開日順ではなく、下書きでなくなってからの時間順**のようです。

右図を見てもらうと、前日の晩にトゥートするために限定共有に切り替えた時間が投稿日になっています。

そのため、せっかく**公開したのに新着に表示されない**ため Qiita記事のタグのフォロワーにしか見てもらえないという事象が今後も発生する可能性があります。

### 提案

決定事項と重複しますが、整理も含めて改めて以下のフローでいかがでしょう？

1. 新規Qiitaコラボ記事（ブランク記事）の作成依頼（BOT／手動含む）→ 下書き @ Qiita
1. Qiita記事IDでGitHubに同ブランク記事を作成 → ここでQiitaとGitHubがリンクされる
1. 著者はClone/Fork/MergeFromMasterを行い記事を修正＆コミットする
1. 著者は原稿があがったら PR を行う
1. BOT のフォロワー以外からの PR の場合のレビューは GitHub 上で行う **← ここがポイント**
1. マージが実行された場合は、Qiita側に同期を行う
1. 新規の場合はステータスを「**下書き→公開**」に変える
1. (3)に戻る

#### ポイントの問題点

GitHub と Qiita では Markdown のテイストが若干違うため、理想で言えば公開前に Qiita でプレビューしたいところです。

しかし、下書き状態を見れるのは BOT のアカウントでログインした場合のみなので、限定共有で公開してチェックする必要がありますが、先の新着表示に影響が出てしまいます。

1. プレビュー専用の記事を別途作成
2. マージが行われた場合はプレビュー記事を削除
3. 本場の方の記事に適用

ブランチ的なイメージですが、BOTの処理（開発スピード）が追いつかない気がします。

お手すきにご意見お待ちしておりマストドン。

**Comment by hidao80** [comment]
問題が2点含まれていると思います。

1. 未コミット master (卑近な表現として「**バージンリモート master** 」と命名します) を同時にclone / fork していたとして、「初稿」とされるのは **最初に PR がマージされたブランチ** となるような気がしますが、これで OK ？  
このとき、最初のマージが行われる前にコンクリフトしていたらどうしますか？ PR に、「現在自分も編集中であること」をアピールする必要がある？ 早い者勝ち？  
**この問題はPR が2つ以上立つまで顕在化しません。**
2. Qiita プレビューは Increments, Inc. のアプリ「Kobito」でしてはどうでしょうか？  
仮にも謹製アプリなので、Qiita と同じ Markdown の描画をすると期待します(未検証)。  
Win/mac のみ対応なので、Linux ユーザ涙目ですが😓  
参考:<http://kobito.qiita.com/ja/features>

## 提案

1. 記事ID振り出しから初稿の発行までに「初版発行猶予期間」を設ける？  
その場合の情報の鮮度はどう担保する？  
誰の合意を得れば初版発行猶予期間を無視できる？
2. プレビュー問題は「Kobito」を使ってもらうこととする。

ご意見お待ちしております。

**Comment by KEINOS** [comment]
## 問題２プレビューに関して

**「Kobito」を使ってもらう** に 👍 

基本方針として「Kobito」を使ってもらうのが現実的だと思います。最悪、自分の Qiitaアカウントの下書きで確認してもらうなど方法はありますし。

## 問題１に関して

本題ですが **マージの基本方針として「コンフリクトのない PR をした早い者勝ち」が良い** と思います。

    「初稿」とされるのは 最初に PR がマージされたブランチ

はい。Qiita 側の記事から見て ID 振り出しの「下書き」状態のものが バージンリモート master です。そして バージンリモート master に最初に PR がマージされたもの、つまり（卑近な表現として）バージンロストが Qithub にとっての初稿です。

    記事ID振り出しから初稿の発行までに「初版発行猶予期間」を設ける？

先の「コンフリクトのない PR をした早い者勝ち」ルールで考えると **猶予期間は設けなくてよい**と考えます。

確かに、一般的には バージンリモート master の作成依頼者（ユーザーA）が初回 PR をあげて初稿となるのが通例だと思います。

しかし、アチキのようにチンタラしていると鮮度の問題もあるため、PR 前にバージンリモート master を同様に Clone して「v(｡･ω･｡)ｨｪｨ♪」と原稿を先にあげて PR する人（ユーザーB）も居ていいと思います。

その場合、ユーザーBにバージンロスト、つまり Qiita記事のステータスが「下書」→「公開」に変更されるわけですが、もちろんユーザーAは 横取りされた感 満載なので「Σ(゜Д゜;)」となると思います。

残念ですが、その場合はユーザーAは PR #54 にあったように、現在の master をローカルで自身のブランチにマージ→コンフクトを直してから内容を整えて PR することになります。

ただ、別件（別issue）ですがコントリビューターを記事の文末に列挙して行きたいと考えているので、ユーザーBによる初稿であっても、コントリビューターの並びとしては バージンリモート master の生みの親である ユーザーA がイニシャルになるのが良いと考えています。

<kbd> ![2017-10-17 23 25 01](https://user-images.githubusercontent.com/11840938/31670406-796476e0-b392-11e7-9e33-67be8ef92769.png) </kbd>

### PR が複数ある場合

issue #52 の「PR を立てる基準」によれば、PR 者みずからのマージ ✋ はNGとなっており、それを望む場合は `push` することを推奨しています。

そのうえで PR が複数あるパターンとして以下が考えられると思います。

1. ほぼ同じタイミングで複数人が PR をあげた
2. 先行 PR が 非フォロワーからなので合議制が発動している間に、他者が PR をあげた
3. そもそも PR 内容に問題があり対処中に問題のない PR があがってきた
4. マージ担当者らが 🚅 ♨️ ✈️ ⛵️ 🏄 🚀 に行っており、なんか放置されている

4を覗く、いずれも PR 時にコンフリクトを確認できるため **「コンフリクトのない PR をした早いもの勝ち」 で対処できる** し **「情報の鮮度」も保たれる** ように思います。

    「現在自分も編集中であること」をアピールする必要がある？

必要はありませんが、アピールする機会はあっていいと思います。早い者勝ちとは言え、やはり横取りは良くないと考える人も当然いると思いますし、足並みを揃えたいという人もいると思います。

この場合のアピールは issue #52 を参考に、各々ブランチを `push` して各自が確認しあうのが良いと思います。

**Comment by hidao80** [comment]
ぬー、何か認識が違うところがありますね。😓

Qithub-BOT/scripts#3 によると、Qiitaコラボ記事の新規作成のプロセスは次の通りです。

>- Qiita の Qithub アカウントで新規記事を作成、記事IDを取得する
>- 同記事IDでitemsrepo（master）にテキストファイルを作成する
>- これらの動作はBOTが行うこととする

ここまでが決定事項ですが、私の解釈では、

1. 新規記事リクエストコマンド（トゥート）を BOT に投げる
1. BOT が新規記事の**空の記事を Qiita と Github に作成し、記事 ID （＝ Github ファイル名）をリプライする**
1. 2 をバージンリモート master として、初稿競作者たちが**白紙のバージンリモート master に PR 競争をする**
1. **最初にマージされた PR が初稿（下書きかも？）となる**

と言うのも、決定事項に「記事 ID 取得トゥート時に本文を含む」合意がないためです。  

逆に、新規記事リクエストに下書きを含むのであれば、**Markdown 込みの原稿を 1 つのトゥートに新規記事リクエストコマンド文字列+記事タイトルを除いた文字数で書いておかないといけない**ことになります。

また、白紙のリモート master に PR するとなると、**コンクリフトを検出する方法が git に備わってない**
のですが、（＝ RP のコンクリフト検出方法はマージ先とローカルリポジトリの差分によるものなので）**初稿登校時は同時に PR してもコンクリフトが検出されない**ことになります。

## 提案と相談

記事 ID 要求者に、**無断でゲラを作る（＝ 1回目の下書きをマージする）権利を与えてはどうか**と思います。

ただし、この方法では BOT が「このマージがゲラか初稿か」を判断する方法がありません。どうするのがベターでしょうか？

**Comment by KEINOS** [comment]
概ね、流れは同じだと思いますがディテールで食い違いがあるのかもしれません。

    決定事項に「記事 ID 取得トゥート時に本文を含む」合意がない

そうですね。Qiita側ブランク記事の作成を改めて試してみたところ、まったくの**ブランクなデータの場合は記事を作成しても削除される**（保存されずIDが破棄されてしまう）ようです。API経由だとエラーが返ってきます。

その為、上記「`1. 新規記事リクエストコマンド（トゥート）を BOT に投げる`」の時点で「タイトル」と「本文」（いずれも１文字以上）の2点の情報が必要になります。

それを踏まえて、私の考える流れを整理したいと思います。違和感のある箇所おまちしており 💪 

1. **新規記事リクエスト**<br>フォロワーは、 Qiitaコラボ記事 の「テーマ」（タイトルと概要）とリクエスト・コマンドを記載した、未収載メンショントゥートを BOT に投げる。
1. **新規Qiita記事の作成（Qiita側）と記事IDの取得**<br>BOT が Qiita の Qithub アカウントで 1 のテーマの内容を含んだ新規記事を「**下書き**」で作成し、記事IDを取得する。
1. **新規Qiita記事の作成（GitHub側）と記事IDの通知**<br>BOT が 2 と同内容の記事を Github に作成し、記事 ID （＝ Github ファイル名）を 1 にリプライする。（＝フォロワーにもテーマを通知）
1. **PR 競争の開始**<br>3 をバージンリモート master として、初稿競作者たちが各々 バージンリモート master のブランチを作成しコミットをはじめる。必要なら `Push` もする。（牽制）
1. **PR と初稿および出版** ※<br>最初に PR されたものが BOT によりリモート master にマージされ（初稿＝初校＝初版）、 2 の Qiita側の記事を更新し 「**公開**」で保存する（外部的には第１版の出版）
1. **出版のアナウンス**<br>（該当記事の）GitHub側のブランチは削除され、原稿が公開された旨を 1 にリプライする（外部アナウンスは定時処理の新着Qiita記事トゥートで行う）
1. **master に追随する**<br>PR 競争に負けた人は、各々リモートの master を自身のローカルに `Pull`しブランチのコンフリクトを直す、もしくはブランチを破棄し、新たにブランチを作成する
1. **次版の PR 競争開始**<br>各自、自身のブランチにてコミットを行う。必要なら `Push` もする。（牽制）
1. **前版の校正＆加筆**<br> コミットが終わった者から初版ではないが手順として 5 に戻る

※ PR 者が BOT のフォロワーでない場合は、フォロワーの合議制が発動し、PR （この場合はゲラ）がフォロワーに通知され :thumbsup:を満たした場合のみ リモート master にマージされる

**Comment by hidao80** [comment]
この流れの説明で納得できました！

### 提案

バージンリモート master を作る際にゲラを要求するように読めたのですが、次のようにしたらどうでしょう？

1. 上記 1 で新規 ID 発行時、**タイトルだけ要求して、本文は「本文なし」として下書きを作成する。**
1. そのまま PR レースに突入
1. 1st. PR を初稿（=初版）とする

**Comment by hidao80** [comment]
この方向で進めるなら、README.md に書いてある、以下の記述を変えないとですね。 😅 

>※ 後述するBOTのフォロワーの 👍 が１０以上得られると、Qiita記事のステータスが「限定共有」から「公開」に変わります。

**Comment by KEINOS** [comment]
> バージンリモート master を作る際にゲラを要求するように読めた

ゲラと言うより **「テーマ」の概要** のつもりでした。

つまり、「新規記事リクエスト」のトゥートは下記のようなイメージです。

```
    ＠qithub #Qiitaコラボ記事:setTheme
    こんなテーマで記事を作成してみたいです。
    ```
    #はじめてのQiitadon
    「Mastodon に興味はあるが Qiitadon から始めてみるか」と考え
    ているQiitaユーザーに、マストドンの基本や Qiitadon の特徴など
    初めてでも入りやすい情報を提供する。
    ```
```

上記のスクリプト・ブロックの１行目＋ハッシュタグ付きが「記事のタイトル」、そして２行目以降が本文に入るイメージです。

いずれにしても、`README.md`の「※イケメンに限る」は変えるべきですね。

**Comment by hidao80** [comment]
がってん！ ガッテン！ 合点！ 👍

タイトル＋サマリなら十分 1 トゥートに収まりそうですね！  

と、いうことは**新規記事立ち上げトゥートは記事 ID をとってサマリ入りの「下書き」状態を作り、Github にファイルを作るだけ**という認識でファイナルアンサー！

正解をお願いします！

> ※イケメンに限る

？ （謎 🤔

**Comment by KEINOS** [comment]
> と、いうことは新規記事立ち上げトゥートは記事 ID をとってサマリ入りの「下書き」状態を作り、Github にファイルを作るだけという認識でファイナルアンサー！

ファイナルアンサー！で 👍 

>> ※イケメンに限る
>
> ? (謎 🤔 

😄 つ 参考文献

※1 https://user-images.githubusercontent.com/11840938/31721170-a153f2b8-b453-11e7-9028-98909639e906.png
※2 http://workingnews.blog117.fc2.com/blog-entry-1431.html

**Comment by hidao80** [comment]
👍 

TL;DR 書いて、 👍  を待ってクローズします。

**Comment by KEINOS** [comment]
👍 

P.S. 秋ですね。TL;DR に念のためのリンクを貼りました。
