### ISSUE TITLE
【提案】Qiita 記事墓場のリポジトリ設置（Qiita-SAPMS, 旧名 Qiita-cemetery）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#130]
## 相談

スパム認定された Qiita 記事のみをストックするリポジトリの設置。
Repo 名： Qiita-cemetery or Qiita-items-cemetery

## 自分の案

[Qiitadon でスパム対策が盛り上がっています](https://qiitadon.com/web/timelines/tag/qiita%E3%82%B9%E3%83%91%E3%83%A0)。どうやら、いまスパムシーズンらしいので、[旬なうちに新鮮なスパムをストックしておきたい](https://qiitadon.com/@KEINOS/100699237695228499)と思いました。

新着Qiita記事をトゥートする際にキャッシュしておき、一定期間後にその記事が存在しなければスパム記事認定ということでストックされるリポジトリがあれば、スパム用のコーパス（学習データ）に利用できるのではないかと。

そのまま（平文のまま）ストックしておくと `https://github.com/Qithub-BOT/` 下が Google 八分にされると思うので、Qithub(bot) の秘密鍵で暗号化しておき、公開鍵で復号できるようにしておけばいいかなと思います。

## TL;DR（進捗・結論 2018/09/14 現在）

- Qiitaの発展に寄与するものと考え、本 Organization で取り扱うことに。https://github.com/Qithub-BOT/Qithub-ORG/issues/130#issuecomment-419884759
- リポジトリ名は ~~Qiita-cemetery~~ → 「[Qithub-SPAMS](https://github.com/Qithub-BOT/Qiita-SPAMS)」→ 作成済み
- スクリプトからの動作検証待ち (*´･д･)(д･`*)

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue #14 [スパム Qiita 記事チェッカー](https://github.com/Qithub-BOT/Qithub-ORG/issues/14#issuecomment-360410314) | 機能拡張 なくてもいいけど、あるとよりよい機能は？

**Comment by hidao80** [comment]
結論から言うと、**リポジトリにスパム記事を蓄積することには反対です**。

## 理由

GitHub は「設計図共有サイト（笑」であって、「データベースの実体」では無いと認識しているためです。

スパム記事はコードではないので、**GitHubで管理する対象としてふさわしくない**と考えます。
私にはスパム記事を編集して PR あげるユースケースが想像できません。

## 対案A

Qithub サークルの遊び場として提供していただいているサーバに間借りをさせていただけませんか？

遊び場サーバならGoogleのヘイトを買ってもほぼダメージがなく（要検証）、平文として置いておくのもスパム記事web魚拓サービスを運営するのも思うがままだと考えます。

**Comment by alice1017** [comment]
すみません、スパム記事をストックする意味がよくわかんないです… 💦

**Comment by KEINOS** [comment]
> GitHub は「設計図共有サイト（笑」であって、「データベースの実体」では無いと認識しているためです。 @hidao80 

私は GitHub はあくまでもオンラインのリポジトリという認識です。公式の「GitHub のはじめかた」でも、以下のように「多種多様なプロジェクトを GitHub のリポジトリに保存可能です」とあり、そのうえで「オープン・ソースを含む」とあるので、データ（DBの実態）でも問題ないと考えています。

> You can store a variety of projects in GitHub repositories, including open source projects.
> https://help.github.com/articles/create-a-repo/

また、私自身も[ユーザー辞書を公開](https://github.com/KEINOS/google-ime-user-dictionary-ja-en)したり、機械学習用の辞書（コーパス）や、日記や記事など、**内容に関しては GitHub そのものは制限していない**と考えています。（違法であるといったものは除く）

ただ、**スパム記事対策のためのデータ作成が Qithub のサークル活動なのか**という点は再考の余地がありますね。

> 私にはスパム記事を編集して PR あげるユースケースが想像できません。 @hidao80 

過去の（消された）スパム記事を持っている人が PR する以外はないですよね。ほとんどの場合は、リソースとしての利用になるのは必至だと思います。

> Qithub サークルの遊び場として提供していただいているサーバに間借りをさせていただけませんか？ @hidao80 

もちろん。サークルで使うぶんには自由に使って構いませんし、望むところです。

> スパム記事web魚拓サービスを運営する

実はそれが目的なんです。その外部ストレージ的に GitHub のリポジトリを使いたいな、と。

**Comment by KEINOS** [comment]
> すみません、スパム記事をストックする意味がよくわかんないです… 💦 @alice1017 

おぉう！色々と前提ありきで話してました！すみません。💦

Qiita 記事はスパム認定されると削除されるので、スパムフィルターを作成しようとする場合、どのようなパターンがある／あったのかがわかりません。

そこで削除された Qiita 記事をリポジトリにストック（溜め込む）ことで、後続の人が過去のスパムから何か見出してサービス化もしくは Qiita 記事の（全体的な）品質に貢献できればいいな、というためのリポジトリです。

イメージとしては下記 Qiitadon の Yyano さんのリポジトリみたいな感じで、タイトルでなく記事の Markdown ファイルが蓄積されていくだけのイメージです。

https://github.com/yyano/Qiita-News

**Comment by alice1017** [comment]
スパム記事を集める目的はわかりました！
ところで、そのスパム記事は手動で集めるのでしょうか？

**Comment by KEINOS** [comment]
> ところで、そのスパム記事は手動で集めるのでしょうか？ @alice1017 

そうですね。

`_(:⁍」 )_` < えー、手動でやるのー

嘘です。もちろん自動化します。 Cron で BOT の尻を叩いて以下の動作を考えています。

### 新着Qiita記事トゥート BOT

1. 新着 Qiita 記事を取得する
2. QiiTime の最新トゥート ID を取得する
3. QiiTime に返信で「新着 Qiita 記事＋記事のタグ」をトゥートする
4. トゥートが成功したら、その Qiita 記事を内部でキャッシュしておく
5. トゥート時から１ヶ月前の記事をキャッシュから探し 404 でないか確認
    - 404 → Qiita記事墓場へ保存＆キャッシュの削除
    - 404 以外 → キャッシュの削除
6.  「Qiita記事墓場の更新スクリプト（仮）」を叩いて 1 へ戻る

### Qiita記事墓場の更新スクリプト（仮）

1. 差分をコミット＆マージする
2. リモートにプッシュする

**Comment by KEINOS** [comment]
新着Qiita記事トゥート BOT は Python でやってみてもいいかもですね。

QiiTime と同じ階層に設置して。

https://github.com/Qithub-BOT/Qithub-ORG/tree/master/api/v1

**Comment by alice1017** [comment]
@KEINOS 
なるほど！
「スクリプトでやるなら**スパム判定**しなきゃいけないんじゃ」と思ってました笑

PythonでやるならQiita記事墓場の更新スクリプトの方が適格かもしれません

**Comment by KEINOS** [comment]
> PythonでやるならQiita記事墓場の更新スクリプトの方が適格かもしれません @alice1017 

なるほど！適材適所ですな。では、新着Qiita記事トゥート BOT はこちらで作成を続けるので、その間、更新スクリプトを Python でお願いしていいですか？

ってか、墓場 repo 前提で進んでしもた！ 😅 

店長ー、メニューにない repo の注文が来たんですけどー。なんか生ゴミらしいんですけど、どうします？ > @hidao80

**Comment by alice1017** [comment]
@KEINOS 

まだ @hidao80 さんの確認がとれてませんが、一応Pythonでスクリプト作るとして、サーバーの方に [delegator.py](https://github.com/kennethreitz/delegator.py) というライブラリを `pip2`  でインストールしていただけませんでしょうか。

`delegator.py` はPython上でシェルコマンドを簡易に実行できるライブラリです。

**Comment by KEINOS** [comment]
> delegator.py というライブラリを pip2 でインストールしていただけませんでしょうか。 @alice1017 

( ﾟДﾟ)ゞ ﾘｮｰｶｲ!!ｼｮｰｼｮｰｵﾏﾁｸﾀﾞｻｲ!!

**Comment by KEINOS** [comment]
@alice1017

( ﾟДﾟ)ゞ  ﾀｲﾁｮｰ! ｶﾝﾘｮｳｼﾏｼﾀ! ｲｶｶﾞﾃﾞｼｮｳｶ!

> delegator                    0.0.3
https://qithub.tk/tools/version/?key=pip+package+installed&type=program

**Comment by hidao80** [comment]
@KEINOS

GitHub にスパム記事を収集する理由と論拠、承知しました。

また、当事案は**Qiitaの発展に寄与するもの**と考えますので、本 Org で取り扱うことにふさわしいと考えます。

取り急ぎ、意見をお伝えしておきます。

**Comment by KEINOS** [comment]
> 本 Org で取り扱うことにふさわしいと考えます。 @hidao80 

@alice1017 さん、店長が Qiita スパムのメニュー追加して良いって！どうします？ org での repo の作成やってみます？それとも今回はアチキが作成しましょうか？

**Comment by alice1017** [comment]
@KEINOS 

今回は @KEINOS さんにお願いしたいです！
よろしくおねがいします！

**Comment by KEINOS** [comment]
@alice1017 ( @hidao80 )

リポジトリを作成しました。とりいそぎ叩き台まで。

## Qiita-SPAMS
https://github.com/Qithub-BOT/Qiita-SPAMS

repo 名ですが、セメタリーは打ちにくいのと覚えにくいのでスパムにしました。

ライセンスは、本リポジトリと同じ CC-BY-SA です。うん国際ライセンスです。

- `.gitignore` でコミットできる拡張子を制限しています。（`.md``.enc`のみ）ホワイトリスト形式なので、必要に合わせて追記していってください。

アチキの Git 環境は Org の全権を持ってしまっているため、スクリプトからの利用（`Push`など）でどんな権限や設定を付与すればいいのか、いまいちわからないので「●●くれよん」などがあったらお知らせください。

ローカルで Git 操作するスクリプトができたらお知らせください。設置先を決めましょう！

**Comment by KEINOS** [comment]
### 【中間報告】

#### スパム記事は消されていない

スパムとして削除された Qiita 記事の確認をするために 404 のヘッダーを触っていて気づいたのですが、どうやら**過去のスパム記事やスパマーのアカウントは Qiita の DB にある**みたいです。

というのも、直接サイトを見ると 404 になっていても、API で記事の ID を叩くと取得できてしまいます。

##### 削除記事
- 削除された記事ページ:  https://qiita.com/shivanijain/items/5585a8886126c03f5244
- 記事ID: `5585a8886126c03f5244`
- API でページの魚拓が見れる: https://qiita.com/api/v2/items/5585a8886126c03f5244

##### 削除ユーザ
- 削除されたユーザーページ: https://qiita.com/shivanijain/
- ユーザーID: `shivanijain`
- API でユーザーの魚拓が見れる: https://qiita.com/api/v2/users/shivanijain

ただ、JSON データやヘッダーを見ても **API ではそのページやアカウントが BAN されたことはわからなかった**です。

そのため、記事のヘッダーを見て 404 だったら、ユーザーページのヘッダーを見て、それも 404 だったら BAN されたアカウント、つまり完全にアウトな記事とみなしていいと思います。

### 本家 API で取得可能なのに Qiita-SPAM 墓場は必要なのか

必要だと思います。本家 API では、**スパムである**という情報がないため、やはりスパムに特化したアーカイブは必要だと思います。（スパム専用の魚拓サービスになってしまいますが）

### 報告した理由

**本サービスが開始してからのスパムしかアーカイブ出来ないと思っていた**のですが、**１年前からのスパムをアーカイブできそう**です。

というのも yyano さんの新着 Qiita 記事のアーカイブが記事タイトルとリンクのみとは言え、 2017/12/05 からで、スパムをもアーカイブしているからです。

- 新着Qiita記事のアーカイブ
    - https://github.com/yyano/Qiita-News

- 2017/12/05 のアーカイブにある記事
    - アーカイブの情報: https://github.com/yyano/Qiita-News/blob/master/2017/2017-12-05.md#detroit-tigers-information-brad-ausmus-may-well-be-the-tigerssupervisor-within-2018
    - 削除されたページ: https://qiita.com/turner3/items/ef30669417ff9862bb06
    - 記事ID: `ef30669417ff9862bb06`
    - API でページの魚拓が見れる: https://qiita.com/api/v2/items/ef30669417ff9862bb06

なので、新着 Qiita 記事のトゥート & キャッシュと `Qithub-SPAMS` のプッシュの実装が済んだら、単発アプリなどを作って過去の墓場を掘り起こしに行きましょう！

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

本件、表題の [Qiita-SPAMS](https://github.com/Qithub-BOT/Qiita-SPAMS) リポジトリは作成できたので Close でもいいのではと思います。

`git.py` の実装や仕様決めは別 issue の方が良いと思います。
