### ISSUE TITLE
【提案】Sider（SiderCI）の自動コードレビューで ESLint を除外（一時除外）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#132]
## 提案

どこかに `node.js` やサイト表示用の外部 Javascript のファイルが置かれるまでの間は、**自動コードレビューに「`ESLint`」 は利用しない**ことにしませんか？

## TS;DR

Issue #127 のサークルメンバーを MEMBERS.md に追記する件であげた PR #131 で、新規 Markdown が ESLint のレビューを通らない（Markdown が ESLint を通る）ようになってしまいました。

[ESLint v5 からの仕様](https://qiita.com/KEINOS/items/bac1e1c46df64311d8a2)を[設定で回避した](https://qiita.com/KEINOS/items/03de9a0765e32f50a3ca)ことによる副作用のようで、現在はダミーの [`dummy.js` を設置して回避](https://github.com/Qithub-BOT/Qithub-ORG/pull/131/commits/c3b02a1c28a47f1e6087452491bb0494b163364e)しました。

`dummy.js` を置いておけば問題はないのですが、それもそれで気持ち悪いので。

## TL;DR（進捗・結論 2018/09/10 現在）

👍 ２つで、アチキのアカウントの方の Sider の ESLint 設定をオフにします。

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 Issue https://github.com/Qithub-BOT/Qithub-ORG/pull/131#issuecomment-419831625

**Comment by alice1017** [comment]
:+1:

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
Commit f6f8d34 で `dummy.js` を削除＆自動コードレビューをパスしたので Close しまーす。
