### ISSUE TITLE
README.md に使うバッジ各種

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#135]
## 提案・相談・報告

Issue #123 「コミットメッセージの言語について」であがった、README.md に掲載するバッジ各種の制定とそのバッジの URL です。

- 提案をコメントして 👍 ２つ以上で制定。（TL;DR に追記していくこと）
- バッジの作成先  https://img.shields.io/

## TL;DR（結論 2018/10/13 現在）

- Wiki 「[各リポジトリの README.md に使うバッジ](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E5%90%84%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE-README.md-%E3%81%AB%E4%BD%BF%E3%81%86%E3%83%90%E3%83%83%E3%82%B8)」

### 色 https://github.com/Qithub-BOT/Qithub-ORG/issues/135#issuecomment-420913842

| 色名 | 用途 | サンプル | 備考 |
| :--- | :--- | :---: | :--- |
| brightgreen |**掲載が必須**<br> **リポジトリごとに任意**に決めていいもの | ![](https://img.shields.io/badge/brightgreen-%E7%B7%91%EF%BC%88%E6%98%8E%EF%BC%89-brightgreen.svg) | |
| green| 未定 | ![](https://img.shields.io/badge/green-%E7%B7%91-green.svg) | |
| yellowgreen| 未定 | ![](https://img.shields.io/badge/yellowgreen-%E9%BB%84%E7%B7%91-yellowgreen.svg) ||
| yellow | 未定 | ![](https://img.shields.io/badge/yellow-%E9%BB%84%E8%89%B2-yellow.svg) ||
| orange | 未定 | ![](https://img.shields.io/badge/orange-%E3%82%AA%E3%83%AC%E3%83%B3%E3%82%B8%E8%89%B2-orange.svg) ||
| red | 未定 | ![](https://img.shields.io/badge/red-%E8%B5%A4%E8%89%B2-red.svg) ||
| lightgray | 未定 | ![](https://img.shields.io/badge/lightgray-%E7%81%B0%E8%89%B2%EF%BC%88%E6%98%8E%EF%BC%89-lightgrey.svg) ||
| blue |**掲載が必須**<br>Organization 内**全体で共通**のもの | ![](https://img.shields.io/badge/blue-%E9%9D%92%E8%89%B2-blue.svg) ||

### スタイル https://github.com/Qithub-BOT/Qithub-ORG/issues/135#issuecomment-421225911

- 「`flat`」（デフォルト）
- ![](https://img.shields.io/badge/style-flat-green.svg?longCache=true&style=flat)

### 制定済みバッジ

![License](https://img.shields.io/badge/license-CC%20BY--SA%204.0-brightgreen.svg)
![日本語ドキュメント](https://img.shields.io/badge/document-ja__JP-brightgreen.svg) ![Documents in English](https://img.shields.io/badge/document-en__US-brightgreen.svg) ![Documents in Multi-language](https://img.shields.io/badge/document-ja__JP%20en__US-brightgreen.svg)
![日本語コミットメッセージ](https://img.shields.io/badge/Commit%20message-ja__JP-brightgreen.svg)
![日本語ソース内コメント](https://img.shields.io/badge/code%20comment-ja__JP-brightgreen.svg)
![参加ポリシー](http://img.shields.io/badge/policy-Qithub%203原則-blue.svg)

```
![License](https://img.shields.io/badge/license-CC%20BY--SA%204.0-brightgreen.svg)
![日本語ドキュメント](https://img.shields.io/badge/document-ja__JP-brightgreen.svg)
![Documents in English](https://img.shields.io/badge/document-en__US-brightgreen.svg)
![Documents in Multi-language](https://img.shields.io/badge/document-ja__JP%20en__US-brightgreen.svg)
![日本語コミットメッセージ](https://img.shields.io/badge/Commit%20message-ja__JP-brightgreen.svg)
![日本語ソース内コメント](https://img.shields.io/badge/code%20comment-ja__JP-brightgreen.svg)
![参加ポリシー](http://img.shields.io/badge/policy-Qithub%203原則-blue.svg)
```

- 当リポジトリの README.md に反映しだい Close

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 Issue #123 「コミットメッセージの言語について」

**Comment by KEINOS** [comment]
## 色の提案

`brightgreen` → リポジトリごとに任意に決めていいが、**掲載が必須**のもの
`blue` → Organization 内全体で共通、かつ**掲載が必須**のもの

**Comment by hidao80** [comment]
👍

**Comment by alice1017** [comment]
色の提案に 👍 
shields.io のバッジには「style」というものもありますが、どうしますか？

flat
![](https://img.shields.io/badge/style-flat-green.svg?longCache=true&style=flat)

flat-square
![](https://img.shields.io/badge/style-flat--square-green.svg?longCache=true&style=flat-square)

for-the-badge
![](https://img.shields.io/badge/style-for--the--badge-green.svg?longCache=true&style=for-the-badge)

popout
![](https://img.shields.io/badge/style-popout-green.svg?longCache=true&style=popout)

popout-square
![](https://img.shields.io/badge/style-popout--square-green.svg?longCache=true&style=popout-square)

個人的にはflatがいいかなとおもいます

**Comment by hidao80** [comment]
私も flat に👍

**Comment by KEINOS** [comment]
flat に 👍 → TL;DR 済み

**Comment by alice1017** [comment]
👍

**Comment by hidao80** [comment]
この issue、close してもいいのかしらん？

**Comment by KEINOS** [comment]
> この issue、close してもいいのかしらん？ @hidao80 

Wiki に記載しました。本リポジトリの README.md にコミット言語のバッジを適用したら Close にしましょうかね。

- [各リポジトリの README.md に使うバッジ](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E5%90%84%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE-README.md-%E3%81%AB%E4%BD%BF%E3%81%86%E3%83%90%E3%83%83%E3%82%B8)

**Comment by alice1017** [comment]
バッジ付けなきゃいけない項目って言語以外に何かありますかね？ 🤔

**Comment by KEINOS** [comment]
@alice1017 

必須だけ決めて、後は任意で良いとは思うのですが、必須項目、悩みますな。いま思いつくのはこんなものかしら。

### 必須
- ライセンス（LICENSE.mdへのリンク付き）
- 言語
    - コミットメッセージ
    - コード内コメント
- Organization 三原則（Wiki へのリンク付き）

### 任意
- CI テスト

### 参考文献
- [クラウドサービスを活用して README にバッジをペタペタ貼る](https://qiita.com/dtan4/items/13b0ea9edf5b99926446) @ Qiita
- [shields.io経由でだいたいなんでも自由にバッジ表示する](https://qiita.com/ymtszw/items/77d1d6bbe0687848470b)

**Comment by alice1017** [comment]
![](https://img.shields.io/badge/license-CC%20BY--SA%204.0-brightgreen.svg?style=flat)
![](https://img.shields.io/badge/Commit%20message-Ja-blue.svg?style=flat)
![](https://img.shields.io/badge/code%20comment-Ja-blue.svg?style=flat)
![Policy](http://img.shields.io/badge/policy-Qithub%203原則-blue.svg?style=flat)
こんな感じですかね

**Comment by KEINOS** [comment]
@alice1017 

おお。わかりやすい。ライセンス同様に **「コミット言語」「ソース内コメント言語」もリポジトリごとに決められる**（も掲載は必須である）ので「緑（明）」だと思います。→TL;DR の文言を明文化しました

また、細かいですが "style=flat" がデフォルト値らしいので、なくてもいいかなと。どうせコピペるものだから、あっても良いかもしれませんが。

なんか並ぶと良い感じ。

![](https://img.shields.io/badge/license-CC%20BY--SA%204.0-brightgreen.svg) ![](https://img.shields.io/badge/Commit%20message-Ja-brightgreen.svg) ![](https://img.shields.io/badge/code%20comment-Ja-brightgreen.svg) ![Policy](http://img.shields.io/badge/policy-Qithub%203原則-blue.svg)

```
![License](https://img.shields.io/badge/license-CC%20BY--SA%204.0-brightgreen.svg)
![Commit Msg](https://img.shields.io/badge/Commit%20message-Ja-brightgreen.svg)
![Code Cmnt](https://img.shields.io/badge/code%20comment-Ja-brightgreen.svg)
![Policy](http://img.shields.io/badge/policy-Qithub%203原則-blue.svg)
```

掲載が必須でない **（任意の）ものは特に色も決めなくていいですか**ね？CI 系のサービスが提供しているものは色指定できないものも多いし。 > @hidao80 @alice1017

**Comment by alice1017** [comment]
@KEINOS 

> 掲載が必須でない （任意の）ものは特に色も決めなくていいですかね？

良いんじゃないでしょうか。

ちなみに
![Document](https://img.shields.io/badge/document-Ja-brightgreen.svg)
も付け加えてはどうでしょう？

**Comment by KEINOS** [comment]
> ちなみに
> ![Document](https://img.shields.io/badge/document-Ja-brightgreen.svg)
> も付け加えてはどうでしょう？

README.md が１つであればいいのですが、"README_EN.md" や[混合しているドキュメント](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/Outline_Of_License.md)なども考えると、必須（緑-明）であるべきなのかしら。コミットやコメントは（明記を）必須にしているからドキュメントもすべき気もするし。

**Comment by KEINOS** [comment]
そうか。普通に併記すればいいのか。

![](https://img.shields.io/badge/document-Ja%20En-brightgreen.svg)

ドキュメントも、コメント・コミット同様必須に 👍

**Comment by hidao80** [comment]
👍

**Comment by hidao80** [comment]
アンダースコアをバッジ内に表示するには、半角アンダースコアを二つ続けるとよいようです。  
ハイフンも同様です。

![コミットは日本語で](https://img.shields.io/badge/commit_msg-ja__JP-brightgreen.svg)

```
![コミットは日本語で](https://img.shields.io/badge/commit_msg-ja__JP-brightgreen.svg)
```

**Comment by KEINOS** [comment]
これまでの内容をまとめ、TL;DR および [Wiki](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E5%90%84%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE-README.md-%E3%81%AB%E4%BD%BF%E3%81%86%E3%83%90%E3%83%83%E3%82%B8) に反映させました。

本リポジトリの README にバッジを掲載するマージで Close します/してください。
