### ISSUE TITLE
【提案・相談】WikiにあるQithub APIのIssueアーカイブをどうにかしたい

### ISSUE THREAD

**Issue by alice1017** [Qithub-BOT/Qithub-ORG#136]
## 提案・相談

- Wikiにある[Qithub API Issue アーカイブ](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Issue-list-of-Qithub-API)をどうにかしたいです。

## 問題点

- 現状、WikiのPagesのところに「147」と書かれてますよね、これ新参の方はビビると思うのです
- Wikiの全ページを見るときに「Show 132 more pages..」と出て、**2回クリック**する必要がある
- Pagesの最下部を見るために数回スクロールする必要がある

「目次みろや」という意見で問題点のふたつが解決するのは分かっていますが…('Д')

## 自分の案

- `docs` というディレクトリを作ってそこに移動させるのはどうでしょうか。
- アーカイブの個数が多いのでGithubAPIなどを使って移動できればいいのですが…

## TL;DR（進捗・結論 2018/09/14 現在）

- Issue アーカイブのみを Wiki から本リポジトリ（Qithub-ORG）に引っ越し決定 https://github.com/Qithub-BOT/Qithub-ORG/issues/136#issuecomment-421214551
- Issue の引っ越し PR 待ち

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue： 
    - #96 「Qithub-API（旧scripts）の issue 引っ越しは必要か」
    - #111 「Qithub-CMD の Wiki を Qithub-ORG に引っ越しました」
    - #119 「Wiki の目次の自動作成」

**Comment by hidao80** [comment]
@alice1017

> `docs`いうディレクトリを作ってそこに移動させるのはどうでしょうか。

これは、「リポジトリの中に Wiki として登録しているページをまるっとコピーする」という理解で合ってますか？
上記の理由なら賛成できません。

### 賛成できない理由

1. リポジトリにコード・ライセンス・PR 時のテンプレートおよび README や INSTALL 以外の大量のドキュメントを入れない方が良いのではないか
2. リポジトリに含めてしまうと**目次・索引を全ページ手作りする手間が増える**のではないか
3. **Wiki には PR の必要がない**ので、typo 等訂正対応が迅速に行われるのではないか

### 代案A

- 索引ページを作成し、トップページからリンクを貼る

### 補足

Wiki は Wiki のみ clone できるはずなので、レイアウトのことを言わなければ

1. Qithub-ORG を clone
2. Wiki を clone
3. Wiki の内容を Qithub-ORG の  docs 内にコピー
4. Qithub-ORG を PR

でいけるはずです。

P.S.
圧倒的な Wiki ページ数表記の解決にはなっていませんが、Wiki には Wiki 内のみの検索もあるので、文書管理に適していると考えています。

全ページリストを非表示にすれば威圧感が減ると思われますが、非表示にできましたっけ？ > @KEINOS

**Comment by KEINOS** [comment]
※ TL;DR → 関連 issue に #96 , #111, #119 を追記

---

> 「147」と書かれてますよね、これ新参の方はビビると思うのです  
> docs というディレクトリを作ってそこに移動させるのはどうでしょうか。 @alice1017

確かにビビりますよねぇ。

私は `「目次みろや」` を前提として Wiki の**旧リポジトリの `issue` のみ**を本リポジトリ内のディレクトリ下への**引っ越しに賛成**です。理由は以下。

## 理由

1. GitHub の Wiki をリポジトリとして操作すると挙動が不安定なため、技術的な理由から。
1. **ログであるため基本的に修正されるものではない**（ドキュメンターのメンテナンス対象から外すべき）
1. Wiki リポジトリをクローンし、ローカルで整理を行う際に対象ファイルが多すぎる。

### 1. 技術的な理由

実は２日くらいまえに [Wiki を少し整理して](https://github.com/Qithub-BOT/Qithub-ORG/wiki)いて気付いたのですが、**GitHub の Wiki はリポジトリではあれど、いささか Git の挙動がおかしい**のです。

特に GitHub の２段階認証を設定していると素直にコミットを Push できないのです。（ GitHub の Issue → https://github.com/desktop/desktop/issues/3839#issuecomment-420957438 ）

まぁ `git` コマンドを駆使すればなんとかなるのですが、何より旧 Issues ディレクトリに手を加えるだけで、ドバッと変更されるため、Wiki ではなく安定した Git 動作をする本リポジトリに移したいと先日感じました。

### 2. ログである ＆  3. メンテ対象ファイルが多すぎる

変更することがないとは言え、メンテしようと開いたらビジュアルで（私も）やられてしまいます。

『「Qithub のプロトコルを勉強しよう」と背表紙を見たら分厚かった』という状態です。でも、実はほとんどが、巻末の参考資料という。

そのため、別冊気分で `docs/archive/` にアーカイブするのが良いと思います。

## アーカイブの引っ越しについて

> アーカイブの個数が多いのでGithubAPIなどを使って移動できればいいのですが… @alice1017 

これは簡単だと思います。ローカルで Wiki のリポジトリから Qithub-ORG のリポジトリへコピーして、コミット＆プッシュすればいいだけだと思います。

## 引っ越しによる弊害

> リポジトリに含めてしまうと目次・索引を全ページ手作りする手間が増えるのではないか @hidao80 

これは大丈夫だと思います。スクリプトで動的に目次・索引を作成できるので。

今後は Wiki に更新があったら（Qiita墓場のリポジトリ更新機能を応用して）自動的に目次・索引を作成スクリプトを叩くようにしたいので、Wiki は以下のようにあればいいなと思います。

1. ニューカマー（新時代のオカマではありません）のための導入マニュアルとして機能している。
1. プロトコル定義書および機能の仕様書として機能している。
1. 動的に変わる可能性のあるドキュメントで即時性が求められるものに絞る。
1.  PR なしに自由に追加・編集できる。
1. 目次・索引からも入れ、Wiki の検索からも入れる。

以上から、 `issue` のアーカイブは引っ越してもいいと思います。

 ### Wikiページの総数非表示

> 全ページリストを非表示にすれば威圧感が減ると思われますが、非表示にできましたっけ？ @hidao80 

実は、初回の Issue 引っ越し時に @alice1017 さんと同じ懸念を一瞬持って探したのですが、[**できない**らしい](https://stackoverflow.com/questions/9239588/toc-or-sidebar-in-github-wiki)ので、むしろ、そこから右サイドバーの設置をはじめ、面倒臭いから[自動化スクリプトを設置した](https://github.com/Qithub-BOT/Qithub-ORG/issues/119)と言っていいかもしれません。

**Comment by hidao80** [comment]
なるほど、旧 issues が確かに膨大ですし、歴史的価値はあっても資料的価値は低減していそうですね。

Issues のみをリポジトリに移動させるに👍

**Comment by KEINOS** [comment]
> 歴史的価値はあっても資料的価値は低減していそう @hidao80 

歴史的価値、確かに。Wiki は全員が積極的に触って行きましょう！

@alice1017 @hidao80 

👍 では**引っ越し決定**にしたいと思います。（→ TL;DR 済み）

引っ越し（本ジポジトリにアーカイブ設置）後の PR で Close させたいと思います。

**Comment by hidao80** [comment]
👍

**Comment by alice1017** [comment]
ありがとうございます！👍
