### ISSUE TITLE
【許可申請】アクセストークン：QiiTime

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#141]
Issue #128 および Wiki の「[アクセストークンについて](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)」より申請

## 申請内容

QiiTime のトゥートに Qiitadon の QiiTime アカウントのアクセストークンが必要なため、`gettoken` シェルコマンドで取得いたします。下記ディレクトリからのアクセス許可を願います。

```
/api/v1/qiitime
```

## TL;DR（結論 2018/09/24 現在）

👍 ２つ以上で許可。許可後、`gettoken` 利用可能ディレクトリに上記パスを追記したら Close。

- 2018/09/19 クローズ済み

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue #128 「アクセス・トークンが外部コマンドから取得できるようにしました」

**Comment by hidao80** [comment]
👍

**Comment by alice1017** [comment]
遅ればせながら👍
