### ISSUE TITLE
【報告】Typo報告

### ISSUE THREAD

**Issue by alice1017** [Qithub-BOT/Qithub-ORG#145]
## Typo報告

`/api/v1/.lib/php/tootlib.php.inc`内の `toot` 関数のコードで、 **schemaが`schama`になってます**
https://github.com/Qithub-BOT/Qithub-ORG/blob/a29b98fed1fa316dd52e3ffee50adb4f5f7eb74c/api/v1/.lib/php/tootlib.php.inc#L335

`/api/v1/qiitime/index.php`の方ではちゃんと **schema** になってます
https://github.com/Qithub-BOT/Qithub-ORG/blob/4559da4355269ce435c3f6bd3a84c1e440f77cc6/api/v1/qiitime/index.php#L81

## TL;DR（進捗・結論 2018/9/19 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
@alice1017 

スチャマーw

そうかキー名の場合は Typo 検知してくれんのか。まぁそうだよね。残念！
あざっす！修正アップし 💪
