### ISSUE TITLE
issue をクローズしていい時の意思表示方法

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#15]
「ok」または「OK」のみのコメントをしたプロジェクトメンバーは、当該 issue に対してこれ以上コメントはない、クローズしてよいという意思表示にしませんか？

延々返信待ちで「クローズしてもいいですか？」が最後のコメントとしてぶら下がったままオープンされている issue はプロジェクトマネジメント or issue 管理上よろしくないと考えます。

もちろん、「クローズしてください」というニュアンスの分が含まれたコメントもクローズ許可フラグとしてみることとします。

**Comment by KEINOS** [comment]
OKよりは 👍 の方がやさしくて好きです。

**Comment by hidao80** [comment]
なるほど、流石に味気なさ過ぎましたね。（汗

では、 :thumbsup: のみのコメントをした方は「意義なし！クローズしてよし！」と思ってことにしましょう。

試しに次のコメントを待ってみる。

**Comment by KEINOS** [comment]
👍

**Comment by hidao80** [comment]
いままでコメントで:thumbsup:することで「意義なし！クローズしてよし！」ということにしていましたが、コメントに対するリアクションとして「:thumbsup:」や「:smiley:」が使えることがわかりました。（投稿したコメントの編集ボタンの隣、「+:smiley:」ボタンより。）

以降、ここで「:thumbsup:したときも『意義なし！クローズしてよし！』」としませんか？

**Comment by KEINOS** [comment]
👍  こういうことですね？
↓
<kbd><img width="603" alt="2017-10-01 18 47 31" src="https://user-images.githubusercontent.com/11840938/31053519-fd60bf32-a6d9-11e7-9286-ed0aab92b5c7.png"></kbd>

**Comment by hidao80** [comment]
:thumbsup:

その通りです！

**Comment by KEINOS** [comment]
御意に
