### ISSUE TITLE
【報告】Webサーバー不要のローカル・チェック環境用意しました（macOS用）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#150]
## 報告

**トゥート BOT の雛形を用意**しました。

また、`dev` という、**PHP のビルトインサーバを空きポートで動かす Web サーバーのランチャー・スクリプト**も同梱しています。

現在は、まだ macOS 専用ですが、追加インストールなくデフォルトで使えるようになっています。ローカル開発にご利用ください。

具体的にはターミナルから以下のように使います。

```shellsession
$ # ローカルの Clone 先の API ディレクトリへ移動（ cd Qithub-ORG/api/v1/ ）
$ cd /path/to/git/cloned/dir/of/Qithub-ORG/api/v1/
$
$ # 開発ディレクトリの作成（サンプルをコピーして利用）
$ cp -r .sample myApp
$ cd myApp
$ ls
README.md	dev		index.php
$
$ # 自分の検証用 Mastodon アクセストークンをセットする（置換）
sed -i -e "s/XXXXX..XXX/<your access token>/g" index.php
$
$ # Webサーバーのランチャーに実行権限を与える
$ chmod +x dev
$ 
$ # Webサーバーとブラウザ起動
$ ./dev safari index.php
$
$ # Web サーバーとブラウザとブラウザが起動し`index.php`が実行され "Hello world" がトゥートされます。
$ # 以降は任意のエディタでスクリプトを修正し、ブラウザをリロードの繰り返で開発します。
$ # サーバーの停止は `control + c`
```

とすると、設定したアクセストークンのアカウントで "Hello world" が  "`unlisted`" でトゥートされます。

- [`dev` ](https://github.com/Qithub-BOT/Qithub-ORG/blob/4559da4355269ce435c3f6bd3a84c1e440f77cc6/api/v1/.sample/dev) は [PHP ライブラリ](https://github.com/Qithub-BOT/Qithub-ORG/tree/master/api/v1/.lib/php)内にある「[`developServer.php.inc`](https://github.com/Qithub-BOT/Qithub-ORG/blob/4559da4355269ce435c3f6bd3a84c1e440f77cc6/api/v1/.lib/php/developServer.php.inc)」を include している PHP スクリプトです。
- `dev` の第１引数は、起動するブラウザの指定で、（ローカルにインストールされていれば）"chrome", "safari", "firefox", "opera" が指定できます。
- `dev` の第２引数はオプションで、ルートとなるファイルです。指定がない場合は `index.php` が使われます。
- 検証用の Mastodon のアクセストークンは Qiitadon の [設定]-[</>開発]-「新規アプリ」から作成可能です。

Happy Qithub life!

## TL;DR（結論 2018/09/20 現在）

- 確認済み

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
👍

**Comment by alice1017** [comment]
👍

**Comment by KEINOS** [comment]
🎉 < TL;DR済み & close
