### ISSUE TITLE
【質問・提案】Qiita-SPAMSのアーカイブ収集の件について

### ISSUE THREAD

**Issue by alice1017** [Qithub-BOT/Qithub-ORG#151]
## 質問・提案

Qiita-SPAMSのアーカイブ収集の件で質問と提案があります。

### 質問

リポジトリの[README](https://github.com/Qithub-BOT/Qiita-SPAMS#%E3%83%87%E3%83%BC%E3%82%BF%E5%BD%A2%E5%BC%8F)には
>データ形式
>>Markdown 形式のテキスト・ファイルを RSA 暗号化したバイナリ  
>
>内容自体がスパムであるため Google 八分を受けないように、Markdown 形式のテキストを Qithub の RSA 秘密鍵で暗号化しています。

と、書かれていますが、これは **Qiita記事をMarkdownに変換** して暗号化するという意味で間違いないでしょうか？

### 提案①

Markdownに変換するのではなく、**記事の中身をそのまま `txt` ファイルとして保存**するのはどうでしょう？

Qiita記事をMarkdownに変換する場合、
```
Qiita記事のHTMLを取得→HTMLをスクレイピング→記事の中身を抽出→Markdownに変換して保存→暗号化
```
という5段階のワークフローになると思います。

記事の中身をtxtファイルとして保存する場合は、
```
Qiita記事のHTMLを取得→HTMLをスクレイピング→記事の中身を抽出して保存→暗号化
```
この4段階のワークフローになります。
たった1段階減っただけですが、こちらの方がシンプルで簡略化できると思います。
どうでしょか。

### 提案②

スクレイピングはPythonの得意分野なので、Qiita記事を取得してから記事の中身を抽出して保存するまでのスクリプトをPythonで書かせてもらいたいですのですが、どうでしょうか。

## TL;DR（結論 2018/9/21 現在）

- データの取得はスクレイピングでなく QiitaAPI より取得
- リポジトリに保存するデータは Markdown でなく QiitaAPI から取得した JSON テキスト

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
> **Qiita記事をMarkdownに変換** して暗号化するという意味で間違いないでしょうか？ @alice1017 

実は、変換はいたしませんのです。

https://qiita.com/api/v2/items
↑この API を叩くと、なんと HTML と Markdown の両方で記事の情報が JSON で取得できます。

それをそのまま `<記事ID>.json` としてキャッシュ保存し、後日スパムと判断した場合は Qithub.tk サーバーに clone された `Qithub-SPAMS` のディレクトリに JSON ファイルを移動します。

その際に（Google八分をさけるため）秘密鍵で暗号化して `Qithub-SPAMS` に移動します。

移動後、 @alice1017 さんのリポジトリ同期スクリプトを叩いて GitHub に Push してもらう。そういった意外にシンプルな流れです。

なので、スクリプトの引数で指定されたディレクトリに `.git` があったら、ディレクトリ内の新規追加を `add` して  `origin` に Push してもらえるシンプルなスクリプトだと、他の用途にも使えて助かります。

**Comment by alice1017** [comment]
@KEINOS 

なるほど！！よく理解できました 👍 
ではGitを操作するスクリプトの開発を続けていきますね！
ありがとうございました。

**Comment by KEINOS** [comment]
@alice1017 

アチキの方のスクリプトも多機能になりすぎたら機能をわけようと思うので、その時はよろぴくお願いします！

**Comment by KEINOS** [comment]
@alice1017 @hidao80 

TL;DR 更新しました。また、確かに [README](https://github.com/Qithub-BOT/Qiita-SPAMS#%E3%83%87%E3%83%BC%E3%82%BF%E5%BD%A2%E5%BC%8F) の記述は Markdown と誤解を招く嘘を付いているので修正 PR をあげて、卍 & 本件 Close で良いと思いますがいかがでしょう？

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
リポジトリを超えてもマージ時のコメントに "`Close <URL issue>`" すると、自動クローズされるのね。

これ、同じ Organization だから機能するのかしら。
