### ISSUE TITLE
【相談】Qiita-SPAMSのアーカイブのデータ形式について

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#152]
## 相談

> Qiita-SPAMS の保存データは以下の情報のみのプレーンな JSON テキストで良いのではないか

- ファイル名： `<YYYY_mm_dd>.json` （投稿された日）
- ファイルの内容（JSON配列）：
    １要素１記事
    ```json
    [
        {
            "id_item": "<記事ID>",
            "id_user": "<ユーザID>",
            "url_cache": "<Qithub のキャッシュURL>",
            "url_raw": "<本家 Qiita API のURL>",
            "date_post": "<投稿日>"
        },
        {
            "id_item": "<記事ID>",
            "id_user": "<ユーザID>",
            "url_cache": "<Qithub のキャッシュURL>",
            "url_raw": "<本家 Qiita API のURL>",
            "date_post": "<投稿日>"
        },
        {
            //以下同文
        }
    ]
    ```

## 詳細

Issue #151 「Qiita-SPAMSのアーカイブ収集の件について」と Issue https://github.com/Qithub-BOT/Qithub-ORG/issues/130#issuecomment-423122460 「Qiita 記事墓場のリポジトリ設置」のコメントで思ったのですが、本家の API を叩けばスパム記事のコンテンツ・データは取得できるので、**Qiita のスパム記事の ID とスパムユーザーの ID があれば十分なのではないか**、と。

Qithub.tk のサーバー側でキャッシュしておいて URL（"url_cache"） を叩けば取得できるようにしておけば、よしんば Qiita 側（上記 JSON 要素の "url_raw"）が削除されたとしても、魚拓（キャッシュから取得）にもなるし。

### メリット

- 復号する必要がない
- 取り扱いが楽

### デメリット

- リポジトリの Clone だけで完結できない
    ID 情報のみなのでスパム記事のコンテンツは別途 Qithub/Qiita API なりで取得する必要がある

## TL;DR（**結論** 2018/11/02 現在）

- Qiita-SPAMS リポジトリにアーカイブするデータ
    - JSON 形式のプレーンテキスト（暗号化しない）
    - フォーマットは下記参照
- Qiita-SPAMS に保存される JSON  ファイルは以下の通り
    - `<記事ID>.json` として 1 記事 1 ファイル
    - JSON ファイル（索引 JSON）のフォーマット
    ```json
    {
        "id_item": "<記事ID>",
        "id_user": "<ユーザID>",
        "url_cache": "<Qithub のキャッシュURL>",
        "url_raw": "<本家 Qiita API のURL>",
        "date_post": "<投稿日"
    }
    ```
    - （ https://github.com/Qithub-BOT/Qithub-ORG/issues/152#issuecomment-429625277 より https://github.com/Qithub-BOT/Qithub-ORG/issues/152#issuecomment-435249421 で制定）
- 新着Qiita記事の機能を下記３つの機能にわけて API としてリリース速度を早める
    1. 新着Qiita記事
    2. 生JSONの魚拓
    3. スパム検知 & cloned Qiita-SPAMS リポジトリに追加 & commit-push スクリプト実行
- QiiTime の API は下記
    - エンドポイント： https://qithub.tk/api/v1/qiitime/
    - リポジトリ： Qithub-ORG @ https://github.com/Qithub-BOT/Qithub-ORG/api/v1/qiitime/

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 Issue
    - #130 「Qiita 記事墓場のリポジトリ設置」
    - #151 「Qiita-SPAMSのアーカイブ収集の件について」

**Comment by hidao80** [comment]
Qithub-SPAMS の README が更新されていないことも相まっていまいち状況が把握できないのですが、以下の理解で合ってますか？

1. 魚拓をリポジトリに含めない
2. スパムの存在情報を日別の json ファイルにまとめる

と仮定すると、 url_cache が何の url なのかが分かりません。

教えてちょんまげ…

**Comment by KEINOS** [comment]
@hidao80 

> 1. 魚拓をリポジトリに含めない
> 2. スパムの存在情報を日別の json ファイルにまとめる

合っています。**コンテンツ本文の魚拓は含みません**。

> url_cache が何の url なのかが分かりません。

失礼しました。多く語れど、言葉足らずでした。

`url_cache` は、まだ存在していない Qithub のエンドポイントで、**Qiita 記事のコンテンツ本体の JSON のキャッシュを返す**だけの API の URL です。

現在、「新着 Qiita 記事のトゥート BOT 」（新着Qiita記事の API）には、新着のトゥート以外に「記事のキャッシュ」や「スパムの判断」処理も含めてしまっており、いささか煩雑になってきています。

そこで、シンプルな機能別にわけたいと整理しているので **`url_cache` の要素はまだ確定ではありません**。

本 issue で議論したいのが、 `url_cache` の要素を含める/含めないは別として、**コンテンツ本体を含めない**ことで、暗号化の必要もなくなるし、開発が楽になるので、早くリリースできるかな、と。

### `url_cache` について

イメージとして、下記（仮）URL を叩くと Qithub.tk のサーバーにキャッシュされた JSON が返されるだけの API です。

`https://qithub.tk/api/v1/qiita-cache/?id=xxxxxxxxxxxxx`（エンドポイント名は仮。xxx..は記事ID）

上記リクエストを受けると、キャッシュされていればキャッシュの JSON を返し、キャッシュされていない場合は Qiita の API を叩いてコンテンツをサーバーのローカルにキャッシュして JSON を返すだけのものです。**この機能を新着 Qiita 記事の BOT からわけたい**のです。

これにより、Qiitadon のスパム対策活動において、ユーザーが `Qiita-SPAMS` repo から得たスパム記事 ID を取得する際に、本家 Qiita API のアクセス負荷をあげないという、負荷分散の目的があります。

また、同時に魚拓として機能するので、本家で削除されたとしても記事 ID さえわかれば（キャッシュされていれば）コンテンツを取得できるようになります。

**Comment by KEINOS** [comment]
本文をわかりやすいように修正しました。原文は「`edited`」の "Created"、変更内容は次項の "Edited" より。
<kbd>![qiita spams issue 152 qithub bot qithub org](https://user-images.githubusercontent.com/11840938/45987192-20617a80-c0ab-11e8-9dad-d03739aa7ca3.png)</kbd>

**Comment by hidao80** [comment]
用向きはわかりましたが、データの居所とデータを管理するプロジェクト（リポジトリ）がイマイチわからないのでもう少し確認させてください。

1. 魚拓HTML or Markdown（≠Qiita生データJSON）は qithub.tk サーバに蓄えられて、GitHub 上には保存しない？
2. qithub.tk には「Qiita生データJSON」と「Qiita-SPAMSの保存データ日別索引JSON」の2種類のJSONが蓄えられる？
3. Qithub-BOT とは別の「qiita-cache」リポジトリが発足しそう？
   - Qithub-CMD の1機能として実装される？
4. qithub.tk にキャッシュがない場合に「qiita-cache」のエントリポイントにアクセスした時の挙動は
    1. qithub.tk に「Qiita生データJSON」をコピーする
    2. qithub.tk の「Qiita-SPAMSの保存データ日別索引JSON」にレコードを追記する
    3. qithub.tk に先ほどコピーされた「Qiita生データJASON」を返す

で合ってます？

**Comment by KEINOS** [comment]
> データの居所とデータを管理するプロジェクト（リポジトリ）がイマイチわからないのでもう少し確認させて @hidao80 

もちろん！身内でもイマイチンわからんちんと言うことは、他の方にはなおさらだと思うので、どんどん明確化して行きましょう！

いささか長く、若干、ご存知のことも含まれていると思いますが、共通認識の確認の意味も含めて重複してしまうことをお許しください。

### 魚拓に関して

<details><summary><blockquote> 1. 魚拓 HTML or Markdown（≠Qiita生データJSON）は qithub.tk サーバに蓄えられて、GitHub 上には保存しない？</blockquote></summary>

はい。魚拓データは GitHub 上に保存（公開）しません。（決定ではない）

あくまでも、**Qiita API のプロクシ的な感じでローカルにキャッシュさせておくだけ**のもので、JSON のフォーマットも同じでいいと考えています。

また、Web サーバに蓄えられる「魚拓 HTML or Markdown」は「Qiita 生 JSON データ」です。つまり、「魚拓データ＝生JSON」です。

と言うのも、Qiita の API からの JSON には **HTML と Markdown の両方のデータも含まれている**ので、特別な加工せずとも、生 JSON をそのまま「隠し（ドット付き）ディレクトリ」に保存してで良いと考えています。これが魚拓データ（キャッシュ・データ）になります。

</details>

### 保存データに関して

<details><summary><blockquote>2. qithub.tk には「Qiita 生データ JSON」と「Qiita-SPAMSの保存データ日別索引JSON」の2種類のJSONが蓄えられる？</blockquote></summary>

はい。本体も含めた「Qiita 生 JSON」と、頭だけの「索引 JSON」の２つです。「索引 JSON」というのは良い例えだと思います。まさにその役割です。

ただ、注意点として「Qiita-SPAMS の保存データ日別索引 JSON」 は qithub.tk のサーバーに `clone` された「Qiita-SPAMS」のリポジトリのディレクトリの中に保存されます。（設置先は未定）

</details>

### 保存先（リポジトリ）について

<details><summary><blockquote>3-1. Qithub-BOT とは別の「qiita-cache」リポジトリが発足しそう？</blockquote></summary>

いいえ。（Qithub-BOT でなく Qithub-ORG のことですよね？）

仮に魚拓サービスの API を（作ってしまいましたが）やるとして、エンドポイントとサーバーでの保存先は、以下のようなイメージになると思います。

- エンドポイント： `https://qithub.tk/api/v1/qiita-cache/`
- API 本体：`/api/v1/qiita-cache/index.php` @ Qithub-ORG repo
- データ保存先：`/api/v1/qiita-cache/.data/` @ Qithub-ORG repo

つまり、[QiiTime](https://qithub.tk/api/v1/qiitime/) と同じ JSON を返すだけのエンドポイントです。

qithub.tk の Web サーバーの `DocumentRoot` は `clone` された「Qiita-ORG」リポジトリであるため、魚拓データは「Qiita-ORG」リポジトリのディレクトリの中に保存されることになります。

そして、データは上記の通りドット付きディレクトリであるため Web からのアクセス不可となります。また qithub.tk 内で生成されたデータやファイルは GitHub には同期されません。

（「Qiita-SPAMS」リポジトリと異なり、`https://qithub.tk/` の本体である「Qiita-ORG」リポジトリは Origin（GitHub側）に Push することを前提としていません。[`.gitignore` にあるデータ](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/.gitignore)以外は[強制上書きする仕様](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/.template/clone_repo.php#L152-L153)になっています。）

</details>

### 機能について

<details><summary><blockquote>3-2. Qithub-CMD の 1 機能として実装される？</blockquote></summary>

いいえ。**QiiTime と同じ単発機能の API** です。

QiiTime は、条件によってトゥートしたりキャッシュを行いますが、メインは JSON を返すだけの API です。これを [qithub.tk の `cron`](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/tools/cron/hourly.sh) で叩いて、条件を発動させて BOT に見せかけています。

**新着 Qiita 記事のトゥート BOT も同じ**で、基本はトゥート済みの新着 Qiita 記事をJSON で返すだけの API なのですが、条件によって新着を取得したりトゥートしたりします。そして、同じ様に `cron` で叩かれて条件が発動するようになっています。

新着の Qiita 記事を取得する際に、もったいないと、キャッシュしたりスパムを判断したりと、１石（１リクエスト）であれこれしようとして、開発が遅れています。

そこで、新着 Qiita 記事のトゥート BOTの**機能を以下のように目的別に分けたい**のは、機能をシンプルにして早くリリースしたいな、というのが全体的な狙いです。

- **Qiita新着記事 API**
    叩くとトゥート済みの新着 Qiita 記事 n 件の JSON を返す。（オプション：新着記事をトゥート）
- **魚拓 API**
   叩くと指定された Qiita 記事の魚拓 JSON を返す。（オプション：未キャッシュの場合キャッシュ）
- **スパム墓場 API**
   叩くとスパム認定済みの Qiita 記事 n 件の JSON を返す。記事 ID の指定があった場合は、スパム判定を行う。（オプション：リポジトリの ADD & PUSH コマンド呼び出し）

※ 上記の「オプション」は条件が揃うと発動する機能です。
※ 魚拓の 生 JSON を機械学習など「別のスクリプトからローカル・アクセスで使いたい」「アーカイブでダウンロードしたい」などは別途。

</details>

### `qiita-cache` を叩いた場合の挙動

<details><summary><blockquote><p>4. qithub.tk にキャッシュがない場合に「qiita-cache」のエントリポイントにアクセスした時の挙動は</p>
<ol>
    <li>qithub.tk に「Qiita生データJSON」をコピーする</li>
    <li>qithub.tk の「Qiita-SPAMSの保存データ日別索引JSON」にレコードを追記する</li>
    <li>qithub.tk に先ほどコピーされた「Qiita生データJASON」を返す</li>
</ol>
</blockquote></summary>

いいえ。1 と 3 のみで、SPAMS の判定は行いません。

あくまでも JSON の魚拓のみで、SPAM 判定と索引 JSON の作成＆リポジトリ操作は、別の専用の API にしたいと考えています。

</details>

### Where is Qithub-BOT?

なお、本来の意味の Qithub-BOT。つまり、トゥートから BOT のコマンドを実行できる機能は、今回の件にはまったく関与していません。 😭 

このコマンド BOT は `cron` で叩いて発動するのではなく、[Qiitadon のストリーミング API](https://qiita.com/KEINOS/items/75febc1d5391ae5c7bd9) を監視させる常駐サービスを作って、反応させる方向で考えています。

**Comment by hidao80** [comment]
👍  なるほどです。

ところで、QiiTime のリポジトリって GitHub 上に存在してます？ どこかわからない…
なければないでいいのですが。

**Comment by KEINOS** [comment]
Qithub-ORG にいまーす

https://github.com/Qithub-BOT/Qithub-ORG/tree/master/api/v1/qiitime

**Comment by hidao80** [comment]
了解です！ 👍

**Comment by alice1017** [comment]
👍

**Comment by KEINOS** [comment]
@alice1017 @hidao80 

あざっす。TL;DR 更新したので Close し 💪

**Comment by KEINOS** [comment]
日付の階層だと不都合があったため、再オープン。仕様変更をキボンヌ。 > @hidao80 @alice1017 

### 提案

1. スパム保存時、日付ベースでなく ID の最初の頭文字ベースでディレクトリ分けしたい
2. ファイル名は Qiita記事ID にしたい。

#### 提案前
```
/.spams/2018_10_14.json
```
#### 提案後

```
/.spams/a/abcd123456.json
```

### 理由

[ブランチで作成中の魚拓 API](https://github.com/Qithub-BOT/Qithub-ORG/tree/KEINOS-Qiita-Cache-API_20180925) とスパム検知の挙動をローカルでテストしていて気づいたのですが、日付をベースにしたディレクトリ構造でスパムの索引 JSON データを保存する場合、**ピンポイントで特定のスパム情報を拾う場合にディレクトリとファイルの探索が必要**になります。

そのため、Qiita記事ID の最初の１文字目をディレクトリ名として、そこに Qiita記事ID 名で索引 JSON を保存したいです。

例） abcd1234567 の Qiita 記事 ID の場合

```
/.spams/a/abcd1234567.json
```

### デメリット

「いつごろ、どれだけのスパムがあったのか」を GitHub （Qiita-SPAMS のリポリトリ）上からは、**目視**で把握しづらくなる。

### メリット

- 特定 ID での検索が速くなる
- 索引 JSON （保存されたデータ）に作成日は含まれているため、DB 処理を行う場合に速度差はない
- ファイルが日付から個別にわかれるためコンフリクトが発生しづらくなる

**Comment by hidao80** [comment]
???

`<日付>.json`って、いわゆる「索引 JSON」では？ それを記事 ID で管理するということは、「索引 JSON 1個に対して一つの記事しか入れない」ということなのでしょうか？

私が何か勘違いしてますか？？？

**Comment by KEINOS** [comment]
> 「索引 JSON 1個に対して一つの索引しか入れない」 @hidao80 

そうでやんす。

`<日付>.json` だと、その日に発生したスパムをまとめて記載できるのですが、**ID ごとに索引データを個別にしたい**のです。

ファイル数は増えるのですが、日付ごとにまとめるメリットより、ID ごとに分けた場合のメリットの方が多いためです。

機械学習で利用する場合にしても、結局ループで１ファイルにしてから処理を行うのが定番のため、日付別のファイルは、見た目の整頓やアナログ検索にしかメリットがなく、機能の実装面で個別にした方が都合が良いのであります。

**Comment by hidao80** [comment]
> `<日付>.json` だと、その日に発生したスパムをまとめて記載できるのですが、**ID ごとに索引データを個別にしたい**のです。
> 
> ファイル数は増えるのですが、日付ごとにまとめるメリットより、ID ごとに分けた場合のメリットの方が多いためです。

上記理由ならば、「頭文字をフォルダ名にする」仕様が不要だと思われますが、この仕様にはどのようなメリットがありますか？

**Comment by KEINOS** [comment]
> 上記理由ならば、「頭文字をフォルダ名にする」仕様が不要だと思われますが、この仕様にはどのようなメリットがありますか？ @hidao80 

１階層にファイルが多すぎて `ls` した時に処理が戻ってきませんでした。。。

https://github.com/yyano/Qiita-News から過去の Qiita 記事 ID 一覧をループでローカルの魚拓 API を叩かせ魚拓を取ってみたのですが、`ls` して確認すると「処理落ちしてるのか？」という感じです。（ちなみに、初回の魚拓時に 404 の記事はスパムとして別途保存しています）

この時、検証で ID を探そうとした時に、ファイル名でなく中身を検索しないとならず、とても面倒なんです。

まぁ「DB 使えよ」という話しなのですが、バイナリなので Git には向かないということで。

**Comment by hidao80** [comment]
sqlite3 の db ファイルをリポジトリに突っ込むのは NG？

自動生成されたファイルを差分をとりながら編集することはないと考えるのですが。

**Comment by hidao80** [comment]
それなら頭文字ディレクトリは効果がありそうですね（36 分割できる）。

この仕様がよさそうです。
https://github.com/Qithub-BOT/Qithub-ORG/issues/152#issuecomment-429625277 を支持します。

**Comment by KEINOS** [comment]
> sqlite3 の db ファイルをリポジトリに突っ込むのは NG？ @hidao80 

サーバー上で処理するぶんには SQLite3 でも良いと思うのですが、DB とテキスト・ファイルの２つの実装を併用すると、内部的に煩雑になってしまう **（面倒）というのが一番の理由**ですが、上記仕様（記事IDがファイル名）の場合、**特定 ID の検索は SQLite3 より速く処理できます**。（ピンポイントでファイルを開くだけなので）

途中で止めてしまったため Qiita 記事の総容量は未知数ですが、以前ローカルの Gitea で **Wikipedia の分かち書きデータの SQLite データを突っ込んだらコンフリクトが結構な頻度で起きた**ので、回避策として、すごいマメにコミットしないといけなく、そのたびに処理が重くなったり、`.git` ディレクトリの容量が肥大化していくので、「返って面倒だな」という（１回きりの）苦い経験もあります。

また、機械学習用のコーパスはテキストや個別ファイルの方が扱いやすいそうです。

**Comment by hidao80** [comment]
> 途中で止めてしまったため Qiita 記事の総容量は未知数ですが、以前ローカルの Gitea で **Wikipedia の分かち書きデータの SQLite データを突っ込んだらコンフリクトが結構な頻度で起きた**ので、回避策として、すごいマメにコミットしないといけなく、そのたびに処理が重くなったり、`.git` ディレクトリの容量が肥大化していくので、「返って面倒だな」という（１回きりの）苦い経験もあります。
> 
> また、機会学習用のコーパスはテキストや個別ファイルの方が扱いやすいそうです。

なるほど…そういう理由もあるのですね。

ならば、「1索引に1記事」がベターなようですね。とりあえずこれで進めておいて、良い方法がひらめいたらその時軌道修正しましょう。

まずは、ver.1 をリリースするのを直近の目標にしたいですね。

**Comment by KEINOS** [comment]
変更の多いバイナリには Git は向かないというのを実感した件でした。

ライナスさんが Linux メンテナを休んでしばらく Git に注力する的な発言があったみたいですが、ここらへんを改善するのかもですね。

> まずは、ver.1 をリリースするのを直近の目標にしたいですね。 @hidao80 

そうですね！ @alice1017 さんの（おてすきに）意見を聞いて、マージの動作確認が取れたら Close いたし 💪

**Comment by alice1017** [comment]
やっとissue読破できました！反応が遅くてすみませんでした…
僕もKEINOSさんの方法を支持します。 👍

**Comment by KEINOS** [comment]
@alice1017 @hidao80 

あざっす！ TL;DR 更新しましたー
ので、Close しまーす
