### ISSUE TITLE
【許可申請】アクセストークン：Qiita-items（新着Qiita記事トゥート）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#153]
Issue #128 および Wiki の「[アクセストークンについて](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)」より申請

## 申請内容

新着Qiita記事のトゥートにアクセストークンが必要なため、`gettoken` シェルコマンドで取得いたします。下記ディレクトリからのアクセス許可を願います。

```
/api/v1/qiita-items
```

利用するトークンは `$ gettoken qiitadon qithub`（本番） および `$ gettoken qiitadon qithub-dev` （開発）です。

## TL;DR（結論 2018/09/25 現在）

- 👍 ２つ以上で許可。 → https://github.com/Qithub-BOT/Qithub-ORG/issues/153#issuecomment-424182427 にて可決
- 許可後、サーバーの `gettoken` 利用可能ディレクトリ一覧に上記パスを追記したら Close。 → https://github.com/Qithub-BOT/Qithub-ORG/issues/153#issuecomment-424202179 にて Close

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue #128 「アクセス・トークンが外部コマンドから取得できるようにしました」

**Comment by hidao80** [comment]
👍

**Comment by alice1017** [comment]
新着Qiita記事のトゥートってどのアカウントで行うんですか？

**Comment by KEINOS** [comment]
> 新着Qiita記事のトゥートってどのアカウント @alice1017 

おぉう。失礼しました！以下になります。

### 新着Qiita記事をトゥートするアカウント

- 本番： https://qiitadon.com/@qithub
- 開発： https://qiitadon.com/@KEINOS_BOT

ちなみに、QiiTime の時報トゥートに対して、上記アカウントが新着を返信するようにしています。

アカウントを分けている理由は下記 旧 Issue によるものです。

- [旧 Qithub-API Issue #92 「新着Qiita記事 ハッシュタグ検索が機能しない件について」](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/docs/archives/issues-Qithub-API/Qithub-API%20Issue%2092.md) @ アーカイブ

問題なければ 👍 お願いします。疑問点があれば、お気軽にドゥぞー

**Comment by alice1017** [comment]
ありがとうございます 👍

**Comment by KEINOS** [comment]
サーバーの `gettoken` シェル・コマンド利用可能ディレクトリ一覧に上記パスを追記しました。

ので、TL;RD 更新 & close し 💪
