### ISSUE TITLE
【提案】ＰＲのルールに追加したい事項があります

### ISSUE THREAD

**Issue by alice1017** [Qithub-BOT/Qithub-ORG#157]
## 提案

PRするときのルール( [CONTRIBUTING.md](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/.github/CONTRIBUTING.md) ,  [wiki](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%80%81PR%E3%80%81%E3%83%9E%E3%83%BC%E3%82%B8%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB) )に以下の項目を追加したいです。

- ユーザーが立てたPRに、**別ユーザーが勝手にコミットするのは禁止**

## 補足

今まで何度か、メンテナが立てたプルリクエストに**別のメンテナが勝手にコミット**する場面がありました。  （PR #154 や PR #125 など）

### 問題点

- PRに勝手に追加コミットすると、PRを立てたユーザーの意志（修正したい内容など）を阻害してしまう可能性がある
- PRを立てたユーザーが修正したかった内容を、別のユーザーが勝手にコミットしてユーザーが修正したかった内容を別のものに改変してしまうのは良くないと思いました

### 対策

- ユーザーが立てたPRに「よくない点」や「もっとこうした方がいい点」があれば、そのPRに勝手にコミットするのではなく、**PRにコメント**するなり**issueを立てる**なりして**PRを立てたユーザーに許可を取って**からコミットした方が良いと思います。 

## TL;DR（進捗・結論 2018/9/27 現在）

- PRへの別ユーザーによるコミットは、PRを立てたユーザーの許可を取ってから行う。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
> **別のメンテナが勝手にコミット**する場面がありました。 （PR #154 や PR #125 など） @alice1017 

どれもアチキですね。 😖

[Qiita コラボ記事](https://github.com/Qithub-BOT/Qiita-items) の Wikipedia スタイルを引きずっていました。

PR コメントで言うだけ言って PR した本人に作業させるのに抵抗があったのもありますが、「`PRを立てたユーザーに許可を取ってからコミットした方が良い`」に集約されていると思います。反省。

> PR を立てたユーザーに許可を取ってからコミットした方が良い

☝️  このルールを設けないと、今後、**勉強のためにあげた PR も勝手に修正（結果だけ提示）され勉強にならない**可能性もあることに気づきました。

なので、新規制定に 👍

**Comment by hidao80** [comment]
👍

**Comment by alice1017** [comment]
@KEINOS @hidao80 

ありがとうございます。 🙏 
それではCONTRIBUTING.mdとwikiを編集してPRを立ててマージ次第このissueもクローズします。
