### ISSUE TITLE
【報告】Qithub のトゥート内の「C++」タグがハッシュタグ化されていない

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#159]
## 報告

下記リンクにて参照できるトゥートの「C++」タグが記号部分を境にMastodonハッシュタグ扱いになっていないです。

https://qiitadon.com/@qithub/100819678404806383

## 自分の案

記号は一般的な発音に近い英単語にすればよいのではないでしょうか？

- 例1) C++ → CPlusPlus
- 例2) C# → CSharp
- 例3) ASP.NET → ASPdotNet (「d」が小文字なのは @hidao80 のセンス)

## 補足

Qiitaタグ中の記号等をMastodonタグ化するにあたって、ルールを設けた方が良いでしょうか？  
@KEINOS さんにお任せ😎で良い？

P.S.
旧バージョンでは対策済みだったような…？（ソース見てない (・ω<) ）

## TL;DR（進捗・結論 2018/10/01 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
> 「C++」タグが記号部分を境にMastodonハッシュタグ扱いになっていないです。 @hidao80 

Σ(- -ﾉ)ﾉ ﾊｯ!?

> 旧バージョンでは対策済みだったような…？

対策してましたね。。。失念しておりました。

> @KEINOS さんにお任せ😎で良い？

👍

**Comment by hidao80** [comment]
@KEINOS 
対処コミットのコミットログに本 issue 番号を入れておいてください。
マージ時に本 issue が自動 close されると思います。 :pray:

**Comment by KEINOS** [comment]
PR #160 の bef444537dc3f79ef4effd1a96878474b99f7773  😎 で修正しましたー！
