### ISSUE TITLE
【相談】/tools/crypt/ の別リポジトリ化とネーミング

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#161]
## 相談

1. [/Qithub-BOT/Qithub-ORG/tools/crypt/](https://github.com/Qithub-BOT/Qithub-ORG/tree/master/tools/crypt) に置いてある暗号スクリプト群を Qithub の別のリポジトリに分けたい。
1. リポジトリ（これらのスクリプト）の名称を決めたい。

## 詳細

Qithub のサークル用に作成した「[GitHub の公開鍵でファイルを暗号化するスクリプト](https://qiita.com/KEINOS/items/2abce1e5b15d799ac6d7)」ですが、[Qiita のコメント](https://qiita.com/KEINOS/items/2abce1e5b15d799ac6d7#comment-fb90213e11af4595e1ee)で「お作りになられているものの価値がすごい感あります」と褒められて戸惑っています。うれしい。

さらに、記事や README では言及していないにも関わらず、コメントを読むと、ソースからひっそりと目指していた方向にも気づいてもらえたのが嬉しいのですが、単一目的（GitHub に特化した暗号化・復号・圧縮・署名スクリプトのブラッシュアップ）にはリポジトリを分けた方がコラボしやすいと思いました。（もちろん issue はここで扱うとして）

### ネーミング

- Qiita/Qiitadon/Qithub 系列であることがわかるものにしたい
- 暗号・復号・署名など関連であることがわかるものにしたい
- ググって、まったく同じ単語（スペル）がトップに出てこないものにしたい

## TL;DR（結論 2018/10/12 現在）

> `QiiCipher`に決定。

- 発音は` [ki ˈsaɪfər]`
- "Key Cipher" より
- リポジトリ作成後の初回 Push で Close

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- Issue #112 「Qithub-ORG/tools/ 下に GitHub の公開鍵を用いたファイルの暗号ツールを公開しました」

**Comment by KEINOS** [comment]
ネーム案

1. `QCrypt`
2. `Criipta`（`crypt` の伊語・西語の`cripta`より）

まだシックリ来てない

**Comment by hidao80** [comment]
GitHub が噛んでいることは名前に込めなくて良い感じですか？

**Comment by hidao80** [comment]
`qrypt`にはライバルがいた…

**Comment by KEINOS** [comment]
> GitHub が噛んでいることは名前に込めなくて良い感じですか？ @hidao80 

あ、そうか。GitHub 必須だからそれも必要か、、、長くなるなぁ

> `qrypt` にはライバルがいた…

あ、[ほんとだ](https://www.google.co.jp/search?q=QCrypt)。さっきは「いねぇ！」とか思ってたら、履歴見たらタイポしてた 😳 

`QithubCrypt` で良い気がしてきたw

**Comment by hidao80** [comment]
正式名称 `GitHub Qrypt`
リポジトリ名 `GHQrypt`
コマンド `enc`と`dec`(早いもの勝ちぃ〜！)

「連合総司令本部より入電！」って感じ。😎

**Comment by KEINOS** [comment]
GHQwww

このトランポリンな大統領の時期に、攻めてる感じでいいですね。ただ、指摘があったように [`Qrypt` は名前も内容も被ってる](https://www.google.co.jp/search?q=Qrypt)のが残念なところ。

### 単語のブレスト

`Cipher` （暗号、演算）
`Crypt`（潜らせる、地下）
`GitHub`
`Qithub`
`Qiita`

**Comment by hidao80** [comment]
`crypt`がそもそも「暗号」という意味でない単語ですが、

1. `crypt`をもじる方向でいくのか、
2. `Cipher`など、単語的に暗号を意味する方向でいくのか、
3. それとも全く違う意味の単語に新たに「GitHub を利用した暗号」という意味をもたせるのか、

方向づけが必要かも？

P.S.
`crypt`もじりは難しそうですね。

**Comment by KEINOS** [comment]
確かに、地下礼拝堂のように「知る人ぞ知るもの」からの `Crypt` だけでなく、このライブラリには著名やアーカイブ機能もあるので、「GitHub で繋がる二人の秘密のなんちゃら」的な、何かが欲しい。

とりあえずの吐き出し
- `援交道`
- `デコ道`
- `CripTicTok`

**Comment by KEINOS** [comment]
漫画の「[CIPHER](https://ja.wikipedia.org/wiki/CIPHER)」にかけて、Jake, Roy, Rang, Siva, Anise とかはひねりすぎか。ってか、誰も知らんか。

**Comment by KEINOS** [comment]
このライブラリでできる事

- 暗号化
- 復号
- 著名
- 圧縮暗号

ライブラリの目的

- 簡単、シンプルに秘密を共有 Now on GitHub

**Comment by hidao80** [comment]
もう全く別単語から取ってくるなら、ダジャレか逸話があるもの(神話、伝承等)が良いですかね。

**Comment by KEINOS** [comment]
どんどん出して行きましょう。

**Comment by KEINOS** [comment]
`Ciipher`

**Comment by alice1017** [comment]
cigher

cipherのphをgithubのghに変えただけですが…

**Comment by hidao80** [comment]
発音しやすくて、音節が少ない方が良い？

コマンドは`enc`と`dec`だから、パッケージ名だけ決めればいいのかねぇ？

**Comment by KEINOS** [comment]
[`Cigher`](https://en.wikipedia.org/wiki/Cigher_River) ルーマニアの川ですって。まさかあるとは思わなんだ。

ひねりはあっても狙いすぎでない範囲だと、発音もしやすい方がいいのかしら。

**Comment by KEINOS** [comment]
日本の神話で、神様が岩に隠れちゃうのあったじゃない？あれ系だと狙いすぎか。
ナントカノオオノカミとか。読めねー

**Comment by KEINOS** [comment]
[`Amano-Iwato`](https://en.wikipedia.org/wiki/Amano-Iwato)略して `IWATO` 

意味わかんねー

**Comment by hidao80** [comment]
岩戸に隠れちゃう神は「天照大御神」ですね。
天皇家のカーチャンです。

**Comment by KEINOS** [comment]
FiveStar とかにしちゃおうかしら。アマテラスだけに。

**Comment by hidao80** [comment]
ここは厨二っぽく。
`selo`(セロ:ポルトガル語で「封印」)

**Comment by KEINOS** [comment]
あのイケメンの手品師みたいな？

**Comment by hidao80** [comment]
食品加工会社がでライバルなんだよなぁ〜。

**Comment by alice1017** [comment]
復号もするので封印しているわけじゃないのでは…（ネタにマジレス

**Comment by KEINOS** [comment]
w

**Comment by hidao80** [comment]
うお！そうだった！>セロ @KEINOS 

selo パッケージがインストールされていれば、封印が解けるイメージです。> @alice1017

**Comment by hidao80** [comment]
セロテープって、元ネタこれか…？ となっている

**Comment by alice1017** [comment]
ぶっちゃけkey-cipherじゃダメかな…
（今までの流れを完全無視

**Comment by KEINOS** [comment]
sello のルーツか > selo
封筒に赤いロウソクで封をするアレをスペイン語で sello と言う。セロテープのセロはセルロースみたいで、細胞だから違うかも。

`key-cipher` 悪くない。`QiiCipher` とか？

`git-crypt` に対抗して `qit-crypt` とか？

**Comment by hidao80** [comment]
`QiiCipher`、良いと思います。

**Comment by KEINOS** [comment]
`QiiCipher` `qiicipher` `QIICIPHER`

Qiita感はあると思うし、Key Cipher の響が好き。（ぜったい「チーサイファー」って言われると思うけど）

**Comment by alice1017** [comment]
QiiCipherいいですね！

**Comment by hidao80** [comment]
リポジトリ化するときには、発音記号つけようぜ(イキリ)😎

**Comment by alice1017** [comment]
発音記号付きのロゴとかカッコ良さそう

**Comment by KEINOS** [comment]
では、「QiiCipher」で決定〜！ 🎉 

> リポジトリ化するときには、発音記号つけようぜ(イキリ) @hidao80 
> 発音記号付きのロゴとかカッコ良さそう @alice1017 

`[ki ˈsaɪfər]` 
何気にかっこいい。今回はキータンにどんなコスプレをさせようか悩んでる。

**Comment by KEINOS** [comment]
ありがとうございました！
良いネーミングだ。気に入ってる。

では、リポジトリ作成後、初回 PUSH で本 issue クローズし 💪 !

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

本 Issue ですが、[リポジトリもできた](https://github.com/Qithub-BOT/QiiCipher)し、 https://github.com/Qithub-BOT/QiiCipher/commit/44d5db3ba07973e49311c23f0d639685bd33f28c で PR がマージされたので Close いたし 💪
