### ISSUE TITLE
【報告】Qiita-cache の初回リクエストで 500 が発生する

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#166]
## 報告

```
https://qithub.tk/api/v1/qiita-cache/?id=<任意の記事ID>
```

初回リクエストで 500 が発生し、２回目以降はキャッシュを表示する不具合が発生しています。
ローカルでは問題は発生していません。（PHP 7.2.6, macOS 10.13.6）

## 自分の案

```
https://qithub.tk/api/v1/qiita-cache/?tag=javascript
```

上記タグ名の検索オプションでは毎回 500 が発生しているので、キャッシュ記事保存後、キャッシュで使われているタグの処理あたりで問題が発生していると思われる。

## TL;DR（結論 2018/10/15 現在）

- 490834c で対応済み
- 原因：関数の引数で型宣言（タイプヒンティング）で `String` を指定しており、PHP7 では動作するも HHVM 3.6 では動かない仕様のため。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
ログを見ると以下のエラーが発生していました。

> PHP Catchable fatal error: Argument 1 passed to () must be an instance of \string, string given, called in [file] on line xxx and defined in [file] on line xxx

<details><summary>エラーの詳細</summary>

> PHP Catchable fatal error:  Argument 1 passed to Qithub\QiitaCache\getTagAsCommonFormat() must be an instance of Qithub\QiitaCache\string, string given, called in /home/kusanagi/qithub.tk/DocumentRoot/api/v1/qiita-cache/functions.php.inc on line 453 and defined in /home/kusanagi/qithub.tk/DocumentRoot/api/v1/qiita-cache/functions.php.inc on line 217
</details>

### 呼び出し行
https://github.com/Qithub-BOT/Qithub-ORG/blob/da2636e8e29c3d4deaaf0b77a88c822e60e7541a/api/v1/qiita-cache/functions.php.inc#L453

### エラー発生箇所
https://github.com/Qithub-BOT/Qithub-ORG/blob/da2636e8e29c3d4deaaf0b77a88c822e60e7541a/api/v1/qiita-cache/functions.php.inc#L217-L241

これは、Web サーバーの PHP が [HHVM](https://qithub.tk/tools/version/?key=phpinfo%28%29+-+HHVM&type=program) で動いているため、PHP 7.x で使えていた型宣言（タイプヒンティング）が使えないことが原因と思われます。（「[PHP の型宣言](http://php.net/manual/ja/functions.arguments.php#functions.arguments.type-declaration)」）

217行目の `getTagAsCommonFormat(string $name_tag)` の型宣言で、使えないスカラー型（`string`）を宣言しているので、これを修正すれば大丈夫と思われます。

PR で語ればよかったのですが、HHVM は PHP7.x との互換もあるため、今後の開発の注意事項として記録しておきます。（Wiki も整理しないと）

本件 😎 で進めます。

**Comment by hidao80** [comment]
うおお、リポジトリのコードがコメント内に引用できるんですね。カッコいい！😍
