### ISSUE TITLE
【許可申請】アクセストークン：Qiita-Cache API（魚拓 API）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#168]
Issue #128 および Wiki の「[アクセストークンについて](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)」より申請

## 申請内容

連続して Qiita 記事の魚拓を取るのにアクセストークンが必要です。

https://github.com/Qithub-BOT/Qithub-ORG/issues/164#issuecomment-429640033 にあるように、自宅のラズパイで 魚拓 API を夜な夜な叩かせようとしたのですが、気づいたらアクセス過多で Qiita API から弾かれていました。

と言うのも、アクセス・トークンなしの場合、 **Qiita の API は 1 リクエスト／分（１時間に６０回）** という[仕様制限](https://qiita.com/api/v2/docs#%E5%88%A9%E7%94%A8%E5%88%B6%E9%99%90)があるためです。

### 許可対象のディレクトリ

```
/api/v1/qiita-cache
```

### 利用するトークン

利用するトークンは `$ gettoken qiita qithub`（本番） および `$ gettoken qiita qithub-dev` （開発）です。

## TL;DR（結論 2018/12/05 現在）

- 👍 ~~２つ以上で許可。~~  [２つ以上ついた](https://github.com/Qithub-BOT/Qithub-ORG/issues/168#issuecomment-435247584)
- サーバーの `gettoken` 利用可能ディレクトリ一覧に上記パスを追記したら Close。
- 実装完了 Close 済み。（2018/12/05）

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue #164【報告】Qiita 魚拓 API（Qiita-Cache API）の実装

**Comment by alice1017** [comment]
👍

**Comment by KEINOS** [comment]
@alice1017 @hidao80 

👍 あざっす！ サーバーの設定（スクリプトからのアクセス許可設定）を終えたら Close しまーす。
（この設定もリポジトリでできるようにせねば）

**Comment by KEINOS** [comment]
@hidao80 @alice1017 

以下を行ったので close しまーす。
しばらく、夜な夜なラズパイから API を叩いてみます。トークン以外で問題あったら別 Issue を立てます。

1. アクセストークン付きの記事取得を実装しました。https://github.com/Qithub-BOT/Qithub-ORG/commit/1a008defe25553b33776bbc63bd50cc4dd4fde55
2. PHP の `file_get_contents` 関数がどうにも HHVM と相性が悪いので、記事取得に `cURL` クラスを使うことにしました。 https://github.com/Qithub-BOT/Qithub-ORG/commit/b8fd224a6b1cf43f47fb0969e71cba072f4b26f5

### その他 Info

- Qiita-Cache API の概要
    - https://github.com/Qithub-BOT/Qithub-ORG/tree/master/api/v1/qiita-cache
- 動作確認：
    - Qiita-Cache API のサンプル（通常キャッシュ）
        - https://qithub.tk/api/v1/qiita-cache/?id=807717ee1b61ed804853
    - Qiita-Cache API のサンプル（キャッシュ時、ユーザー＆記事がなくスパム判定だった場合）
        - https://qithub.tk/api/v1/qiita-cache/?id=49f10efb25f8a74416da
    - キャッシュ時にスパム判定されると API の同階層の `.spams/` ディレクトリに格納されます。※
        - `/api/v1/qiita-cache/.spams/4/49f10efb25f8a74416da.json`

※ `.spams` ディレクトリは、[Qiita-SPAMS](https://github.com/Qithub-BOT/Qiita-SPAMS) リポジトリの別名クローンにする予定です。実装前に、ローカルで取得したスパムは別途 Qiita-SPAMS に PR したいと思います。
