### ISSUE TITLE
【報告】Qiita-cache API で存在しないタグについて検索した場合

### ISSUE THREAD

**Issue by yasokada** [Qithub-BOT/Qithub-ORG#173]
## 質問

タグ検索ですが、
`https://qithub.tk/api/v1/qiita-cache/?tag=javascript%20TomCT`
とした時に以下が返ります

```json
[
    "JavaScript",
    "tomct"
]
```

一方でQiitaではtomctというタグは存在しないようです。
[Qiitaでtomctタグ検索](https://qiita.com/search?utf8=%E2%9C%93&sort=&q=+tag%3Atomct)

存在しないタグの場合、そのまま同じ文字列を返す
という仕様でしょうか?

(どうするのがいいかは利用者次第かもしれませんが）

**Comment by KEINOS** [comment]
> 存在しないタグの場合、そのまま同じ文字列を返す
> という仕様でしょうか? @yasokada 

あいや、これは仕様です。README に明記されていませんでした。失礼いたしました。

以下の箇所で、初めて出現つまりキャッシュには存在しないタグだった場合は、そのタグが最も多いタグと判断して、そのまま返しています。

https://github.com/Qithub-BOT/Qithub-ORG/blob/1bc100e380d3b496a1196fd595030d250dfd12f0/api/v1/qiita-cache/functions.php.inc#L267-L270

これはキャッシュの集計以前にタグが使われている可能性もあったことからなのですが、キャッシュにない場合は、本家をクロールしてチェックする工程を入れるのもいいかもしれません。

ちなみに、本家ではタグは全て lower case に置換して DB 化しているようです。

**Comment by yasokada** [comment]
該当コードの掲示とあわせて、ご連絡ありがとうございます。

キャッシュと本家、２つを考えることになるのですね。

「多く使われるタグ」の処理であれば、（未登録タグでの）処理時に何も返らないよりは、元の文字列を返す方が扱いやすいかもしれません、と思いました (つまり現状の実装のまま）。

**Comment by KEINOS** [comment]
> つまり現状の実装のまま @yasokada 

ご意見いただき、ちょっと調べてみたところ、本家 API からもタグを取得できそうなので、現状の実装に対して１つ精度を高められそうです。

### 本家 API 

- タグが「存在する」　： https://qiita.com/api/v2/tags/JAVAscript
- タグが「存在しない」： https://qiita.com/api/v2/tags/TomCT

どうやら本家の場合は、登録時は lower case で DB 登録しておき、メジャーなタグの場合は、別途、置換リストでロゴや公式の表記に置き換えているようです。

### ブレスト

「タグのタイプミスを検知する用途」のことを考えると以下はどうでしょう？
お手すきに、ご意見いただければと思います。

- 検索タグがキャッシュに「ある」
    - → 一番出現の多かったタグ表記名を返す
- 検索タグがキャッシュに「ない」
    - 本家 API に問い合わせて「ある」
        - → そのタグを返す
    - 本家 API に問い合わせて「ない」
        - リクエスト・クエリに `&only_used=true` が「ある」
            - → 空（""）のタグを返す
        - リクエスト・クエリに `&only_used=true` が「ない」
            - → 検索クエリのタグを返す （従来の動き）

**Comment by KEINOS** [comment]
@yasokada 

[KEINOS-Issue173-BetterTagDetection_29181213](https://github.com/Qithub-BOT/Qithub-ORG/tree/KEINOS-Issue173-BetterTagDetection_29181213/api/v1/qiita-cache) のブランチで以下のように実装してみました。

- 一般検索（デフォルト動作）
    - リクエスト
    ```
    /api/v1/qiita-cache/?tag=TomCAT%20JerryMOUSE%20JAVAscript
    ```
    - レスポンス
    ```json
    {
        "TomCAT": "Tomcat",
        "JerryMOUSE": "JerryMOUSE",
        "JAVAscript": "JavaScript"
    }
    ```
- `only_used`クエリ有効
     - リクエスト
    ```
     /api/v1/qiita-cache/?tag=TomCAT%20JerryMOUSE%20JAVAscript&only_used=true
    ```
    - レスポンス
    ```json
    {
        "TomCAT": "Tomcat",
        "JerryMOUSE": "",
        "JAVAscript": "JavaScript"
    }
    ```

主な変更点は以下の３つです。

- JSON 配列の添字に対応する検索タグを使うようにした
- キャッシュに存在しない場合、Qiita API に存在するか確認するようにした
- "only_used"クエリに値がある場合、タグが存在しない場合は空（""）の値を返すようにした

特に問題なさそうであれば、PR をかけたいと思います。（マージされたら本 issue は close）
お気付きの点や、ご要望ありましたら遠慮なく〜

**Comment by yasokada** [comment]
@KEINOS 
良いと思います。

一つひっかるところは`only_used=true`の部分です。

A. only_used=true のように=trueをつける方がいいのか(`&only_used=true`か`&only_used`)
(`only_used=false`という使い方をしない、という点で)

B. only_usedで意味が分かりにくいように思います。別の用語を考えてはいますが。。。
(もう少し考えてみます)

**Comment by KEINOS** [comment]
> 一つひっかるところは `only_used=true` の部分です。 @yasokada 

確かにいまひとつ直感的ではないですね。値は適当でいいというのも逆に戸惑ってしまうかもしれません。

実は Mastodon の API が同じ仕様なのですが、確かに私もそれに戸惑い [Qiita 記事にした](https://qiita.com/KEINOS/items/94b755c1afc5e3ab34ff)くらいだったのを思い出しました。

以下のようなクエリ・フォーマットはどうでしょう？

```
?return_value=only_used
?return_value=dafault
```

**Comment by yasokada** [comment]
@KEINOS 

こういう風にも考えてみました。
（簡潔ではないですね）

```
?return_value=only_used
?return_value=search_tag_if_not_used
```

**Comment by KEINOS** [comment]
@yasokada 
> こういう風にも考えてみました。

なるほどー。言われてみれば `default` では挙動がピンときませんね。

>（簡潔ではないですね）

内部動作を知るものとしてはピンと来ますが、わかります。以下はいかがですか？

```php
?return_value=only_used
?return_value=self_if_not_used #alias of「return_value != 'only_used' || return_value == ''」
```

**Comment by yasokada** [comment]
@KEINOS 

ファイナルアンサー
ですね。

selfを含めてself_if_not_usedというのは簡潔ですね。

コメントの部分も分かりやすいです。

**Comment by KEINOS** [comment]
@yasokada 

Σd(-`ω´-〃) ﾗｼﾞｬ！

では、今晩、実装してマージし 💪 ! 
アドバイスあざっす！

**Comment by KEINOS** [comment]
@yasokada 

PR #174 で仕様を反映いたしました！よろぴくご査収ください。（あわせて当 Issue Close いたしました）

- [?tag=JAVAscript%20TomCAT%20JerryMOUSE](https://qithub.tk/api/v1/qiita-cache/?tag=JAVAscript%20TomCAT%20JerryMOUSE)
    ```json
    {
        "JAVAscript": "JavaScript",
        "TomCAT": "Tomcat",
        "JerryMOUSE": "JerryMOUSE"
    }
    ```

- [?tag=JAVAscript%20TomCAT%20JerryMOUSE&return_value=only_used](https://qithub.tk/api/v1/qiita-cache/?tag=JAVAscript%20TomCAT%20JerryMOUSE&return_value=only_used)

    ```json
    {
        "JAVAscript": "JavaScript",
        "TomCAT": "Tomcat",
        "JerryMOUSE": ""
    }
    ```

**Comment by hidao80** [comment]
JerryMouse...
よき

**Comment by yasokada** [comment]
TomCAT
JerryMOUSE

トムトムとニャーゴ
ジェリージェリージェリーチュウ
ですね

そんな深い意味が。
