### ISSUE TITLE
【報告】ドメインが Expire されています

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#175]
## 報告

#87 で取得した https://qithub.tk/ のドメインが期限切れで失効されています。

すみません。メールに気づかず手続きをしていませんでした。

再取得には 1,100円（9.95米ドル）かかるそうです。

## 案

1. 無料のドメインを別途取得して、ドキュメント類を書き直す
2. 手間を考えると 1,100 円出して更新した方がいい（毎年更新料が発生する？）

## TL;DR（進捗・結論 2018/12/21 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連Issue #87 Organization の公式ドメイン「Qithub.tk」の取得と情報

**Comment by hidao80** [comment]
案1に👍

@KEINOS さんにだけ負担を押し付けるのは違うと思うので。
サークルはドメインとは関係なく生き続けますし、その辺は受け入れていい変化かなと思います。

**Comment by KEINOS** [comment]
#178 でドメインを取得しました！

ので、こちらは Close しまーす。
