### ISSUE TITLE
「Qithub」のロゴやキャラクター募集

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#18]
# アイコンやキャラなど募集します！

ボット名とアカウントも決まった（ #9 ）のですが、アカウントのアイコンが寂しいです。

取り急ぎ、以下のアイコンを作成しましたが、暫定でいかがでしょうか？

![qithub_250x250](https://user-images.githubusercontent.com/11840938/30875728-61e0f35e-a32f-11e7-8079-907e3e248783.png)

**Comment by hidao80** [comment]
:thumbsup:

顔が描かれていないところが「bot」っぽさを強調しており、シルエットはQiitan を踏襲しているところがとても良いです！

特に変更がなければこれで行きましょう。本issueをクローズしていいと思います。

絵がかけてうらやましぃ。:)

**Comment by KEINOS** [comment]
あと GitHub のロゴにも似せているところがポイント 😄 

では、一旦クローズとして「擬人化したよ！」「キャラ作ったよ」など何かあれば、ここにリクエストしてください。再オープンいたしまーす。

**Comment by KEINOS** [comment]
ロゴを反映しました。良い感じ！

## ロゴ ＠ Qiita
<img width="100%" alt="2017-09-27 16 01 43" src="https://user-images.githubusercontent.com/11840938/30900029-5ca08d0a-a39d-11e7-9d8b-f8add20424e5.png">
<img width="100%" alt="2017-09-27 16 01 58" src="https://user-images.githubusercontent.com/11840938/30900038-6322b3f6-a39d-11e7-95c9-b7dc6d4c1170.png">

## ロゴ ＠ Qiitadon

<img width="725" alt="2017-09-27 12 48 23" src="https://user-images.githubusercontent.com/11840938/30900088-8340347e-a39d-11e7-9705-c28fc75af32e.png">
<img width="297" alt="2017-09-27 12 49 19" src="https://user-images.githubusercontent.com/11840938/30900093-8a497e10-a39d-11e7-81b3-2ba314a97198.png">
<img width="624" alt="2017-09-27 13 35 31" src="https://user-images.githubusercontent.com/11840938/30900111-9c6fb74e-a39d-11e7-9938-ebc0714a5fc4.png">

**Comment by hidao80** [comment]
👍 ！！！！
