### ISSUE TITLE
【バグ】QiiTimeで同一記事を同一時報で複数回tootしている

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#180]
## 報告

sasanquaneuf@qiitadon.comさんの下記指摘により、QiiTimeが同一記事を同一時報で複数回tootしていることが判明しています。

sasanquaneufさんのtoot： https://qiitadon.com/@sasanquaneuf/101574339240810960
QiiTimeのエビデンス： https://qiitadon.com/@QiiTime/101574300645667936

## 推測

- 分をまたぐ間に保存しきれないほど大きい記事は、保存済みフラグが立つ前に再度登録してしまうのではないか。
- 現在、新規tootチェックcronが1分おきになっており、上記不具合が発生しているのではないか。

## 自分の案

- 原因は不明。これから調査して、わかり次第スレッドに投稿します。
　　　↓
- 分をまたぐほど大きなtootに対応するべく、新規tootを発見した時点で**書き込み中フラグを立て**てはどうか

## TL;DR（進捗・結論 yyyy/MM/dd 現在）

- 調査中 ( `・ω)🔎

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
本 Isse の現象は以前からチョイチョイ出ており、発生する条件として「新規 Qiita 記事の公開直後に編集を繰り返した」場合に発生します。

原因は３つの仕様にあります。

1. Qiita 記事の公開後すぐに編集を行うと **Qiita 側の新着に再掲載される**という Qiita の仕様
2. QiiTime でなく Qiita-Items の仕様で、記事の**投稿時間をベースに判断している**という仕様
    - IF ( 記事の投稿時間 == [現在のトゥート時間内](https://qithub.gq/api/v1/qiitime/) ) なら QiiTime に返信
3. Qiita-Items の**トゥート済み一覧は１時間おき（n:00）にリセットされる**という仕様

上記３つの仕様の組み合わせにより、この現象が発生します。

つまり、Qiita 側の新着では、いったん削除されて再掲載されているのですが、BOT は削除されたかまで検知しておらず、単純に**投稿時間が前回と異なるため別記事として判断**し、再掲載のトゥートが重複トゥートになるという塩梅です。

### 回避案

- 「現在の時報の時間内にトゥートしたデータ」とは別に、「過去 n 時間以内のトゥート済み記事 ID 一覧」を用意する。
- この「n 時間内のトゥート済み一覧」に該当する記事 ID であった場合にスキップする処理を、下記のスキップ条件に追加する。

https://github.com/Qithub-BOT/Qithub-ORG/blob/2baeb57438addf1e814206fe04e684656b39a2ff/api/v1/qiita-items/index.php#L87-L95

**Comment by hidao80** [comment]
@KEINOS 
ううむ…説明と状況がかみ合っていない部分があるので確認を取りたいのですが。

例えば [syui さんのこの投稿（password-cli）の編集履歴](https://qiita.com/syui/items/a34cd36eaaec5df7ea4d/revisions)をみると、編集された様子がありません。

にもかかわらず、[QiiTimeの同一トゥート時間内](https://qiitadon.com/@QiiTime/101575244311088613) に

- https://qiitadon.com/@qithub/101575265184275542 ：AM 05:05
- https://qiitadon.com/@qithub/101575279794468086 ：AM 05:09

> Hint: #cli_qiita で検索するとかかります

と、**編集履歴のない同一記事IDのトゥートが重複してトゥートされている**ように見受けられます。

ここまでで、上記トゥートは @KEINOS さんが[原因としている条件](https://github.com/Qithub-BOT/Qithub-ORG/issues/180#issuecomment-462577864)のうち、2. しか満たしておらず、**組み合わせで現象が発生する**という説明とも合致しません。

Qiita-Itemsのソースが読み込めていないので「ここ！」と言いづらいのですが、本件の原因はどこにあると考えられるでしょうか？

**Comment by KEINOS** [comment]
あらー。確かに！

となると、**ファイルの書き込みと読み込みのズレが問題**っぽいですね。要 DB 化の挙動臭がします。

現在、中途半端に API 間でスクリプトを共有しているのでトレースするにも煩雑になっています。

サーバーの OS を入れ替えた際にコンテナ化してよりシンプルに実装するので、その時に SQLite3 対応させたいと思います。

**Comment by hidao80** [comment]
@KEINOS 
Qiitadonにアカウントがある方には重複して通知がいくという不具合ですが、Qiita-Itemsの挙動としては致命的な不具合ではないと思われますので、優先度中くらいにしておきます―😊

**Comment by KEINOS** [comment]
QiiTime のコンテナ化が終了しているので、この issue は一旦 close でいかがでしょうか。
OS 入れ替え & コンテナ稼働化が終了して、再発した場合は、別途コンテナの issue をあげるとして。

問題なければ、お手すきに close お願いし 💪
