### ISSUE TITLE
【相談】不要なリポジトリの削除

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#182]
## 相談

不要なリポジトリを削除したい。

- ChQiita, ChQiita-DEV
- Qithub-DEV
- Qithub-CMD
- Qithub-CORE

## 自分の案

サーバーの OS を CoreOS に移行することで各種機能をコンテナ化するにあたり、上記のリポジトリを一旦削除したいと思います。

メンテナンスがされていないため、ChQiita などのライブラリでセキュリティ・アラームが発生し、対応を続けるのが面倒なのと、OS の変更により当時の仕組みと大きく異なるからです。

週末明け（06/10）までに問題（ 👎 ）がなければ削除したいと思います。

## 補足

ChQiita などネーミングが面白いものは、後に何かしらの方法で復活させたいと思います。

## TL;DR（結論 2019/06/12 現在）

- Qithub-DEV を除き削除済み
- Qithub-DEV は OS 移行後に削除予定

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
:+1:

**Comment by KEINOS** [comment]
Qithub-DEV 以外の不要なリポジトリを削除しました。 😎 

Qithub-DEV はサーバーの WebHook にも使われているので、CoreOS に移行したら削除します。

なので、一旦クローズです。
