### ISSUE TITLE
Qiitadon TCGの作成

### ISSUE THREAD

**Issue by matyapiro31** [Qithub-BOT/Qithub-ORG#185]
## 提案

Qiitadon TCG (カードゲーム)の作成

## 自分の案

Qiitadonのユーザーや流行りなどを用いたカードゲームの作成

- オリジナルのルールのカードゲーム
- Qiitadonのタイムラインなどから自動的にカードを追加する
- リポジトリ名はQithub-TCG

## TL;DR（進捗 2020/9/26 現在）

まだ何もコードは書いてません。

----------------

- [ ✔️  ] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
@matyapiro31 

とても良いと思います！タイムラインからカードが決まるのは面白いですね！

リポジトリも作成しました！

以降、このスレではリポジトリの管理（停止・削除や移管）のみとして、それら以外の**一般的な Issue は該当リポジトリの Issue で進める**ようにしましょう。

- Qiitadon TCG のリポジトリ
    - https://github.com/Qithub-BOT/Qithub-TCG
- Qiitadon TCG の Issue
  - https://github.com/Qithub-BOT/Qithub-TCG/issues

※ イニシャル・コミットがされたら、この Issue はクローズしましょう。
