### ISSUE TITLE
Organization のタイトルを変えるべきでは？

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#2]
当Organizationのタイトルを以下のように変更することを提案します。

    「はじめてのQiitaシリーズ制作委員会」
       ↓
    「BOTch - Qiitaユーザーのコラボ用Qiitadonボット」

理由①：「はじめての〜」が主体となると「要件定義書」「仕様書」含むその他の「非はじめての〜」記事が趣旨とブレることになるため。

理由②：GitHubのMarkdownをQiita記事に反映させることで共同制作記事を実現しており、その一例として「はじめての〜」があるため。

理由③：Organizationの目的をBOT開発に注力し、BOTのユーザーが「はじめての〜」記事を作った方が明確。（そのユーザーが自分たちであっても）

**Comment by hidao80** [comment]
Organization タイトル変更、賛成です。

ただし、このままだと「何をするボットを作るプロジェクト（Organization）なのか」がわかりにくいかと思います。
将来的にボットが対象とするアクションが明確になったら、「コラボ」の単語をより具体的にすると、名は体を表す感じになってよりよいと思います。

```
対案：
例）「BOTch - リポジトリ内 Qiita 記事　投稿および Qiitadon 広告ボット」
```

うーん、私がプロジェクトのスコープが見えていないことがモロバレですね。（汗
しかもお役所的な命名なので、もうちょっとシャレオツな単語を使ったほうが、
我々のテンションが上がるような気がします。:)

まずは提案していただいた Organization タイトルでよいと思います。

**Comment by KEINOS** [comment]
OrganizationのタイトルとOrganization名を変更しました。
ブックマークしていた場合は変更をお願いします。

    「my-first-qiita」→「Qiita-BOTch」
    「はじめてのQiitaシリーズ制作委員会」→「「BOTch - Qiitaユーザーのコラボ用Qiitadonボット」

一旦クローズとし、タイトルはBOTの仕様が固まってきたあたりで再考する際に再オープンしたいと思います。
