### ISSUE TITLE
Git のブランチ名の付け方

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#20]
#17 より。ブランチ名が同一であった場合、issue のスレッドも同一になってしまうようです。

基本的な命名方法を決めませんか？

### 基本

    ＜ユーザー名＞-＜タイムスタンプ YmdHi＞
    例） KEINOS-201709271730

### ベター

    ＜ユーザー名＞-＜タイムスタンプ YmdHi＞-＜MEMO＞
    例） KEINOS-201709271730-AddOauthLogin

**Comment by hidao80** [comment]
私もそのアイデアで今まさに悩みつつプルリク上げたのですが、**ブランチ名にユーザ名を入れると別のユーザがそのブランチを触る(= clone する)可能性がある**ため、混乱のもとになるかも、と考えています。

また、全員が全員お行儀よくブランチを切ってくれない可能性も考慮する必要があると考えています。

対案：
```
<コミット単位メモ>-<タイムスタンプ YmdHi>
例）AddClosedIssue#20-2017091741
```

コンクリフトを起こした時には**より早くプルリクがマージされた方**を優先で解決したらどうでしょうか？　個人開発だと原則コンクリフトしないので、要領のいい解決方法がわかりません。;(

**Comment by hidao80** [comment]
**「マージに不適当なプルリクである」** 条件に、 **「ユーザ名と異なるブランチ名を使っている」**  という規約を入れることもできますが、啓蒙が大変そうですね…

また、編集対象ファイルをロックできない Git の性質上、コンクリフトは**同一ブランチ名で開発している当人同士の問題**であることが避けられません。コンクリフトを起こした(= push できない)人は素直に pull してもらう、というのが Git 的に自然な解決方法でしょうか。

**Comment by hidao80** [comment]
連投失礼します。

延々同じブランチ名を使ってプルリクのスレッドを伸ばし、当該スレッドをクローズさせないのは、プロジェクトの進捗管理上よろしくないと考えます。

そのため、**機能ごとにブランチを切り、プルリクを上げ、コミットされたらプルリクをクローズする**のをルーチンにしたらよいかと思います。
機能を追加するごとに新しいブランチを切るイメージです。

うぅ…そもそも Git の正しい協業の仕方がわからない… ;(

**Comment by KEINOS** [comment]
わっかんないですねー。買っているようで買っていなかったGit本。

個人作業では「日付」でブランチを切って、終わりにマスターにマージするという日記風でしか利用しておらず、忙しい時は「もぅマスターでいいや」とやってしまいます。同じ箇所を触る人もいないし。

ネットを漁ったら、以下のQiita記事がわかりやすくまとまっていると感じました。

https://qiita.com/muran001/items/f13742b51da3a22117ee

ただ、ドキュメントとコード（`items`と`scripts`）ではブランチのありかたが違うのかな、とも感じました。

`items`リポジトリに関しては、本当であれば「第２版」とブランチを切り、それにコミットして行って、最後に"master"にマージさせ、「第３版」のブランチを切るのが正しい（出版ぽい）と思います。

しかし、上記手法は**リリースしたら後戻り出来ない場合には確実で有効**ですが、Qiitaに同期させること＋Wikipedia方式を採用している以上、確実性よりは即時性が大事なので手間でしかないと思われます。

また、`scripts`に関しても、本当は「開発版」（dev）「修正版」（fix）などでブランチを分けるのが正しいと思うのですが、BOTアプリのリリースが重要ではなく、動いているBOTが重要なので、 "master" を直接叩き上げるくらいで良いと思っています。

そのため、コミット名のルールを決める前に、以下の２点を先に議論した方が良い気がします。

1. `items`リポジトリと`sctipts`リポジトリでブランチ名のルールを分けるべきか
1. 共通の汎用ルールを設けるべきか

理屈では私は前者が良いと思います。

ただ、**堅牢なBOTを作るのが目的ではない**ので、「修正は早いもの勝ち」「気軽に参加できる」「失敗したらみんなで直せば良い」といった雰囲気が保てるなら**後者の方がシンプルで良い**と思います。

**Comment by hidao80** [comment]
#19 より転記します。

> マージ後のブランチの処分も慣れてなのでどうしようか迷いますが…
>
>A案. 断固破棄！ 別ブランチ（この場合通常の Qiita 記事編集ブランチ）の成果をロールバックするかもしれない！
>B案. 断固保持！ 対象機能（この場合対象記事１ファイル）ごとにルートブランチを切り、それぞれのプルリクスレッドで議論をすれば、いちいち issue を立てなくても記事編集方針が相談＆相談履歴が残る！
>
>どっちにも利があるような気がします… issue 立てて議論します？

**Comment by hidao80** [comment]
>1. itemsリポジトリとsctiptsリポジトリでブランチ名のルールを分けるべきか
>2. 共通の汎用ルールを設けるべきか

2. 案に賛成です。安易にルールを増やすのは得策ではないと考えます。

ルール案は、

1. 追加機能（記事）ごとにブランチを切る。
2. 機能追加（記事の完成）が**達成されていない**プルリクの場合、ブランチを残し、プルリクもクローズしない。プルリク時コメントに**不足事項を書く**ことにする。
3. 機能追加が**達成されいる**プルリクの場合、ブランチを削除し、プルリクをクローズする。

で、どうでしょう。

これなら「私には機能追加はできないけど、メッセージの修正（誤字脱字の修正）ならできる！」という人にも貢献してもらえると考えます。
なおかつ、機能単位でブランチを削除するので、ロールバック耐性もつくのではないかと期待します。

ちなみに、issue、プルリクにテンプレートを設定することができるようなのでそれに必要な記入事項を書いておけば混乱が減らせるような気がしています。（以下URL参照：Qiita 記事）

https://qiita.com/nyamogera/items/3fe6985b45fbd5377184

**Comment by KEINOS** [comment]
> ちなみに、issue、プルリクにテンプレートを設定することができるようなのでそれに必要な記入事項を書いておけば混乱が減らせるような気がしています。

これは良いですね！ `items` `scripts` 両リポジトリに各々置いてあげれば、基本ルールは同じでできそうですね。

1. 追加機能／記事ID ごとにブランチを切る。
2. 機能追加／記事の完成 が**達成されていない**プルリクの場合
    - ブランチを残す
    - プルリクもクローズしない
    - プルリク時コメントに**不足事項を書く**こと
3. 機能追加が**達成されている**プルリクの場合
    - ブランチを削除
    - プルリクをクローズする

となると、共通のブランチ命名ルールは以下のような感じですかね？

    <コミット単位メモ／記事ID>-<ブランチ作成時のタイムスタンプ YmdHi>
    例） AddClosedIssue#20-201709281309
    例） 1a52282f0b132347c2b1-201709281309

**Comment by hidao80** [comment]
試しに items 向けにテンプレート用 Markdown ファイル集をプルリクしました。問題がなさそうなら、items の master にマージして運用を始めてみましょう。

ちなみに、
```
.github/
     CONTRIBUTING.md
     ISSUE_TEMPLATE.md
    PULL_REQUEST_TEMPLATE.md
```

は、ディレクトリごと Github の予約語の様です。

**Comment by KEINOS** [comment]
マージしました！
とりあえず、ちょっと運用してみて、わかりづらいようであれば、再オープンするってことで、:thumbsup:クローズ？

**Comment by hidao80** [comment]
👍

**Comment by hidao80** [comment]
new issue をちらっとのぞいてみました。

われながらいい感じ。（自画自賛

**Comment by KEINOS** [comment]
Issue のテンプレ触ってみたかったので、いささか早いですが issue #22 をあげてみました。

とりえず、こちらはクローズしまーす。
