### ISSUE TITLE
items リポジトリを整理しましょう（deprecated documents）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#22]
## 提案・相談・質問内容

以前のBOTのアカウントで作成された記事（depre_xxxxxx.md）があるので整理したいです。
これらのファイルは現BOT（Qithub）のアカウントでは更新できません。

## 自分の案

削除用のブランチを切ってプルリクするので、余計なファイルを消していなければ「マージェで？」と（矢沢風に）言いながらマージする。

## 補足

issue のテンプレートきましたね！活用できそう。
ちなみに、Mastodon のリポジトリの issue だと以下のようなフッターが入るようになってますね。

---
- [ ] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
Oops!

補足のほうでテンプレートへの情報が付いてきましたね。\
まとめて処理しましょう。

1. 削除用ブランチでのプルリク：:thumbsup:OK！
2. issue テンプレートのフッターについてのアイデア：:thumbsup:採用！

さっそく issue テンプレートを修正しましょう。\
直り次第、プルリクします。
