### ISSUE TITLE
Organization 運営の基本ルールを考えよう

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#27]
## 相談

基本ルールを考えましょう。\
ブレスト気味にアイデアを集めて、キャッチーな標語5〜7箇条にしたいです。

## 自分の案

- 簡潔・明瞭
- 使って楽しい・作って楽しい
- ユーモアでレビュアーをハッピーに
- どれくらい？ をハッキリと（Don't let cry）
- 「いいね！:thumbsup:」を伝えよう！

## 補足

ダジャレ上等！ **明るく、楽しく、上品に**アイデアを募集します。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
「簡潔・明瞭」を「シンプルリク（簡潔・明瞭にキメて行こう）」とか。 @hidao80 さん提案の「KISSから始まるストーリー」とか。

「KISS〜」は、'scripts'リポジトリで諸機能の初回実装の際の「Hello world!」の替わりに使うルールでもいいかなと思います。 Qithub-BOT/scripts#10

"Don't let cry"は個人的にツボ（オヤジ臭があるところも）ですが、「何を」がわかりづらいかな。

「 👍 」など **emoji を使うのは伝えやすい**＆伝わりやすいので、入れたいところ。

**Comment by hidao80** [comment]
「KSS～」は、パロディネタなのと、「Don't～」は韻を踏むのを優先しすぎているので語弊がある 😅 として、

- 簡潔・明瞭に KISS して
- 使って楽しい・作って楽しい
- ユーモアでレビュアーをハッピーに
- 「いいね！👍」を伝えよう！

項目数のバランス的に、3 or 5 or 7 項目がいいんですが、思いつかないので問題なければ上記で暫定、ということで。

**Comment by KEINOS** [comment]
私も３もしくは５項目程度が良いと思うのですが、個人的には、もぅ少しブラッシュアップしたいところです。

・KISS（簡潔・明瞭）
・HAPPY（楽しく作って、楽しく使える）
・:thumbsup: 😄  🤔 （emoji でシンプルに気持ちを伝えよう）

**Comment by KEINOS** [comment]
「KISS」「HAPPY」 以外には「FUNNY」（もしくは「FUN」）があるといいかもです。

- KISS & CLEAR（簡潔・明瞭）
- HAPPY（楽しく作って、楽しく使える）
- FUNNY（いつもどこかにユーモアを）
- 👍 😄 🤔 （emoji でシンプルに気持ちを伝えよう）

**Comment by hidao80** [comment]
:thumbsup:

 4 項目はさすがにバランスが悪いので、提案いただいた 3 項目をちょっとだけいじってみました。\
個人的には定義と説明は「:」でつながると気持ちがいいもので。

- KISS: 簡潔・明瞭に
- HAPPY: 楽しく作って、楽しく使える
- 👍 😄 🤔 : emoji でシンプルに気持ちを伝えよう

…う〜む、「Funny」、捨てがたいですね。

**Comment by hidao80** [comment]
うわぁ、コメント書いている間に「4項目版」を投稿されてしまった！

**Comment by KEINOS** [comment]
やはり「遊び心」は入れたいけど、４つはバランス悪いですよねぇ。

**Comment by KEINOS** [comment]
😄  編集しちゃっていいじゃないですか（笑

**Comment by hidao80** [comment]
こうなったら、5 つ目をひねり出します！

**Comment by KEINOS** [comment]
ひねりだした「 💩 を使おう！」

いや・・・ちがう、な。

**Comment by hidao80** [comment]
苦し紛れのお役所仕事。

- KISS: 簡潔 
- CLEAR: 明瞭
- HAPPY: 楽しく作って、楽しく使える
- FUNNY: いつもどこかにユーモアを
- 👍 😄 🤔 : emoji でシンプルに気持ちを伝えよう

忍法、分裂の術！

本当は、頭文字を並べ替えると英単語にしたかったんですが、私の英語力では無理でした :cry:

**Comment by KEINOS** [comment]
そうか第一項は分身できますな。いい感じ！

あとは、 issue でこの五箇条をポイントして、マトを得られるかですな。

「ちょっと煩雑なので誰か KISS ME MORE #27」
「一読ではわかりづらいと思いました #27」
「みなさん #27 で行きましょうよ」
「 👍  #27 で失敬」

大丈夫そうな気がする。とりあえず、この５つに 👍

**Comment by hidao80** [comment]
おお！ ナイスな例文ありがとうございます！\
#27 をエイリアスにした意思疎通は面白いですね！ このOrganization の精神がここにある気すらします。:smile:

ここでこの issue をクローズします。後ほどドキュメントも PR します。
