### ISSUE TITLE
issue にラベルを付けられるようにしませんか？

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#3]
issue の優先度・属性を表すのに、プロジェクトのカラムを分けるのではなく、issue のラベルを使うイメージを持っていました。

本 issue のタイトルに「[提案]」というラベルもどきをつけていますが、「提案」・「質問」・「不具合」・「重要度：高」・「重要度：中」・「重要度：低」などのラベルがあるとよいと考えています。

提案
-----

プロジェクトのカラムは、

1. プロジェクトに属するノートを配置するカラム（注: issue は置けない）
2. scripts に属するノート・issue を配置するカラム
3. items に属するノート・issue を配置するカラム

の 3 本立てにすれば、

- 進捗ステータス軸
- 所属リポジトリ軸

のマトリクスにならずに済み、高プライオリティノートはカラムの上側、低プライオリティノートはカラムの下側に配置することで、リポジトリごとにカラムの上から順に消し込めばよい運用になりステータス管理がやりやすいのではないかと考えています。

また、Github には issue をリポジトリ単位でラベル検索する機能もあるようなので、閲覧性の向上にも寄与すると考えられます。

そのため、「当該 issue の優先度・属性」を表すラベルを issue にもつけたかったのですが、現在 issue 登録画面にラベル選択機能がありません。ぜひ復活を検討してください。

**Comment by KEINOS** [comment]
なるほど。ノートやissueのプライオリティがカラムをラベルでリプレイスからのドメインをカラム〜チョってやつですね！

縦軸を所属になっとくです。了解！
となると、ラベリングは必須なのでトラベリングしてきます。

**Comment by KEINOS** [comment]
[進捗]
GitHub本家のヘルプには「カスタムラベリング」可能とあるのですが、issueを有効にしてラベルの項目が出て来てはいるものの、「New Label」がありません。要探索です。

https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

<img width="405" alt="2017-09-24 11 11 58" src="https://user-images.githubusercontent.com/11840938/30778781-7b8b0f3c-a119-11e7-8d46-4bd20ac092a8.png">

**Comment by KEINOS** [comment]
カスタム・ラベルの登録方法を発見

1. リポジトリを選択
1. 「issue」もしくは「Pull request」タブを選択
1. 左上上部の検索で**空欄のまま**「Labels」ボタンを押下

すると添付画像のような画面がでました。みなさん（member権限ユーザー）のissue作成画面では右側にラベルの項目はありますか？

追伸：ラベル名については別issue #5 を用意しました。

<img width="1044" alt="2017-09-24 11 17 32" src="https://user-images.githubusercontent.com/11840938/30778829-599edf6a-a11a-11e7-9e53-4bd54c4af537.png">

**Comment by hidao80** [comment]
現在 member 権限では、ラベルの編集、ラベルの付いた issue の作成ができないようです。（添付画像参照）。

ラベルのリストは表示され、検索キーとすることはできるようですが。

ちなみに、こちらの環境では確認できないのですが、「ひとつの issue に複数のラベル」をつけることはできますか？　可能であれば、複雑なラベルルール考えず重要度ラベル3パターン、ホウレンソウカテゴリー3パターンを作ればよいと考えています。

確認と、member へのラベル編集権限の許可をお願いします。

<img width="783" alt="default" src="https://user-images.githubusercontent.com/8155294/30779724-3339d550-a133-11e7-9cd1-863972f63327.PNG">
<img width="878" alt="2" src="https://user-images.githubusercontent.com/8155294/30779725-333b313e-a133-11e7-9956-13cfaf98aed3.PNG">

**Comment by hidao80** [comment]
ひとつの issue に複数のタグがつけられました。自分個人のリポジトリで確認してきました。

ラベルの分け方については issue #5 で言及します。

**Comment by hidao80** [comment]
こちらの issue の結論は出ていますが、member 権限で issue にラベルがつられるようになるまではオープンのままとします。

member 権限でラベルがつけられることが確認できしだい、クローズします。

返信不要。

**Comment by KEINOS** [comment]
どうやら、ユーザーには３つの権限（Admin, Write, Read）があり、"member"のデフォルトを「Read」にしているためラベルがつけられないようです。

個別に権限を変えるためには、「ブラックリスト方式」つまりデフォルトを"Write"もしくは"Admin"にして、個別に「Read」へ権限を落とす方式のようです。

GitHubによると、デフォルトを"read"にしておき、チームを作成して、そのチームに権限を与える「ホワイトリスト方式」を勧めているので「WriteUsers」チームを作成して、 @hidao80 を追加してみました。

おそらく「メンテナ」や「品管」などのチームが適切と思いますが、現状十分とし、もうしばらくして別途issueを立ち上げて決めたいと思います。

チームの気になる点は、チームの中にまたチームがあります。部署と課みたいな関係でしょうか。とりあえず作ってみました。

## 手順
1. Teamを作成
2. Temaの対象リポジトリの追加
3. Teamにユーザーを追加時にリポジトリ毎の権限を聞かれるので"Write"を選択

### 参考文献

- 『Limiting interactions with your repository - User Documentation』<br>https://help.github.com/articles/limiting-interactions-with-your-repository/
- 『githubのorganizationアカウントの運営について - Qiita』<br>https://qiita.com/chari/items/ee16bf16715f4bbcbd9b
- 『GitHub の新しい Organization パーミッションモデル（2015年10月リリース）について理解する | まくまく Git ノート』<br>http://maku77.github.io/git/github-new-organization-permissions.html

**Comment by hidao80** [comment]
チーム作成と権限委譲、ありがとうございます。おかげさまで issue にラベルをつけることができました。:)

チームの中にチームがあるのは、例えば中～大規模開発を想定すると「フロントエンドチームとバックエンドチームにそれぞれアーキテクチャ、コーダ（ライブラリアン含む）、プロマネがいるとする。このとき『アーキテクチャ達にはコードの issue 立てとドキュメント整備だけさせてコードを触らせない』とか、『コーダ達にはドキュメントの issue 立てとプログラミングだけさせてドキュメントを改変させない』」とかってユースケースが考えられますね。

日本の開発現場は割と「アサイン」の概念がないですが、欧米では個人の責任範囲を明示する習慣があるようなのでその影響かと。
