### ISSUE TITLE
Qiitaコラボ記事 のメディアファイルについて（画像の利用）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#31]
## 相談

`items`内のMarkdownテキストは良いとして、記事の質の向上のため画像を利用したい場合はどうしましょう？

## 自分の案

- "images"ディレクトリを設置してそこに置く。
- 画像のファイル名は「＜Qiita記事ID＞-＜連番nn＞.＜拡張子＞」とする。
- 記事内に `[[img:＜上記の画像ファイル名＞]]` といった Qithub記法（？）で記述し、Qiitaに転送（記事の更新）を行うタイミングで imgタグ 及びパスへ自動置換を行う。

QiitaAPI経由で画像をQiitaのサーバーにうんぬん、も考えたのですが**画像の差し替えや削除などの機能実装の手間を考えるとシンプル**だと思います。

## 補足

**リポジトリの容量が心配**ですが、 GitHub から警告や容量が逼迫してきた際に画像置き場を再考（ issue を再オープン）するとし、上記の Qithub 記法の置換先のパスを変更→記事の更新を行うといった手法で対応可能だと思います。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

---------------
## TL;DR（結論 2017/10/04 現在）

- "images"ディレクトリを設置してそこに置く。
- 画像のファイル名は「＜Qiita記事ID＞-＜連番nn＞.＜拡張子＞」とする。
- Qiita互換記法でQiita反映時に記事内に画像埋め込みの置換を行う。
- 具体的な記法
```
![代替テキスト](画像のID "画像タイトル")
```
> `![Qiitadon_500_Pokemon.gif](xxxxxxxxxx-01.gif "500エラーの画像")`

#### アップロード時置換処理
```
![代替テキスト](CDNの画像パス "画像タイトル")
```
> `![Qiitadon_500_Pokemon.gif](https://cdn.rawgit.com/Qithub-BOT/items/_images/xxxxxxxxxx-01.gif "500エラーの画像")`

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
「TL;DR」追記しました。

**Comment by hidao80** [comment]
👍

**Comment by hidao80** [comment]
Qithub 記法は混乱のもとなので、CDN（注:下記リンク参照） 利用を提案します。

参考記事: https://qiita.com/takanorig/items/89db46120d2ec171e3d8

上記サービスに負荷をかけるのは記事をアップロードするタイミングだけで、画像へのリンク記法は qiita 標準にできるのではないかと。

FAQ ドキュメント的なものに明記する必要がありますが。

**Comment by KEINOS** [comment]
> CDN利用を提案します

👍 
RawGit ってたまに使っていましたが CDN だったんですね。てっきりコンテンツ・ヘッダーを付けるだけのパーサーなのかと思ってました。確かにサブドメインに 'cdn' って付いてますね 😄 

また、Qiita 記法に準拠することに関しても 👍 ですが、CDN を利用することを前提とすると、やはりIMG の記述に工夫が必要だと思います。

#### Qiita記法
```
![代替テキスト](画像のURL "画像タイトル")
```
> `![Qiitadon_500_Pokemon.gif](https://qiita-image-store.s3.amazonaws.com/0/78776/dfbef3f0-822c-b2f2-834f-bed75fe36dc8.gif)`

#### 一度記事を保存した後の置換
```
<img width="500px" alt="Qiitadon_500_Pokemon.gif" src="https://qiita-image-store.s3.amazonaws.com/0/78776/dfbef3f0-822c-b2f2-834f-bed75fe36dc8.gif">
```

### 提案
#### Qiita互換記法
```
![代替テキスト](画像のID "画像タイトル")
```
> `![Qiitadon_500_Pokemon.gif](xxxxxxxxxx-01.gif "500エラーの画像")`

#### アップロード時置換処理
```
![代替テキスト](CDNの画像パス "画像タイトル")
```
> `![Qiitadon_500_Pokemon.gif](https://cdn.rawgit.com/Qithub-BOT/items/_images/xxxxxxxxxx-01.gif "500エラーの画像")`

#### 一度記事を保存した（アップロード）後の置換

    Qiita の Amazon AWS に Qiita側で置換される（恐らく）

上記であれば、共同著者にCDN付きURLの入力をしてもらうより入力ミスが減る気がしますが、いかがでしょう？

**Comment by hidao80** [comment]
👍

画像タイトルを alias にするのがとてもいいと思います！🙆

qiita 互換記法のオプションを使えば、画像のpath が変わっても問題がないと思います。

この手で行きましょう！
