### ISSUE TITLE
issue の最終的な結論をスレッドの頭にとりまとめる

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#33]
## 問題

クローズド issue も増えてきて良い感じなのですが、クローズされた issue を見返すと**結論にたどり着くまでに時間がかかる**のが気になります。

時系列で過程を辿れる（追体験できる）ので、現在のルールや事項が**どのような経過を経て決定したのかが納得しやすい**ので、当事者は思い出すのには良いのですが、ドキュメント化するときにドキュメンターが苦労したり、ニューカマー（新参のこと、新種のオカマさんではない）が来た時に辛いんじゃないかな、と。

## 自分の案

協議中はスレッド内で適宜取りまとめていけば良いと思いますが、以下のようにしてはどうでしょう？

    最初の質問者（issueを立ち上げた人）は、
    知りたかった内容の最終結果もしくは現在の最新状態の取りまとめを明記してからクローズする

Qiitaユーザの場合は「TL;DR」から入って「TS;DR」に移るのが好きだと思うので、具体的には以下のような感じが良いと思います。

```
## 提案
げほげほげ・・・

## 自分の案
HOGE Hoge hoge

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/10/04 現在）
- Foo Bar で統一する
```

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------
## TL;DR（結論 2017/10/04 現在）

採用。以下のルールで運用することに。テンプレ、運用ルールに追記

    最初の質問者（issueを立ち上げた人）は、
    知りたかった内容の最終結果もしくは現在の最新状態を
    最初の投稿の下部に取りまとめてからクローズする

**Comment by hidao80** [comment]
👍 いいですね！

このプロジェクトを初めて、各スレッドを何往復もしましたので、効果のほどが分かります。

早速テンプレを直します。運用ルールも同じ PR に書いときま〜す。😄

**Comment by hidao80** [comment]
#34 と #35 の PR で、issue と PR のテンプレートを修正しました。

いま手元に PC がないので、CONTRIBUTING.md は後日直します！

**Comment by KEINOS** [comment]
> CONTRIBUTING.md は後日直します！

👍

**Comment by hidao80** [comment]
CONTRIBUTING.md 直しました！

**Comment by KEINOS** [comment]
マージ時に `close #33`入れ忘れたので手動でクローズし 💪
