### ISSUE TITLE
PR の「変更内容」欄をテンプレートから削除しませんか

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#37]
## 提案

PR の変更内容は、ブランチのコミットログを見ればわかる（はず）なので、コメントテンプレートから削除したい。

## 自分の案

コミットログの粒度を下げ、1度の PR に複数のコミットが含まれることを許容すれば、
実質 PR の変更内容がすべて追いかけられるため、`PULL_REQUEST_TEMPLATE.md` には
変更内容を記述する必要がないと考えられる。

変更内容を記述する必要のないコミットの粒度、簡潔なログの記述を規約としたい。

## TL;DR（結論 2017/10/04 現在）

- [x] 変更内容項目を削除する

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
> PULL_REQUEST_TEMPLATE.md には
> 変更内容を記述する必要がない

👍 

私も、コミット時に記入して、PR 時に「あ、また記入するのか」と感じた事が何度かありました。

PR が issue と紐付けされていた場合、両者に TL;DR を追記する必要が出てくるので **PR に TL;DR欄は必要なのか**も いささか 感じるのですが、TL;DR ルールは始まったばかりなので、それは後々考えるとして、まずは `変更内容欄は必要ない` に 👍
