### ISSUE TITLE
Qiitaコラボ記事 「Organization 全体で使われる用語集」

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#38]
## 提案

コラボに必要な GitHub 用語など、このプロジェクトを通して勉強しながら用語を覚えたりしているのですが、新規メンバーやコンセンサスのために **「知っておいた方がいい単語」辞典** というか、とりまとめがあれば良いなと感じました。（[ググレカス](http://ja.uncyclopedia.info/wiki/%E3%82%B0%E3%82%B0%E3%83%AC%E3%82%AB%E3%82%B9)と言われそうですが）

## 自分の案

まずは、ここのissueで募集し適宜 TL;DR に追記していき、ある程度溜まってきてたら Qiitaコラボ記事 に移すなどを検討してはどうでしょう？

### 例
| 用語 | 説明や用途 | 備考 |
| --- | --- | --- |
| PR | 俗に呼ばれる「プルリク」のことで、プルリクエスト（Pull Request）の略。自分が変更した内容を master に反映してもらうようにリクエストすること。リクエストが上がると番号が振られ、以降は PR #番号 で参照されることになる。 |  Qithub内ではトピック番号の１つとして扱われます。|

----------------

## TL;DR（結論 2017/10/05 現在）

- この issue でストックせずに Qiitaコラボ記事 でとりまとめる
    - Qiita記事ID：7157c17765e328917667
    - Qiita：https://qiita.com/Qithub/private/7157c17765e328917667
    - GitHub：https://github.com/Qithub-BOT/items/blob/master/7157c17765e328917667.md

-  新規 Qiitaコラボ記事を作成し[Qithub 設定資料集の用語説明](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md#用語説明)から引っ越し
- [x] 当面、新規Qiitaコラボ記事が必要な場合は issue を立てて作成依頼し、担当者は以下を実行。
    - Qiitaに新規記事を作成し Qiita記事IDを取得
    - master に「＜Qiita記事ID＞.md」を直接作成
    - コミット時に "Close #＜issue番号＞" を含めクローズ
    - 必要であれば クローズされた issueに作成した旨を伝える

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
Qithub 設定資料集 [1a52282f0b132347c2b1.md](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md) の末尾に、用語解説コーナーをひっそりと開設しているのであった。😉

ですが、 Qithub 設定資料集ページのボリュームが多くなってきたので、用語集は別ページの方がいいと思っています。

**Comment by KEINOS** [comment]
> 末尾に、用語解説コーナーをひっそりと開設

ほんとだ！ 😄 

ボリュームが大きくなると、大幅変更時コンフリクトがおきやすくなるので別ページにした方がいいかもですね。

早く Qiitaコラボ記事 の新規作成が手軽にできるといいな。（ね？ @KEINOS さん？）

**Comment by KEINOS** [comment]
あ、お呼びですね？

BOTからの新規作成は時間がもう少しかかりそうなので、「Qiitaコラボ記事 ●●●」で issue を立ててくだされば、手動でブランク記事を作ります。（Qiita側で作成→記事ID取得→GitHubに同IDで作成）

その場合は直接 master にWeb上から追加していいですかね？ PR を通す？

**Comment by hidao80** [comment]
👍 

直接 master に追加でいいと思います。

合意のもと、「空のファイルを作るだけ」なので PR 不要と思います。

**Comment by KEINOS** [comment]
TL;DRアプデしました。

用語解説の新規 Qiitaコラボ記事 作成したら、この issue はクローズでよろしいですか？

Qithub 設定資料集の「用語解説コーナー」をコラボ記事に引っ越してからのPRでクローズ？

**Comment by hidao80** [comment]
新規コラボ記事作成でクローズに賛成します。🙋
