### ISSUE TITLE
BOT のコンセプト・目的

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#4]
この BOT は何をするものでしょう？　BOT の利用者（BOT のアクション結果を受ける人たち）はどんなありがたみを感じてもらえるのでしょうか。

この辺りをこの issue で解決したいと思います。

**Comment by hidao80** [comment]
issue #2, @KEINOS より抜粋
```
理由②：GitHubのMarkdownをQiita記事に反映させることで共同制作記事を実現しており、その一例として「はじめての〜」があるため。
```
と、あるので、勝手に想像してみる。「イメージと違う！」というところはガンガン突っ込みお願いします。

要件
------

- Github の Markdown を Qitta 記事としてエクスポート　(要ブレイクダウン)

この一言に尽きますかねぇ。「Github 内の原稿の保存場所(パス)」とか、「記事原稿のフォーマット策定・周知方法」とかも仕様に含まれる気がしますが、「BOT のコンセプト」ではないと思います。

最悪、gogs や野良 Git でリポジトリを管理できてもいいかもしれません。

まずは「できるだけ小さな完成品」を目指すのはどうでしょうか。
Google Chrome だって、メジャーバージョンは 60 を超えているご時世、リーンスタートアップがいいかと思ってます。だって、動くものがあるほうが楽しいじゃないですか。:)

**Comment by KEINOS** [comment]
入力中に先を越されました！ 😄 
そうですね、まずは「可能な限り小さなもの」を作るところから始めましょう。:thumbsup:

---

「コンセプトと目的」づくりに向けて、共通イメージを保つためにちょっと記憶を吐き出します。

# ２つの面でQiitaユーザーとコラボしたい
1. 知識（Qiita記事）
1. 技術（実プログラム）

## ① 知識（Qiita記事）におけるコラボ

1. 現状のコラボの問題
    1. Qiita記事のコメントに付いたサジェスチョンなどによる**著者の更新に依存**している
    1. 第三者による**記事のリファクタリングが出来ない**（出版でいう校正が難しい）
    1. 良い内容なのに「もったいない」と思っても**参加しにくい**

1. 提案
    1. 上記問題は**架空の人物（BOT）の記事に対してであれば対応しやすい**のではないか
    1. GitHubに元データを置くことで、GitHub→Qiitaの投稿（転記）となるため**Qiitaの知的財産でなく、コラボレーター全員＝オープンソースの所有物となる**。かっこいい。
    1. 文章であるためコンフリクトフリーに近いので**Gitを使ったコラボレーションの練習にも良い**
    1. 文系出身、新人エンジニア、異業種など**誰でもコラボに参加できる**。（校正や図解作成など）

## ② 技術（実プログラム）におけるコラボ

1. 現状のコラボの問題
    1. そもそも「Qiita」には「paiza.IO」のような仕組みがない
    1. Qiitaユーザーが触れるAPIはQiitaとQiitadonしかない
    1. QiitadonはQiitaユーザーのインスタンスなのにPawooに負けていてくやしい
    1. Qiitadonのコラボだと言語依存があり、誰でも（自分の得意言語で）参加しづらい

1. 提案
    1. Qiita社内のSlackBot「Qiitan」よろしくQiitadonのBOTを共同で作れないか
    1. BOTへのダイレクト・トゥートが、BOTへのコマンドとなると面白そう
    1. BOTの機能拡張が言語依存しないのであれば、参加しやすいのではないか
    
# ∴ 両者の美味しいところ取りすると

    BOTを作れば解決じゃね？

## 「BOTのマイルストーン」のための備忘録

- GitHub内のリポジトリのMarkdown記事を自動でQiitaに投稿・更新できるようにする
- 新規Qiita記事をQiitadonで**良い感じで**トゥートできるようにする
- ダイレクト・トゥートの内容（ハッシュタグなど）で反応するようにする
- 機能の拡張に"paiza.IO"は使えないか（ユニットテスト的にでも）

### 機能の拡張（プラグイン）のイメージ
```sample.php
<?php

$toot_msg      = getTootMsg();
$toot_hashtag  = getTootHashTag( $toot_msg ); 
$command       = getCommand( $toot_hashtag );
$id_user_mstdn = getUserId_mastodon();
$id_user_qiita = getUserId_qiita( $toot_hashtag );
$access_token  = "xxxxxxxxxxxxxxxxxxxxxx"; // QiitaAPI v2

// プラグイン
switch($command){
    // プラグインに標準入力でデータを渡す
    case 'helloworld':
        // Pythonプラグイン by hidao80
        $result = `python ./plugin/hidao80_helloworld.py ${command} ${toot_msg}`;
        toot_direct( $id_user_qiita, $access_token, $result);
        break;
    case 'morning':
        // PHPプラグイン by KEINOS
        $result = `php ./plugin/keinos_morning.php ${command} ${toot_msg}`;
        toot_direct( $id_user_qiita, $access_token, $result);
        break;
    default:
        //略
}
// 略
?>
```

**Comment by hidao80** [comment]
バカでかい話題で issue を作ってしまったか、と若干後悔しています。;(

## 質問

1. ①-1-iii は、どう『もったいない』のでしょう？
2. ①-2-iv. は、qiita はそもそも「プログラマのための」と銘打っているので、解決してはいけない問題なのでは？
3. ②-1-iii. どのように Pawoo に負けている？　アクティブユーザ数？　運用力？　機能（拡張性含む）？

## 提案

返事を聞かずに提案するのもいかがなものかとも考えましたが、話題を収束させるためにあえて提案します。

### ミッションステートメントを作りませんか？

はい、社長や取締役が好きなアレです。　…引かないでください。 **全メンバーが当事者であれば、大変効果的** だと考えています。

要は、

```
「この BOT は○○する△△です。」
```

の空欄2つを埋めたいだけです。

「自分、たのしそうにしとるやん、なんや、それ。」と言われたときに返す「殺し文句」です。

一言聞いて、「おもしろそうやん！ 俺も混ぜてや！」って言わせたら勝ちです。

このフレーズさえあれば、

- 自分の活動を簡潔に他人に説明できます。
- 一言でイメージがわくので、follower、contributor、core になるポテンシャルを持っている人をただちに follower、contributor、core にすることができます。
- 自分たち（新たな core 達含む）が目指すべきものからブレません。合意が早くなります。

ただの言葉遊びになっては本末転倒ですが、折々で「この Organization が何を目指しているのか」を明確にすることで、「この機能は目的に合わないから実装をやめよう」とか、「この機能がないと目的が達成できないから当然いるよね」とかを素早く判断・合意できるようになり、個人・グループともに迷いがなくなります。

で、言い出しっぺがまず作るのが IT クラスタの習わしなので、たたき台を置いておきます。

```
「この BOT は qiita の記事品質を上げ、優良な死蔵記事への手入れを可能にする、SNS 型 UI 開発プロジェクトです。」
```

賛成・反対、提案返し、そもそも論、各種お待ちしております。

**Comment by hidao80** [comment]
#9 の Qithub の自己紹介が、ばっちりこのプロジェクト/BOT のコンセプトですね！

> QiitaとQiitadonのユーザ間コラボレーションを支援するためのBOTをQiitaユーザーで作るためのGitHubのOrganization用アカウントです。

1. Qiita と Qiitadon ユーザの
2. コラボレーション支援する
3. BOT 
4. の開発プロジェクト

follower、contributor には 1.～3. の説明で、core にはすべてを伝えれば、「#Qithub #とは」に対応できると思います。

逆に言うと、

- Qiita と Qiitadon ユーザのコラボレーション支援する
- BOT の開発

以外のプライオリティが著しく低いプロジェクト、というとらえ方もできるでしょうか。

例えば、

- ほかのインスタンスとのコラボレーションは **やらない**
- Mastodon 自体の改変、独自インスタンス運営は **やらない**

やるなら別プロジェクトでやってください、というスタンスではどうでしょうか？

**Comment by KEINOS** [comment]
> やるなら別プロジェクトでやってください、というスタンスではどうでしょう

それでいいと思います。

壮大なissue問題ですが、コンセプトは要ですしミッションが明確になりません。そのため、同じ穴でも、何度も、どんどん掘っていって、磨いていって、「キラー・フレーズ」が見つかるといいと思います。

といいつつ、収束に持って行くということで。

# TL;DR

    Qithub BOT のコンセプト・目的とは

- Qiita と Qiitadon ユーザのコラボレーション（コンセプト）
- 支援BOTの開発（目的）
- をQiitaの皆で楽しむ（コンセプト&目的）

例１）Qiita と Qiitadon ユーザのコラボレーション支援BOT開発を楽しむ（`scripts`リポジトリ）
例２）Qiita と Qiitadon ユーザのコラボレーションを支援BOTで楽しむ（`items`リポジトリ）

# TS;DR

Mastodon同様に「ポリシーに同意するなら改変してもいいし、それを商用・個人・無料・有料問わず自由にしていいけど、**変更は必ず共有して同じライセンスにしてね**。うふ ♪ 」ということにして、我々は**Qiita+Qiitadonを優遇していい**のではないでしょうか。

そのためにGitHubを利用しているとも言えるでしょうし。

ただ、**BOTのフォロワーはインスタンス縛りをしない方がいい**気がします。

例の「Qiita新着BOTの大誤爆空襲事件」で個人的に感じるのが、大御所インスタンスに流れているQiitaユーザーや、お一人様インスタンスのQiitaユーザーが多いということです。

BOTのフォロワーを増やすにあたり、ターゲット層を考えると「ハードコア・エンジニアおよびプログラマ」ではなく、先の質問の答えにも繋がる層がターゲットだと感じます。

    1. 「もったいない」とは？

視点はいいのに、読み手を考えていないのか「記事」になっておらず、「校正を入れたらアクセス増えるし、より有意義な記事になるのに」という記事です。「俺、文系じゃないし」と言うのはあまり好きではありません。

∴ コラボ記事の出番です

    2. qiita はそもそも「プログラマのための」と銘打っているので、解決してはいけない問題なのでは？

「文系出身、新人エンジニア、異業種など誰でもコラボに参加できる。」の箇所を指していると思うのですが、これはQiitaユーザー（著者でなく主に読者）のうち「文系なのに勤めたらプログラマー」「出版・建築に勤めているけど、（コスト削減のため）VBAちょっと触れるだけなのに、いつのまにかエンジニア（プログラム担当）」といった層を指しています。

建築は除外しますが、出版含め**俗に言う「文系」のエンジニア**を巻き込みたいのです。つまり、「俺、理系じゃないし」を言い訳にしている人にも参加できる場を設けたい、と。

「同じエンジニアなんだから得意分野で良くしてこーぜ」的な流れになると素敵だと思うのです。

∴ コラボ記事の出番です

    3. Pawooに負けてる？どのように？

まず、これはMastodonにおける話でPixivとQiitaの比較ではないのですが、インスタンスを比べると単純にユーザー数だけでなくサービス面含めQiitadonよりPawooの方が上だと感じるからです。運営のレスポンス含め。

なにより機能拡張を楽しんでいるのがうらやましいのです。

個人的には、人数は大きく増えては欲しくないのですが、人数が増えないとサービスとして会社から認知されませんし、アクティブ・ユーザーが増えないと予算が出ないと思います。

たまにフォロワーのブーストで流れて来る「QiitaのMastodonでQiitadonというものがあるらしい。ガクガクブルブル」みたいな内容を見ると、嬉しくもあり、中身を見たらガックシするんだろうなという気持ちもあります。

そこで**QiitaやQiitadonに足りないのは遊び心**という結論にいたり、ちょっと面白いことをやりたいな、と現在にいたるわけです。

∴ ボットの出番です

**Comment by hidao80** [comment]
私なりにまとめてみました。

### Qithub 3 つの more

- 共同執筆と互助
- 帰属意識の向上
- 楽しく環境改善

…お役所っぽい。もっと超！エキサイティンな単語に置き換えたいですが、それはおいおいするとしてプロジェクトのコアは上記 3 つかな？ と理解しています。

だいぶエッセンスが絞れてきた感じです。

**Comment by KEINOS** [comment]
いいですね。絞れてきましたね。この路線で行きましょう。

> もっと超！エキサイティンな単語に置き換えたい

👉  「Qithub 3つの moe」

**Comment by hidao80** [comment]
ツッコミ待ち…です…よね…？ :l

ホントに「moe」で記事にしますよ？

三項目はこれで行きましょう！
クローズOKです。

**Comment by KEINOS** [comment]
👌
