### ISSUE TITLE
Qiitaコラボ記事 「この BOT の機能について」

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#40]
## 依頼

@KEINOS さん、'scripts'リポジトリの[README.md](https://github.com/Qithub-BOT/scripts/blob/master/README.md)で、BOTの仕様を記載するQiita記事が必要なので、作成をお願いします。

## TL;DR（進捗 2017/10/05 現在）

- 作成済み
    - Qiita記事ID：3c1f06f93eb03463c470
    - Qiita　 ： https://qiita.com/Qithub/private/3c1f06f93eb03463c470
    - GitHub ： https://github.com/Qithub-BOT/items/blob/master/3c1f06f93eb03463c470.md 
----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
ご用命のQiitaコラボ記事作成ですが、タイトルが「この BOT の機能について」だとQiita側から見て**何のBOTの機能なのか、わかりづらい**ので再考が必要と思われます。

とりあえず Qiitaに限定共有で作成しましたので、後ほど修正をプルリクしてくださーい。

- Qiita記事ID： 3c1f06f93eb03463c470
- Qiita記事URL： https://qiita.com/Qithub/private/3c1f06f93eb03463c470

**Comment by KEINOS** [comment]
Qiita記事作成の一連の流れの小芝居を１人で一気にしてしまったので、メンバーの同意を得ずにクローズまでしてしまいました。再オープンします。

こんな流れで新規 Qiitaコラボ記事 を作成します。クローズ 👍 ？

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
👍
