### ISSUE TITLE
Qiitaコラボ記事 一覧（目次）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#42]
## 提案

Qiitaコラボ記事が増えてくると items リポジトリでは、記事IDだけなので一見してどのような記事があるのか判断できません。しかし、README.md に記述すると冗長になってしまいます。

<kbd><img width="80%" alt="2017-10-05 22 36 02" src="https://user-images.githubusercontent.com/11840938/31230405-e0b8e4ac-aa1e-11e7-9b19-87adf5262cc6.png"></kbd>

## 自分の案

Qiitaコラボ記事 に専用の記事を作成。BOT による items リポジトリにおける記事のマージ処理が行われた際に、同時に更新を行ってはどうか。

README.md には、そのリンク先だけを記述する。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（決定事項 2017/10/07 現在）

- 記事の更新時に合わせて索引を自動更新
- 非Qiita記事（README.mdと同等の）扱い
- フォーマット
    - ファイル名： items/[index.md](https://github.com/Qithub-BOT/items/blob/master/index.md)
    - CSV形式（各ROWの**最後のCOL（セル）はスペース２つで終了していること**に注意）
```
<記事ID 1>.md,[記事タイトル1](記事1 URL)  
<記事ID 2>.md,[記事タイトル2](記事2 URL)  
<記事ID 3>.md,[記事タイトル3](記事3 URL)  
︙
```

**Comment by hidao80** [comment]
## 賛成事項

- 索引ページを作る。
- 新規 Qiita 記事がマージされたタイミングで索引を更新する。

## 対案

記事 ID と記事タイトルの対を Qiita 記事にする必要性を感じない（読者(!=コラボレータ)に見せるメリットがない）ため、非公開ファイルとする事を提案します。

- items/index.md を作成し、**CSV で構成、マークアップは Markdown 記法を使う**。本ファイルは Qiita にアップロードしない。
- CSV は検索・**追記**・ソート・**フォーマットの維持**・可読の各容易性に優れている。

### 例

items/index.md

```
<記事ID 1>.md,[記事タイトル1](記事1 URL)
<記事ID 2>.md,[記事タイトル2](記事2 URL)
<記事ID 3>.md,[記事タイトル3](記事3 URL)
︙
```

新しい記事ができたら、`file_put_contents("index.md", $entry, FILE_APPEND);` するだけ。

CSV にハイパーテキストを埋め込むのも Markdown があったればこそ。

**Comment by KEINOS** [comment]
👍 

> 記事 ID と記事タイトルの対を Qiita 記事にする必要性を感じない
> （読者(!=コラボレータ)に見せるメリットがない）

確かにOrganization内およびSEO的に必要なだけで、非コラボレーター（一般読者）に見せる必要はないですな。そもそも、記事のタグ（ #コラボ記事 など ）で一覧を確認できるし。

'index.md'をCSVフォーマットは面白いですね！

プラグイン側も`file_get_contents`で取得できるので、'system'側がわざわざ渡さなくても良くなりますし。

- 非Qiita記事（README.mdと同等の）扱い
- CSVフォーマット
- 記事の更新時に合わせて索引を自動更新

試しに、手動で現在の index を作成してみて issue Close 👍 でしょうかね。

**Comment by KEINOS** [comment]
試しに作成したものをプルリクしてみたのですが、改行が問題になりそう。
見づらいですなぁ。

<kbd><img width="751" alt="2017-10-06 4 46 45" src="https://user-images.githubusercontent.com/11840938/31249476-679f1f9e-aa52-11e7-8e8e-adb8db621dbb.png"></kbd>

**Comment by KEINOS** [comment]
おぉ、良い感じ！:thumbsup:

一旦クローズで、BOT処理でつまづいたら再オープンします。

<kbd><img width="678" alt="2017-10-06 11 46 59" src="https://user-images.githubusercontent.com/11840938/31260909-30dc11a8-aa8c-11e7-85bf-9270da0195ba.png"></kbd>

**Comment by hidao80** [comment]
👍😄

**Comment by KEINOS** [comment]
PR #49 にあわせて TL;DR も修正。 行末を ',\\' → '  '（スペース2つ ）

**Comment by hidao80** [comment]
👍 😄

**Comment by KEINOS** [comment]
なぜか index.md が消えていた 🤔 ので PR #54 で再アップしましたー。

**Comment by hidao80** [comment]
おお、多分私がすごく古いブランチを使ってプルリク上げてしまっていたのだと思います。

申し訳ない😅

**Comment by KEINOS** [comment]
👍 😄 原因がわかれば ノープロ です

![noproblem](https://user-images.githubusercontent.com/11840938/31638188-3f00c1c8-b30d-11e7-81e5-68d4017ca5dc.png)
おてすきに PR #54 処理お願いしまーす
