### ISSUE TITLE
ラベル （カスタムラベル）の名称と色

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#5]
カスタムラベルの作成方法がわかりました。

タスクの優先度をきめるなど、ラベリングするにあたり、最低限のラベル作成からしたいと思います。

    ラベル名：高
    色：赤色

は汎用度が高い。

    ラベル名：高：提案
    色：赤色

目的と重要度が明確だが、個数が増えると煩雑になる？

どんな感じにしましょう？

------

### タグのラベル名とカラーリングの仕様

`scripts`および`items`の両リポジトリで使われるタグ名と色は以下の通りです。「緊急度」タグは他のタグと併用して使われ、緊急度に関しては #6 をご覧ください。

| タグ名 | 色コード | 元タグ名 |
| --- | --- | --- |
| 不具合 | #ee0701 | bug |
| 保留 | #ffffff | wontfix |
| 提案 | #fbca04| enhancement |
| 無効 | #e6e6e6 | invalid |
| 相談 | #33aa3f | help wanted |
| 緊急度：中 | #ffff00 | カスタム |
| 緊急度：低 | #0e8a16 | カスタム |
| 緊急度：高 | #b60205 | カスタム |
| 質問 | #cc317c | question |
| 重複 | #cccccc | duplicate |

<kbd><img width="100%" alt="2017-09-24 21 15 15" src="https://user-images.githubusercontent.com/11840938/30782435-8cb01254-a16d-11e7-8e35-7b903c3a5a1f.png"></kbd>

**Comment by hidao80** [comment]
ひとつの issue に複数のラベルがつけられることが確認できましたので(issue #3 参照)、具体的なラベルのデザインを提案します。

| ラベル名      | 色 |
|:--------------|:----|
| 重要度：高   | 赤 |
| 重要度：中   | 黄 |
| 重要度：低   | 緑 |

| ラベル名      | 色 | 備考 |
|:--------------|:----|:-------|
| 相談  | 緑 | GIthub default に準拠 |  
| 不具合 | 赤 | GIthub default に準拠 |
| 質問  | 紫 | GIthub default に準拠 |
| 提案   | 黄 | BOTch オリジナル |

重要度ラベルの色は本物のトリアージに準拠しています。

内容ラベルの色は Github のデフォルトラベルを参考にしています。そのほうが新参の方にやさしいかという配慮です。
提案についてはデフォルトコンパチがなかったので、ひらめいた時の電球マークのイメージで「黄」としました。

同色ラベルが2つ並ぶ可能性を考慮しましたが、重要度ラベルのほうを暗め、内容ラベルのほうを明るめのトーンにして回避できないでしょうか？

重要度ラベルに「重要度：」と書いてあるのが冗長のように見えますが、メンバーが増えた時に説明する手間を考えると、初めから書いてあったほうが良いと考えます。これなら、いちいち説明 & ドキュメント整備が不要になるからです。

**Comment by hidao80** [comment]
「重要度」よりも「緊急度」の方が直感的でしょうか？

**Comment by KEINOS** [comment]
「緊急度」の方が直感的ですね。色に関してもLGTMです！

**Comment by KEINOS** [comment]
「緊急度：高」（赤）とか、わかりすぎて怖いと思ったので絵文字を使って「:scream:至急」のように精神的にやわらげてはどうかと思ったのですが、「絵文字のユニコード範囲は使えない」と怒られてしまいました。（笑）

カスタムラベルおよび既存ラベルの日本語化をして、以下のように設定してみました。
いかがでしょう？

<img width="997" alt="2017-09-24 21 15 15" src="https://user-images.githubusercontent.com/11840938/30782435-8cb01254-a16d-11e7-8e35-7b903c3a5a1f.png">

**Comment by hidao80** [comment]
「緊急度：高」(赤色) はインパクトが強いですね。:(

ですが、この Organization の文脈分からない人でもすぐ commit / pull req. / issue できたほうがいいと思ってます。
後続のメンバーに「この issue (#5) 見といてね」って言って回るよりは後で効いてくると信じています。

…もうちょっとピンクよりの赤にします？

**Comment by KEINOS** [comment]
> …もうちょっとピンクよりの赤にします？

いや「緊急度：高」（ピンク）は怪しいイメージになっちゃうので、これで行きましょう😆！

ただ、信号（緊急度）の簡単な指針を決めたいですね。 #6 を立ち上げましたので、このissueはクローズします。

**Comment by KEINOS** [comment]
[`scripts`リポジトリ](https://github.com/Qiita-BOTch/scripts)のラベルの色付けを失念していました。
以下の内容でラベルを作成しました。


| タグ名 | 色コード | 元タグ名 |
| --- | --- | --- |
| 不具合 | #ee0701 | bug |
| 保留 | #ffffff | wontfix |
| 提案 | #fbca04| enhancement |
| 無効 | #e6e6e6 | invalid |
| 相談 | #33aa3f | help wanted |
| 緊急度：中 | #ffff00 | カスタム |
| 緊急度：低 | #0e8a16 | カスタム |
| 緊急度：高 | #b60205 | カスタム |
| 質問 | #cc317c | question |
| 重複 | #cccccc | duplicate |

**Comment by hidao80** [comment]
ありがとうございます。

基本的に、scripts と items で同じ名称には同じ色が使われているという認識でいいですか？

**Comment by KEINOS** [comment]
> 基本的に、scripts と items で同じ名称には同じ色が使われているという認識でいいですか？

**はい**、同じ色が使われます。長期返信をスルーしていました！ごめんなさい。 😭 

TL;DRを追加しました。

**Comment by hidao80** [comment]
👍😁
