### ISSUE TITLE
PR を立てる基準について相談

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#52]
## 提案・相談・質問内容

この頃、「マージをしてほしくない」PR を見かけるようになりました。  
ですが、Pull (マージ) を希望しない PR にとまどいを隠せません。

マージを希望しない Push は PR しないようにしませんか？ 

Git はブランチを PR せずに Push することを許容しているはずです。

## 関連 issue

Qithub-BOT/scripts#21 Qithub-BOT/scripts#23 Qithub-BOT/scripts#24

## 自分の案

- マージを希望しない Push について意見を求める時は、issue を立てるようにしませんか？  
   下記補足の書き方で、**PR を立てていないブランチを公開できるはず**です。
- マージを希望しない Push をするときは、PR を立てないようにしませんか?

## 補足

`[https://github.com/Qithub-BOT/scripts/tree/receive-github-webhook-201710110137](https://github.com/Qithub-BOT/scripts/tree/receive-github-webhook-201710110137)`

[https://github.com/Qithub-BOT/scripts/tree/receive-github-webhook-201710110137](https://github.com/Qithub-BOT/scripts/tree/receive-github-webhook-201710110137)

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/10/11 現在）

- **マージを希望しない PR は行わない**。<br>（レビュー等でマージがペンディングになっている場合を除く）
- **平行開発を防ぎたい場合は、 issue を立ててブランチ名を公開**しておく。<br>（平行開発とは他のメンバーの作業とのバッティングを指すが、同じ機能を別言語やアプローチで開発したい場合はこれを妨げないものとし、同じ issue内で別ブランチを立て、相談により解決するものとする）
- ブランチの進捗（コミット内容）がわかるようにしたい場合は、PR せずに**ブランチの Push/Publish のみを行う**。

### 参考文献

- [GitHub Desktop で Pushする方法](https://qiita.com/RINDO/items/b7fac50289e9d5046ab9 "『Github Desktopを使った開発の流れ(入門) - Qiita』")

**Comment by KEINOS** [comment]
なるほど、確かに戸惑いますよね。 😅 

「なんでも良いよ♪うふ」とか言いながら「それは嫌だ」と言っているようなものですものね。

GitHubデスクトップでローカル・ブランチをリモートに同期する方法（おそらくここという箇所はあるのですが、挙動）がわからなかったので、「いま、こんなのやってまっせ」的な進捗のつもりでPRしちゃってました。すみません。

**Comment by hidao80** [comment]
情報共有ありがとうございます！👍

個人的に「(Pull) Request が来ているのに応えてはいけない」のが引っかかってたのです。

ので、今後は **意見募集の建前で** issue を立てるというのはどうでしょう？  
進捗は TL;DR に、提案にリポジトリへのリンクを貼る(上記)とうまく行きそうな気がします。😄

強制にすると Organization 外からの開発がしづらくなるので、任意で立ててよいと言うことでどうでしょうか。

**Comment by KEINOS** [comment]
> 進捗は TL;DR に、提案にリポジトリへのリンクを貼る

👍 

「いま、こんなのやってまっせ」とアッピールしたい場合は、平行開発防止の意味でも**意見募集の建前で issue を立てる** に 👍 です。

では、 GitHub Desktop で **PR せずにローカル・ブランチをリモートに Push する方法**がわかりしだい、ここに報告して Close 👍 でよろしいですか？

**Comment by hidao80** [comment]
👍

> 平行開発防止の意味

issue を立てて **あえて競作(コンクール？)** をするのも面白いかもですね。😄

Github desktop で PR 無しで push できたら教えてください。😉

**Comment by hidao80** [comment]
FYI: [Github desktop から push (publish)](https://qiita.com/RINDO/items/b7fac50289e9d5046ab9)

**Comment by KEINOS** [comment]
> FYI: Github desktop から push (publish)

やっぱり「 ☁️ Publish」でよかったのね。そんな気はしていたのですが、アイコン的に自分のアカウントにフォークされて、そっちに Push されるのではとドキドキしてました。

いんふぉありがとうございます！試して見ます。

**Comment by hidao80** [comment]
:thumbsup:

**Comment by KEINOS** [comment]
いただいた情報で、GitHub Desktop でも無事 PR せずに Push/Publish できました！

なので、クローズ 👍 お願いします！ （P.S. TL;DRも更新しました）

<kbd><img width="1003" alt="2017-10-12 18 18 38" src="https://user-images.githubusercontent.com/11840938/31488977-5180598a-af7a-11e7-8996-17dd2f956ad9.png"></kbd>

**Comment by hidao80** [comment]
👍😊
