### ISSUE TITLE
Qiitaコラボ記事 「WPA2 の脆弱性 KRACKsに関する翻訳」の公開について

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#55]
## 提案

Qithub のコラボレーションの検証をかねてのパイロット版として、表題の[Qiita記事](https://qiita.com/Qithub/private/17871e7f26c308ef6514)（GitHub [17871e7f26c308ef6514.md](https://github.com/Qithub-BOT/items/blob/master/17871e7f26c308ef6514.md)）を**限定公開 から公開にしたい**。

## 自分の案

他の記事は別として、表題の話題がホットなうちに未完であっても、この記事を公開することで、認知に貢献すると思いますし、いいテストケースになる気がします。

## 補足

ただ、ウェーブをフィールしているというだけで、BOTによるマージ後のQiitaへの自動転送など、まだまだ実装が不十分なため、時期相応ではない（怖い）気もします。（Qiitadonにはオープンが始まっちゃったけど）

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗 2017/10/18 現在）

- ホットな記事は鮮度が命。公開することに。<br>https://qiita.com/Qithub/items/17871e7f26c308ef6514

**Comment by hidao80** [comment]
この記事は**鮮度が命**であると考えますので、最悪**BOT を通さず投稿することを考慮して良い**と思います。🙆

即、投稿しましょう！

BOT は通さないけど、共有記事としてリポジトリからアクセスだできるようになっていると嬉しいな。😄

**Comment by KEINOS** [comment]
👍 

当面は GitHub と Qiita 間のコピペBOTになりきります！

**Comment by KEINOS** [comment]
表題の記事を[追加翻訳している](https://github.com/Qithub-BOT/items/blob/17871e7f26c308ef6514-20171018/17871e7f26c308ef6514.md)のですが、区切りがついたところでアップロード（PR→記事更新）をしたいのですが、BOT の**PR がフォロワー時の自動マージ実行機能が実装されていない**ため、とりあえずこの記事に関しては 😎 ❓

**Comment by hidao80** [comment]
👍😄
