### ISSUE TITLE
GitHub の Qithub用アカウント作成

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#56]
## 相談

Qithub-BOT/scripts#29 で、自分（ @KEINOS ）のアカウントの自動コードレビュアーが自分自身を叱ってくれるのは面白いのですが、他のユーザーに対してもアチキが叱るわけで、現実のアチキはそこまでスキルがあるわけではないでありんす。

## 自分の案

Qiita や Qiitadon 同様、Qithub にもアカウントを作って、レビューをBOTにさせているイメージにしてはどうか。

- 理由①<br>Qithub-BOT のアカウントから叱られた方が Organization 的に面白いかと。
- 理由②<br>Organization のオーナーを @KEINOS から @Qithub に移すことでアチキの身に何かあっても引き継げる
- 理由③<br>@KEINOS の変なイメージアップが怖い (ﾉД＼lll) ﾋｰ
----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗 2017/10/17 現在）
- 審議中
```
　　　 ,､_,､　 ,､_,､
　 ,､_('・ω)(ω・`)､_,､
　('・ω)uﾟ 　ﾟuu(ω・`)
　 ﾞuuﾟ(　'・) (・`　)uu'
　　　　ﾟuuﾟ 　ﾟuJﾟ
```

**Comment by hidao80** [comment]
SideCI のプロジェクト設定から、コメント設定を「コメントしない」にすればいいのでは？

これで PR にコメントせず、プログラマは SideCI の画面を見ながら自動レビューが受けられるという寸法のような気がしてる（未確認）。

SideCI のアカウントは個別に取ってね！ で行ける気がしてる。

Qithub-BOT/scripts#29 で試して見ません？ 

![e35a3891-d0f6-4fd0-b21f-592dfaa50c02](https://user-images.githubusercontent.com/8155294/31660275-e2b35a4c-b371-11e7-98b9-4b35bbd6fe33.png)

**Comment by KEINOS** [comment]
そうか、Organization 側の設定のどこを見ても SideCI の自動コードレビューがねぇなと思っていたのですが、自分のアカウントに紐づけられていて、そのアカウントでコメントを投稿しているってだけなのか！なるほど！

> Qithub-BOT/scripts#29 で試して見ません？

そうしましょう、そうしましょう！
一旦コメントを決して、設定を変えてから再度レビューをかけてみます！

**Comment by hidao80** [comment]
👍 

コメントなしレビューが成功したら、この issue を閉じても大丈夫です😊

**Comment by KEINOS** [comment]
👍  コメントなしで PR のレビューが成功し（SideCIからめっちゃ叱られ）ました！

**Comment by hidao80** [comment]
👍
