### ISSUE TITLE
Organization の代返・代行（プルリク・ラベリング・承認などのサポート）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#57]
## 相談

Qithub のOrganization は有志によって運営されています。

体調含め各々の諸事情により`ラベル`チームや`プログラム`チームのメンバー全員が自分のチームの役割を遂行できないこともあります。Qiitadonはできるけど、ぶっちゃけ文章を書く気力やムードでない場合も当然あります。

個人的には、それをリスペクトしたいので面倒な時の**簡単な合図**があると良いなと思います。

## 自分の案

状態に以下の emoji を使うのはどうでしょう？

### 「なんとなく自分のROLEのような気がするけど、今はちょっと無理。誰か代返（対応）して」の意

    😫  🙏  = :tired_face: :pray:
    😪  🙏  = :sleepy: :pray:
    😷  🙏  = :mask: :pray:
    😱  🙏  = :scream: :pray:
    💩  🙏  = :poop: :pray:

### 「（マージなど）これは独断で進めちゃってよろしいかしら？」の意

    😎  👌  ❓ = :sunglasses: :ok_hand: :question:

### 「まかせてチョンマゲ」の意（他のチームや PR 当人含む）

    👌 = :ok_hand:

上記には「よろしくてよ」や「ノープロブレム」の意味も含みますが、その場合は「 👍 」が望ましいです。

### 「みんな忙しそうだけど、そうだったら独断で進めてもいいよ」の意

    IF 😫 THEN 😎 ❓ 

### 「ちょ、ちょっと待った」の意

issue/PR 対応が意図しない方向に動いていると感じる人がいれば、以下の emoji を出してストップをかけて、対応者は恐らく自分で気づかない何かが起きていると信じて、一旦落ち着くまで待ちましょう。

    👏 ✌️ 👌 👁  = :clap: :v: :ok_hand: :eye:

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗 2017/10/17 現在）

Emoji の基本的な定義は以下の通りとし、組み合わせは２文字までとする。（複雑にさせすぎない）

| Emoji | Code | 意   | 使用例 | Codes | 解釈例 |
| :----: | :----: | :--- | :-----: | :-----: | :------ |
| 😎 | `:sunglasses:` | 独断で進める | 😎❓| `:sunglasses: :question:` | 独断で進めるよ？|
| 🙏 | `:pray:` | (代わりに)お願い！| 😎🙏 | `:sunglasses: :pray:` | 独断で進めて！|
| 👌 | `:ok_hand:` | 了解！|  |  |  |
| ✋ | `:hand:` | ちょ、ちょっと待って！|  |  |  |
| 😭 | `:sob:` | マジ悲しい|  |  |  |
| 🙇 | `:bowing_man:` | ごめん、ちょっと無理… |  |  |  |  |

**Comment by hidao80** [comment]
大筋で合意です。気になるところは、❓の使い方です。

あまり記号化を進めると住民以外話せなくなるので、できるだけ少ない記号で意味が通じるようにしたい…

### 対案

 😎は「独断で進める」、 🙏  は「(代わりに)お願い！」の記号として、

`😎❓`：独断で進めるよ？  (：sunglusses： ：question：)
`😎🙏 `： 独断で進めて！(：sunglusses： ：exclamation：)
`🙏`：代わりにお願い！（：pray：：exclamation：）
`👌`：了解！(：ok_hand：)
`🖐`：ちょ、ちょっと待って！(：hand：)
`😭`：（issue、PR に対しては）「ごめん、ちょっと無理…」、（人に対しては）「マジ悲しい」 （：sob：）

#### 例1 

a: 忙しければ 😎🙏  
b: 👌

#### 例2

a: @hidao80 🙏 #n 
@hidao80: 😭 

#### 例3

b: 風邪にて :pray: @c
c: 👌  @b :sob:

「ごめん、ちょっと無理…」にフィットする emoji が欲しい。

**Comment by KEINOS** [comment]
なんかギャル語を論理的に展開している気に 🤣 

では、**emoji の組み合わせはMAX 2文字まで**ということで、上記の例題は以下の翻訳で合ってますかね

### 例１訳
a: （アチキ手が離せないので）忙しくなければ独断で進めてちょ
b: おっけーバブリー

### 例２
a: @hidao80 さん #n の案件、対処お願いしマッスル
@hidao80 : ちょっとムリポ

### 例３
a: 風邪ぎみなので @c さんお願いしマッスル
@c: おっけーバブリー @b さんはダメぽいので

> 「ごめん、ちょっと無理…」にフィットする emoji が欲しい。

    🚧 :construction:
    🙅 :no_good_woman:
    🙇 :bowing_man:

とか？

**Comment by hidao80** [comment]
おお、emoji の豊富な語彙が！ これがボキャ貧との差か！😁

大筋あってます！ 例3に謎の a 氏の影が…

ムリポに関しては、 🙇 （`:bowing_man:`）が良さげですね。👍

**Comment by KEINOS** [comment]
> 例3に謎の a 氏の影が…

あ、そうか！例題をちゃんと読んでないやいやい。これ昔からやっちまうんです。慌てない慌てない。

#### 例題３）

以下の Emoji を解読せよ

    b: 風邪にて 🙏 @c
    c: 👌 @b 😭

##### 回答

b: 風邪ぎみなので @c さんお願いしマッスル
c: おっけーバブリー @b さん辛そうですね。くれぐれもご無理などなさらないよう、ご自愛ください。日増しに秋の深まりを感...(rk

TL;DR に取りまとめてみました！問題なければ Close 🙏

**Comment by hidao80** [comment]
👍
