### ISSUE TITLE
ラベル 「緊急度：x」の指針（決定基準とラベリング担当）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#6]
各issueに複数ラベルが付けられることがわかり、「緊急度：高」といったラベルを付加することで、優先度を示すことができるようになりました。

ただ、人によって「重要度」同様に「緊急度」の温度差があると思います。

そこで、簡単な指針というか、「最低●●を含む場合には『高』」といったスレッショルドが欲しいです。

**Comment by hidao80** [comment]
実はそこは悩んでいました。
医療現場のトリアージでは、

- 歩けるか
- 出血があるか
- 脈拍数および呼吸数が所定範囲以内か（正確な数値を失念しました）

くらいの定数的・かつ1分以内に判別できる方法をとっていたと記憶しています。

なので、

- boolean で判断できる
- 定数の範囲（未満・以内・超過）で判断できる

のがふさわしいかと思います。

例えば、

- 緊急度：高
    - １リプライまたはチームメンバーの多数決で解決できる相談・提案・質問（Yes/No、OK/NG、n 者択一、etc.）
    - 仕様が未確定のため、実装作業が完全にストップする件に関する相談・提案
    - 適切な緊急度の相談を含む issue
- 緊急度：中
    - ただちに実装作業は止まらないが、完成に必要な足りない情報を提案・質問
- 緊急度：低
    - ほしい追加機能の提案
    - ただちに実装作業は止まらないが、要件定義において不明な情報の提案・相談・質問

定数的でないので以下の例を挙げるのは適当ではないのですが、私の主観では以下のルールの具現化が上記のルールです。

- 緊急度：高）即座に解決する問題、即座に解決しないと開発できない問題
- 緊急度：低）即座に解決する必要がなく、議論が必要な問題
- 緊急度：中）上記2件に属さない問題

ラベルをつける人の主観によるところが大きくならないようにしたいとは思いますが、「時間の見積もり」にも主観が入るので悩ましいところです。

**Comment by hidao80** [comment]
んん～、余計なお世話だと思いますが、提案ラベルをつけるときには first comment に提案者の暫定的な意見（たたき台）があるとうれしいです。

**Comment by KEINOS** [comment]
> 提案ラベルをつけるときには first comment に提案者の暫定的な意見（たたき台）があるとうれしいです。

確かに「提案」していませんね。 😅  すみません！ タグを外して #7 にポカ避けのissueを設けました。

**Comment by KEINOS** [comment]
・ boolean で判断できる
    ・ 定数の範囲（未満・以内・超過）で判断できる

いいですね。例えばポイント制というのはどうでしょう。

## トリアージ（優先度の決定と選別基準）

| 緊急度 | しきい値 |
| :---: | :---: |
| 高 | >= 50 |
| 中 | >= 25 |
| 低 | >= 10 |

| issueの概要 | ポイント|
| --- | :---: |
| 不具合である | 25 |
| 仕様が決まっていない | 20 |
| 実装作業が完全にストップしている | 50 |
| 機能を追加したい | 5 |
| etc | x |

**Comment by hidao80** [comment]
緊急度ウエイトポイント制、いいですね。:)

根拠がはっきりしていて、誰でも再現できるのがとてもいいと思います。

2点気になっています。

1. ウエイトポイント及びしきい値をラベルチームの合議制にしたい（定期的 or 緊急時に issue を立てる）
2. 10 ポイント未満が issue 化されない？ :P

２. は冗談です。見逃してください。:)

**Comment by KEINOS** [comment]
> ウエイトポイント及びしきい値をラベルチームの合議制にしたい
> （定期的 or 緊急時に issue を立てる）

そうですね！この値はトライ＆エラーでベストな値を決めていくべきだと思います。

> 根拠がはっきりしていて、誰でも再現できるのがとてもいいと思います。

ありがとうございます。

このポイント制は、実は仕事でも活用しているものです。ただ issue 決めでなく、**案件ごとの配当金額を決めるシステムに使っているもの**です。

「案件を取って来た」「基礎開発をした」「オフライン対応（オンサイト、ミーティングに同席など）した」「オンライン（メール・電話）対応した」「イレギュラー対応した」「定例処理をした」「請求書を出した」「改善した」といった、さまざまな項目を三段階評価で自己評価と他己評価で数値を出し、項目ごとの重みを掛けた数値を全体で割った割合で金額を決めています。

簡単であってもアクションがあれば評価になるので、割とうまく機能しているのですが、反省点として、逆に「案件を取って来る」「基礎開発を行った」といった難しい内容（重みのある項目）を皆が避けるようになり、案件が減ったという痛いシステムでもあります。

ただ、システム自体は好評なのも**何度も重みの調整を行っていたから**だと思うので、やはり定期的な見直しは必須だと思います。

最初、電話対応はポイントが低かったのですが、ちょっとクレーマー気味のクライアントの案件の時はかなりポイントが高くなりました。

つまり、ウエイト・ポイントにも旬があるというのが意外でした。

いずれにしても、最初の項目は５つ程度と少なく始めて issue が発生した際にラベルチームでミーティングして加えていったり重みを調整して行くのが良いと思います。

以下の３つは恐らく必要な項目だと思います。他に何がありますかね。

1. 不具合である
1. 仕様が決まっていない
1. 実装作業が完全にストップしている

## 項目の案
- 関連情報がない（見つかりにくい）
- 機能の拡張である

**Comment by hidao80** [comment]
> ウエイト・ポイントにも旬があるというのが意外でした。

なるほど。開発が順調な時は使用策定やドキュメント整備、クレーム対応（issue の解決等）の方がポイントが高く、LTL にトゥートを垂れ流しまくっているときは新機能の打ち合わせよりも、不具合の修正または運用（BOT を止める）が高ポイント（=緊急）である、という認識でよいでしょうか。

> いずれにしても、最初の項目は５つ程度と少なく始めて issue が発生した際にラベルチームでミーティングして加えていったり重みを調整して行くのが良いと思います。

そうですね。この手の事案は放っておいても複雑・肥大化するので、スタートは「簡潔・明瞭」を基本方針としたいと思います。

…！　「簡潔・明瞭」は本 Organization 5大基本ルールに入れてもいいかもですね。

KISS から始まるストーリー。（言いたかっただけ）

## 項目の案

1. 当該案件によって **被害が出ている** (ex. LTL 垂れ流し、BOT が頻繁に落ちる、セキュリティリスクが看過できない
2. 当該案件によって **実装がストップしている** (ex. 仕様が決まっていない、決まった仕様が参照できない、開発環境が破壊された
3. 当該案件によって **Organization の目的が果たせない** (ex. qiita へのアクセス権が得られない
4. 当該案件によって **ブレイクスルーが予想される** (ex. ライブラリの開発、新 API の発想、人材確保

**Comment by KEINOS** [comment]
KISS から始まるストーリー 😆 

それいいですね。どこかで使いましょう！
そして「簡潔・明瞭」は５大基本ルールに入れましょう。

> 開発が順調な時は
> 使用策定やドキュメント整備、クレーム対応（issue の解決等）の方がポイントが高く、
> LTL にトゥートを垂れ流しまくっているときは
> 新機能の打ち合わせよりも、不具合の修正または運用（BOT を止める）が高ポイント（=緊急）である、
> という認識でよいでしょうか。

**よい**でございます。項目をチェックした結果に違和感がある場合は「ポイントの重みが変わった」か「項目が足りない」ということなので、その場合はissueをあげてもらってラベルチームで議論してもらうといいと思います。

## 項目の案

1. 不具合である
1. 仕様が決まっていない
1. 実装作業が完全にストップしている

- 関連情報がない／見つかりにくい
- 機能の拡張である
- 被害が出ている
- 実装がストップしている（上記３と重複）
- Organization の目的が果たせない
- ブレイクスルーが予想される

最後の「ブレイクスルー」に関しては、緊急度と関係なく「ラベルチーム・チョイス」や「ピックアップ」みたいな**専用のラベルを用意していい**と思います。

**Comment by hidao80** [comment]
> 1. 不具合である
> 2.仕様が決まっていない
> 3. 実装作業が完全にストップしている
> - 関連情報がない／見つかりにくい
> - 機能の拡張である
> - 被害が出ている
> - Organization の目的が果たせない
> - ブレイクスルーが予想される

上記で始めて、運用しながら適宜ブラッシュアップの方がいいかもですね。曰く、事件は会議室で起きてるのではないそうなので。:)

> 「ラベルチーム・チョイス」みたいな専用のラベルを用意していいと思います。

うーん、ラベルチームの人間としては、開発チームとの温度差が極端に出そうで嫌な予感がします。

「経営陣が決めた優先順位は合理的でない」的な。あくまで3段階査定で、「同ランクならどれから手を付けてもいい」のがお互い精神衛生上よろしいかと。

**Comment by hidao80** [comment]
ウエイトポイントの暫定値が必要ですね。

**Comment by KEINOS** [comment]
重みポイントによる緊急度ですが、タスクの優先度には使ったことがなかったので paiza.IO でプロトタイプを作ってみました。（下記URLと図参照）

https://paiza.io/projects/yrd20tbK6h8qGdJnbit47A

その中で「**テーマ（メインの質問）の書き方が決まると項目も決めやすくなる**」のに気づきました。また、項目が決まるとウェイトの暫定値も決まりやすくなりそうです。

あと、余談ですが「[GitHub App](https://qiita.com/icoxfog417/items/fe411b94b8e7ae229e3e#github-apps)」なるものがあるらしく、GitHubのProject内にWebApp（ガジェット？）を埋め込めるらしいです。この緊急度算出系も将来埋め込めたら楽でいいですよね。（プライオリティは低めですが）

<img width="676" alt="2017-09-26 17 38 55" src="https://user-images.githubusercontent.com/11840938/30850801-aae09c92-a2e1-11e7-8c88-cfa2c9831106.png">

**Comment by hidao80** [comment]
プロトタイプ作成ありがとうございます！

なるほど、テーマ設定は盲点でしたね。近すぎて見えてませんでした。逆に考えると、テーマ設定とテーマごとの項目＆ポイントによって、ほかの意思決定も客観的かつシステマチックに行うことができる**汎用意思決定ツール**になるポテンシャルがあるのではないかと期待します。

ポイントの暫定値も私の感覚とあまり離れていないので、まずは @KEINOS さんの提案通りの採点で運用を始め、次の issue からの判定結果からフィードをバックを得て調整していきたいと思います。

こうなると、ラベリングチームは**ラベルを貼る**のが仕事ではなくて、**重みづけを調整する**のが仕事になりそうですね。
でも、「ラベル張りポカよけ」のために、ラベルを張るのはラベリングチームの仕事としておきましょう。

### Github Apps について

こんな機能があったとは！　上記の通り、緊急度がシステマチックに算出できるので非常に有効なツールになると思います。ほかにも「編集されやすい（commit数が多い）記事のタグ集計」「一度も修正されない記事まとめ」とかがあると、需給マッチ（コラボレータに人気・不人気の記事テーマ）が一目でわかって面白そうですね。

---------

重みの調整はラベリングチームが担当し、当面は私の独り部隊なのでちょこちょこ調整していきたいと思います。チームメイトが増えたら、issue を立てて調整するスタイルにしようと考えています。

以上で本 issue をクローズしてよいと思います。:thumbsup:

**Comment by KEINOS** [comment]
> 「ラベル張りポカよけ」のために、ラベルを張るのはラベリングチームの仕事

👍 

> 重みの調整はラベリングチームが担当
> チームメイトが増えたら、issue を立てて調整するスタイル

👍
