### ISSUE TITLE
Qiitaコラボ記事 のQiita側にコラボのコメントが付いた場合の対処

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#60]
## 相談

Qiitaコラボ記事は GitHub 上の Markdown をみんなで修正して Qiita に反映という基本動作でコラボする仕様になっています。

しかし、下記リンクのようにユーザの諸事情で **Qiita 側のコメントにコラボが来た場合**は、どのようにしましょう？
https://qiita.com/Qithub/items/17871e7f26c308ef6514#comments 

## 自分の案

以下の３パターンが考えられますが「３」番目が良いと思います。

1. **仕様を通す**<br>コメントでお願いして GitHub/Git でプルリクをあげてもらうようにお願いする。
2. **イレギュラー対応する**<br>2017/10/21現在、BOTによる自動更新がまだ実装されていないので、代理でダイレクトに修正してしまう。
3. **仕様を通す、が代理で**<br>「＠xxxxさんのコメントの内容を反映させました」として代理でプルリクをあげる。

## 補足
#13『Qiitaコラボ記事「記事原稿第1版が完成しているか』を BOT から判断する方法」が近い issue かと思いましたが、完成＆公開している場合の条件だったので別 issue として立てました。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

### 決定事項
- 記事のコラボ方法は以下の２通り
    - プルリクエスト（via GitHub）
    - 編集リクエスト（via Qiita）
- 「編集リクエスト」の検知は Qiita API で、定例 cron によりチェックを行う
- 「編集リクエスト」を検知した場合の対応は次項を参照

### 編集リクエストが来た場合の反映までの流れ（BOT 実装までの暫定対処）

1. **Qithub アカウントホルダー**（2017/10/23 現在 @KEINOS）によってリクエストを承認。<br>（Qiita記事にリクエストが反映される）
1. リクエスト者が新規「共同著者」の場合は、**手動**で共同著者欄に追記。
1. Qiita記事の内容を**手動**で GitHub の Qiitaコラボ記事 に反映。<br>（PR はせず master にダイレクトに反映）
1. 反映した旨はQiita側のコメント含め特に**行わない**。※

※ Organizationのメンバーは Qithub のメール（＝メーリングリスト）に登録されているため。

**Comment by KEINOS** [comment]
全体方針は、おいおい決めて行くとして、取り急ぎ上記の[Qiitaコラボ記事](https://qiita.com/Qithub/items/17871e7f26c308ef6514#comments)は 提案３ で 😎 ❓

**Comment by hidao80** [comment]
BOT が動き出すまでは案2で賛成です！👍

## 考察

案1、2、3の折衷案を考えました。次のような対応はどうでしょう？

すなわち、**コメントへのコラボは「編集リクエスト」してもらうように誘導**し、**編集リクエストを自動的に PR にする**のがベターだと思います。

Qiita 側に「編集リクエスト」という機能が存在する以上、**PR を通さない編集リクエスト** _(紛らわしい！)_ の方が**一般的なQiitaユーザには**直感的だと思います。  
「Githubを通す」or「コメントを本文にマージする」方がイレギュラーという認識です。

## 提案

もしQiita API で編集リクエストを検知したら、PR を自動的に立てることはできないでしょうか？

さすがにコメントが編集リクエスト相当かどうかを判断するのは難しいと思われるので、**せめてコラボレータからの編集リクエストを自動的に PR する** か、思い切って **コラボレータからの編集リクエストはレビューせずにマージする**でもいいかも知れません。

**Comment by KEINOS** [comment]
> 「Githubを通す」or「コメントを本文にマージする」方がイレギュラー

確かに。ピュアQiitaユーザーから見れば「GitHub」を通すのはイレギュラーですものね。

また、コメントで（編集内容を）アッピールされるよりは**Qiitaの「編集リクエスト」を活用**してもらう方がQiitaとしては健全ですね。

> Qiita API で（Qiita側からの）編集リクエストを検知したら、PR を自動的に立てる

これが今後の判断のキモになりそうですね。

> コラボレータからの編集リクエストはレビューせずにマージする

個人的には、**記事の原文は GitHub のリモート master で徹底**し、プルリク（PR）および編集リクエスト（ER？CR？）の両方からのリクエストにより GitHub の master が更新され、Qiitaにデプロイされるという KISS な流れにこだわりたいのですが、「編集リクエスト」は Qiita 内部の Git 的な仕組みを使っているので、Qiita 側の編集リクエストを破棄する工程が生まれてしまい、むしろ**工程的に KISS にならない**（煩雑になる）可能性もあります。

まずは、**Qiita API で GitHub リモート master の記事を Qiita 側に反映させる** 機能を実装して、この案件を進めていければと考えています。

P.S. TL;DR を更新しました。

**Comment by hidao80** [comment]
👍

そうですね、話をややこしくしてしまいました。😅

リーンスタートアップで「 **MVP (Minimal Viable Product)** のリリースを最優先して、ユーザからのフィードバックで製品の方向性を決めろ」という考え方を知ったので、

> まずは、**Qiita API で GitHub リモート master の記事を Qiita 側に反映させる** 機能を実装して、この案件を進めていければ

という方向性に賛成です！

細かい話は動くものができてから！ の方が楽しいじゃないですか😁

**Comment by KEINOS** [comment]
> 細かい話は動くものができてから！ の方が楽しい

👍  そうですね！仕様を決めてから動くのも大事ですが、**楽しい方がもっと大事**ですものね！

いずれにしても「編集リクエスト」を活用するのは盲点であり、Qiitaユーザー目線で大事なポイントだと思うので、そこらへんも追ってホジって行きましょう。

BOT が「編集リクエスト」を検知できたら、ここにお知らせするので、**方針が決まったら issue を close でどう**でしょう？

**Comment by hidao80** [comment]
## 方針案

BOT が対応できるようになるまで、下記方針で**手動対応する**。

a. コメントにコラボが来た場合  
→3.仕様を通す、が代理で
b. 編集リクエストが来た場合  
→**Qithub アカウントホルダーによって**リクエストを承認する

ってとこでしょうか。

👍なら close、対案もお待ちしてます。

**Comment by KEINOS** [comment]
(a)は 👍 。(b) も 👍 なのですが、以下の認識でよろしいですか？ノープロであれば close で。

### 編集リクエストが来た場合の反映までの流れ（暫定対処）

1. **Qithub アカウントホルダー**（2017/10/23 現在 @KEINOS）によってリクエストを承認。<br>（Qiita記事にリクエストが反映される）
1. リクエスト者が新規「共同著者」の場合は、**手動**で共同著者欄に追記。
1. Qiita記事の内容を**手動**で GitHub の Qiitaコラボ記事 に反映。<br>（PR はどうしましょう？しないなら master にダイレクトに反映で 👌 ❓ ）
1. 反映した旨はコメント含め特に**行わない**。※<br>（BOTが対応できるようになった場合、処理が増えるため。必要が出て来た場合は再考する）

※ Qithub のメーリングリストに通知が飛ぶため。（MLって届いてます？）

**Comment by hidao80** [comment]
ノープロです👍

質問に答えます。

1. PR は不要で良いと思います。Qiita 側でマージが承認されているため。
1. メーリングリスト、ラグがありますが届いてます。

**Comment by KEINOS** [comment]
👍 TL;DR に反映
