### ISSUE TITLE
Qiitaコラボ記事 のライセンスは？

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#63]
## 相談内容

PR #61 で話題になった、「コラボ記事のライセンスをどうする？」という問題を解決しましょう。

## 自分の案

クリエイティブ・コモンズの「表示ー継承」ライセンスが適当だと思います。  
以下の制限を明示できるからです。

1. 自由な改変を認めている
2. 改変の際、元著者のクレジットを求めている
3. 改変の禁止を制限している

## 補足

クリエイティブ・コモンズ <https://creativecommons.jp/licenses/>

## TL;DR（進捗・結論 2017/10/24 現在）

- 審議中

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
[![BY-SA](https://i.creativecommons.org/l/by-sa/4.0/88x31.png "BY-SA")](https://creativecommons.org/licenses/by-sa/4.0/deed.ja)
「表示ー継承」というと、これ ☝️ ですね。良い感じ。

Qiita記事のライセンスとのからみの記載はどうしましょう。
上記 CC-BY-SA 及び https://qiita.com/terms に同意するものとするのは、短絡的すぎでしょうか？

**Comment by KEINOS** [comment]
仕組み的には、GitHub側の記事をQiitaに公開しているので、下記 [Qiita規約](https://qiita.com/terms)の第９条５項がまんま当てはまりますよね。

> 第2項から前項までの規定にかかわらず、ユーザは以下のライセンスに準拠する投稿内容を本サービスに投稿することができます。その場合、投稿内容の権利については当該ライセンスの定めに従うものとし、ユーザは投稿内容が当該ライセンスに違反していないことについて当社に保証するものとします。
> 1. Creative Commons
>     a. 表示
>     b. 表示 - 継承 👈 
> 2. GNU GPL
> 3. BSDライセンス及び修正BSDライセンス
> 4. 前各号のライセンスに準ずるライセンスであって当社の認めるもの

**Comment by hidao80** [comment]
<https://qiita.com/terms> の9条5項にあるように、qiita 記事に許されたライセンス種類に CC-BY-SA が用意されているので、Qithub では「qiita の利用規約より CC-BY-SA を選択しました」と表示すると良いかもしれません。

もしくは、単に CC-BY-SA を表示して、qiita に投稿したものは qiita の暗黙的に利用規約に同意し、qiita に投稿されていないものは**qiita の利用規約に同意せずに CC-BY-SA とする**と良いかもしれません。

PR 中でマージされていないもの（Github に乗ってるけど、qiita に乗ってないもの）は not qiita && CC-BY-SA な感じです。

------

ところで、Qithub のアカウント利用方法が利用規約の8条3項2号に抵触してそうですが、大丈夫でしょうか？

Qithub のアカbanで済めばいいですが、 @KEINOS さんのアカウントにも影響あるのでは？ と ((((；ﾟДﾟ))))ｶﾞｸｶﾞｸﾌﾞﾙﾌﾞﾙ

**Comment by KEINOS** [comment]
> 8条3項2号
> ユーザーIDを共有する行為、当社の許諾無く1人でアカウントを複数保有する行為、当社が許諾する数を超えるサブアカウントを保有する行為

限りなく透明に近いブラックかも 😱 
BOTのフォロワーに内部の方がいるとはいえ、明示的に許諾を得たわけではないので、これは確認する必要がありますね。トゥートで確認してみます。

**Comment by hidao80** [comment]
👍🙆

**Comment by hidao80** [comment]
#64 が解決したので、こちらも Close します。

**Comment by KEINOS** [comment]
Qithub のアカウントの件は issue #64 で確認いたしました。（結果 👌 ）

さて、Qithub のライセンスですが

> qiita に投稿されていないものは**qiita の利用規約に同意せずに CC-BY-SA とする**と良いかも

Qiita未投稿のデータは上記でシンプルで 👌 なのですが、もし投稿時に合意を考えるとやはり総括的な記述が欲しいところです。

### 提案

- **Qiita記事末尾に以下を明記**
    - 共同著者一覧
    - ライセンス・ロゴ（BY-SA）とQithub/items/LICENSE.mdへのリンク
- **LICENSE.mdの内容**<br>以下の概要だけを記載したファイル。
    - Creative Commons BY-SAであること＆リンク
    - [Qithubのコンセプト](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md#qithub-3-つの-moe-注more-のもじり)（帰属意識の向上）によりQiitaとQiitadonでも利用されるため、あらかじめ了承しておくこと
    - ライセンスに関する疑問がある場合は早めに issue で議論すること＆issueへのリンク

**Comment by KEINOS** [comment]
Oops! タッチの差 🤣

**Comment by hidao80** [comment]
👍🙆

LICENSE.md の共著者一覧を Github の Commit リストから自動取得できると幸せになりそうですが、必須ではないので後回しで。😅

記事末尾の必須事項は README.md にも書いておいたほうがいいかもですね。😁

LICENSE.md のたたき台はこちらで用意しましょうか？ @KEINOS さんにイメージしているものがあるならおまかせしたほうが良い？

**Comment by KEINOS** [comment]
> LICENSE.md のたたき台はこちらで用意しましょうか？

🙏
