### ISSUE TITLE
Qithub のアカウントが qiita の利用規約に抵触しているかもしれない

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#64]
## 相談内容

#63 より

Qithub のアカウント利用方法が利用規約の8条3項2号に抵触してそうですが、大丈夫でしょうか？

Qithub のアカbanで済めばいいですが、 @KEINOS さんのアカウントにも影響あるのでは？

## 自分の案

かなり苦しい解釈で、qiita 側の出方にはよりますが、次の様な言い訳が成り立つと考えられます。

1. Qithub のアカウントホルダーは @KEINOS のみで、ユーザーID の共有はしていない。
1. @qithub は @KEINOS のサブアカウントで、 @KEINOS は一人で複数アカウントを保持していない。
1. 「記事の共有」は CC-BY-SA に則って行われているものであり、「編集リクエスト」に相当する。\
@qithub の記事に対して編集リクエストを行う機能を Github にアウトソースしているにすぎない。

これらの言い分が通れば、規約には抵触していないことになります。苦し言い訳ですが、なんとかなるかもしれません。

## 補足

qiita 利用規約より抜粋；

> ### 第8条(禁止事項)
> (中略)
>(2)ユーザーIDを共有する行為、当社の許諾無く1人でアカウントを複数保有する行為、当社が許諾する数を超えるサブアカウントを保有する行為

## TL;DR（進捗・結論 2017/10/27 現在）

- 2017/10/27 11:50現在
    - Qiita 運営側より現在時点での了承は得た。
    - 今後、規約の改変により制限される可能性はある。（規約がBOT想定外であるため）
    - 了承情報： https://qiitadon.com/@KEINOS/98898555733495258

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
Qiitaの方に相談いたしましたが、以下のような返答をいただき、**現状は大丈夫**とのこと。

ただし、やはりグレーではあるものの想定外であるため、BOTの投稿内容や活動によっては制限がかかる可能性があることを念頭におかなければなりません。

> 厳密に言えば抵触するかとは思いますが、そもそも規約がBotなどの運用を想定したものではないこともありますので、現時点では特にご対応頂く必要はないかと思います。（その他の規約に抵触する行為を行う目的でないならば、特に。）

<img width="558" alt="2017-10-27 11 52 00" src="https://user-images.githubusercontent.com/11840938/32086028-87a56714-bb0d-11e7-9996-cf6774d6cca7.png">

引用元： https://qiitadon.com/@KEINOS/98898555733495258 （2017/10/27 11:50）

内容をご確認いただき、Qithub の Qiita アカウントに関する懸念事項が今のところなければ Close で！

P.S. TL;DRも更新

**Comment by hidao80** [comment]
👍🙆

**「現時点で対応の必要なし」** とお墨付き頂いたので安心しました。

問い合わせしたいだだいてありがとうございます。😄 お手数おかけしました。
