### ISSUE TITLE
Qiitaコラボ記事 「はじめての Qiitadon」をアドベント・カレンダー用に

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#69]
## 提案

Qiitaの今年（2017）のアドベントカレンダーでトピックに「[Mastodon](https://qiita.com/advent-calendar/2017/mastodon)」があるので、**あえて Mastodon ではなく Qiitadon に特化した Qiitaコラボ記事を書きたい**です。

## 自分の案

1. **内容**<br>以下を対象としたユーザーに、「やさしく説明」できて「楽しそう」と思ってもらえるもの。
    - これからマストドンをはじめたいユーザー
    - 他のインスタンスから来たユーザー

2. **コラボ方法**<br>[専用のブランチ](https://github.com/Qithub-BOT/items/tree/My_First_Qiitadon-Qiita-Advent_Calender_2017)をみんなのコミットで叩き上げる
    - ブランチ名：[My_First_Qiitadon-Qiita-Advent_Calender_2017](https://github.com/Qithub-BOT/items/tree/My_First_Qiitadon-Qiita-Advent_Calender_2017)
    - コミット優先度： 先にコミットしたもの勝ち。全消しなど、明らかにやりすぎな場合意外は、どんどんブランチにマージする。
    - 誤字脱字などの修正：遠慮なく行う。
    - 注意点：必ず fetch, merge してから編集→コミットすること。

3. **記載方法**<br>ダラダラと文書を書くのではなく**Qiitaスライド方式**でどうでしょう？

## 補足

- 注意点
**Qiitadonの運営側で明示されていない「暗黙のルール」は、記事内でルールのように記載しないこと**が大事だと思います。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/12/08 現在）

- [Qiita記事にて公開済み](https://qiita.com/Qithub/items/eb1bf516f4d26e959937)

**Comment by hidao80** [comment]
LGTM👍😄

Qithub の使いでのあるテーマですね！

Qiitaスライドは初見ですが、Qithub と相性よさげでいいですね👍

ものは試し、やってみましょう😄

**Comment by KEINOS** [comment]
ブランチ [My_First_Qiitadon-Qiita-Advent_Calender_2017](https://github.com/Qithub-BOT/items/blob/My_First_Qiitadon-Qiita-Advent_Calender_2017/eb1bf516f4d26e959937.md) に叩き台をコミットしてみしたー

**Comment by hidao80** [comment]
ブランチを master にマージするデッドラインがあった方がいいかしら？

「12/1 AM 7;00 のコミットまで」とか。

デッドラインの設定値がブラック企業のソレですが。

**Comment by KEINOS** [comment]
ある程度書きあがったら、とっとと master にマージしちゃって、Qiitadonユーザーに公開しても良い気もします。それで参加がなくてもそのまま公開しちゃう感じで。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
https://qiita.com/Qithub/items/eb1bf516f4d26e959937 にて公開済みなのでクローズして良いかと思います。

以降は、根本的な問題がなければ適宜 PR するってことで。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
👍 では、クローズしまーす。
