### ISSUE TITLE
ラベル を貼る時のタイミングのルール

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#7]
自己判断でラベルを付けると危険・誤解を招くと思うので、以下のラベル付けのルールはどうでしょうか。

- issueを立ち上げた直後にはラベルを貼らない
- ラベル付けは本人以外（将来的には担当者）が行う

**Comment by hidao80** [comment]
良いルールだと思います。

より良くするために、第一条をこう改変したいです。

-  issueを立ち上げた直後には __優先度ラベル__ を貼らない

トリアージも医師（有資格者）がやるものなので、「カテゴリは投稿者が決める」、「優先度は担当者が付与する」と混乱が少ないと思います。

**Comment by hidao80** [comment]
う〜ん、上記アイデアでは肝心のポカよけになりませんね…

ポカよけを「設定より規約」で実装するためには @KEINOS さんの素案がベストだと思います。

ラベリングチームは Project のカンバン方式では肝になるセクションなので、プロジェクトのマイルストーンが見えている人にお願いしたいですね。:)

**Comment by KEINOS** [comment]
私より、 @hidao80 さんの方が適切にラベリングできると感じているので、中間をとって以下のようにしてはどうでしょう。

- issueは「ラベルなし」でスタートさせる
- 「WriteUser」チームを「ラベリング担当」に変名＋ @KEINOS をチームから除外
- 「ラベリング」は「ラベリング担当」チーム（ 現在 @hidao80 のみ）にまかせる

そして、嬉しいことに**メンバーが増えたら Role を再考する**ということでいかがでしょう？

**Comment by hidao80** [comment]
上記意見に賛成です。All Collect です。

**Comment by KEINOS** [comment]
以下を実行しました

- チーム名を「ラベルチーム」に変更
- @hidao80 をチームのメンテナに昇格（メンバーの追加・削除などの権限）
- @KEINOS をチームから除外

https://github.com/orgs/Qiita-BOTch/teams/team/members
