### ISSUE TITLE
items と scripts に共通のファイルを変更しました。scripts に適用しませんか？

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#73]
## 提案

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE.md
- LICENSE_en-US.md
- CODE_OF_CONDUCT.md

を編集し、PR をあげました。

これらの変更を Qithub-BOT/scripts に適用しませんか？

#70 , #71 , #72 

## 自分の案

提案の通りです。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/11/05 現在）

- PR Qithub-BOT/scripts/pull/36 で`scripts`にも適用済み
- LICENSE.md を[公式のライセンス文書](https://choosealicense.com/licenses/cc-by-sa-4.0/)に差し替えてリポジトリにライセンスが適用されたのを確認済み
- 今までの要約は「LICENSE_OUTLINE.md」に和文・英文を統一

**Comment by KEINOS** [comment]
"LICENSE.md"ですが、リポジトリ作成時以外でライセンスを適用させるには、[ライセンス一覧](https://choosealicense.com/appendix/)に掲載されている文面と同じにしないとAPIが自動検知せずトリガーされないようです。

https://help.github.com/articles/licensing-a-repository/#detecting-a-license

"LICENSE.md"を[ライセンス文](https://choosealicense.com/licenses/cc-by-sa-4.0/)に差し替えてプルリクしてみますね。 → PR #74

**Comment by hidao80** [comment]
👍😁

キてますキてます、来まくりやがってます！

![クレジットされてる図](https://drive.google.com/uc?export=view&id=1rdGVJDaGLyXggjvxvBD6VvPEN-ZlG6gy)

**Comment by KEINOS** [comment]
きましたね！

今までのライセンスの概要は良い感じで要約されていると思うので、それら日本語と英語を１つのファイルにまとめて「LICENSE_OUTLINE.md」としてはどうでしょう？

**Comment by KEINOS** [comment]
#77 で PR をあげてみました。よろしくご検討ください。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
マージ thx! TL;DR に反映しました。

**Comment by hidao80** [comment]
👍LGTM😊
