### ISSUE TITLE
ルール （制定済みルール）の置き場

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#8]
issueを通して制定されたルールなど、最終的にはQiita記事にとりまとめるとして、クローズされたissueの中から探すのが後々大変と予想されます。

例えば、Projectに「制定済み（記事作成待ち）」といったカラムを追加してはどうでしょう？（カラム名は冗長ですが）

もしくは「制定済み」といったラベルとか。

**Comment by hidao80** [comment]
総論賛成です。

一つ提案です。

Project に「記事作成済み」というカラムを作って、記事作成が済んだ note (or issue) を __すべて__ (scrips のドキュメント化済み含む) そのカラムに移動する、と言うのはどうでしょう？

すなわち、「items カラムにあって、クローズしている note (or issue) はドキュメント化されていない（早くしろ）」と言うイメージです。

**Comment by hidao80** [comment]
スミマセン、scripts は混ぜないほうが良さそうです…

**Comment by KEINOS** [comment]
「制定済み」より「記事作成済み」の方が**ゴールは同じでも先まで見えていい**ですね。成果物感も増しますし。

「減ると嬉しいもの」と「増えると嬉しいもの」を考えると、「記事作成済み」は後者に該当すると思います。

ただ、懸念としては、それは内部のメンバーの達成感の現れだけで、新しく来た人が「げ、こんなにルールあるの？」と躊躇してしまわないか心配です。

## カードを増やす方向より減らす方向

提案としては「 Project 内は看板が少ない方が健全」といったシンプルなルールにして、**カラム名は「記事作成済み」→「記事作成待ち」にしてはどうか**しら。

また、それにあわせて、記事作成・クローズされた issue などの**成果や実績は別枠でキチッと皆の頑張った感が出る工夫を検討**して、クローズ案件はどんどん Project から消す方向にしてはどうでしょう。

## ルールに関する個人的な意見

個人的には、「ルールを守らせるためには、ルールがわかりやすくないといけない」と思っていて、それは内容だけでなく確認する場所も含めてわかりやすくしたいです。

基本ルールは至極シンプル（５か条くらいのイメージ）にして、あとは判例のように issue で都度対応していく、くらいが良い気がします。

issue 番号を含めると該当 issue にリンクしてくれる便利な仕組みを活用して、判例 issue から該当基本ルールの issue 番号を振ってリンクさせる、みたいな。

**Comment by hidao80** [comment]
### 制定済み issue 看板処理の件

記事作成待ちカラムに賛成です。

「Project から看板を減らしても issue は消えない」という事実を失念していました。看板は少ない方がいいです。ToDo に集中するのが Project の役割だと認識しています。

Done はレビューには有効ですが、それは issue のスレッドでやれば良いことで、Project の画面でやることではないと考えています。

Done 看板は Project から消しましょう。

### 基本ルール管理ポリシーについて

> 基本ルールは至極シンプル（５か条くらいのイメージ）にして、あとは判例のように issue で都度対応していく、くらいが良い気がします。

同意です。「コラボレータ全員が記憶できるルール」は「コラボレータ全員が運用できるルール」になると確信しています。

基本ルールは「べからず集」にせずに「行動指針」にできるとやらされ感がなく、気持ちよく同じ向きを向けて良いと思います。

楽しくコラボできるコミュニティーになると素敵ですね。:)

**Comment by hidao80** [comment]
他のissueも含めて仮定・確定した事項をドキュメントにまとめたいのですが、本issueが解決していません。

## 提案

A. items に「合意文書ディレクトリ」を作りませんか？
B. items に「合意文書 qiita 記事」を作りませんか？

とにかく、現在のメンバーでもクローズしたissue件数でも二桁に近づいており、一つのissueで複数の項目が合意されています。

何とかして、**一刻も早く合意部分だけ**を共有空間上に残したいと考えています。

A案 は、即効性がありますが、リポジトリがよごれます。
B案は、**私が記事を振り出せませんが**、他のドキュメントとなじみ、リポジトリが汚れません。

ご意見お待ちしています。

**Comment by KEINOS** [comment]
> A. items に「合意文書ディレクトリ」を作りませんか？
> B. items に「合意文書 qiita 記事」を作りませんか？

    @KEINOS は B案に 👍  賛成です。

昨晩Qiitaのアカウントを作成したので、取り急ぎQiita上から手動で「限定公開文書」を新規作成し、その記事IDでリポジトリにも作成しました。「[1a52282f0b132347c2b1.md](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md)」です。

これって @hidao80 さんのアカウントでGitHub上から編集ってできますか？

Qiita側は https://qiita.com/Qithub/private/1a52282f0b132347c2b1 です。

**Comment by hidao80** [comment]
@hidao80 のアカウントで、Github 上で編集 & プルリクできました！

プルリクにも書きましたが、Github 上で Markdown による記事編集が可能になるため、Github 最大の障壁である**git クライアントの使用**から解放されます。

ブランチの運用方法については啓蒙する必要がありますが、ブラウザと通信環境があればどこからでも（スマホからでも！）記事編集ができるのはとても良いと思います。:thumbsup:

本 issue を解決とし、クローズすることに同意します。
何かあれば、引き続きコメントお願いします。

**Comment by KEINOS** [comment]
<img width="1019" alt="2017-09-27 2 33 50" src="https://user-images.githubusercontent.com/11840938/30875097-51b0bc1e-a32d-11e7-8988-c7546d72ac8c.png">

おぉぉ。プルリクられてる！ 👏 👏 👏 👏 
やっぱりGistっぽくブラウザで編集できるのは強みですね。

> ブランチの運用方法については啓蒙する必要があります

そうですね。それはまた別 issue を立てるとして、とりあえずクローズしまーす。
