### ISSUE TITLE
Organization から各リポジトリへの導線

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#82]
## 提案

- Qiita記事のコラボには`items`リポジトリ
- Qithub の BOT開発コラボには`scripts`リポジトリ

わかりやすいのですが、[Organization トップ](https://github.com/Qithub-BOT)から各々のリポジトリへの導線がないので、何か欲しい。

## 自分の案（１）

１ページものでもいいので GitHub Pages があればいいなと思います。

### 設置方法

`qithub.github.io`というリポジトリを作成すればいいらしいです。

### 内容

Organization トップは簡単な概要と各リポジトリへのリンクと Qithub のロゴ程度のもの。

### タイミング

設置＆公開するとしたら Qithub-BOT/scripts/issues/66 の `items`を Qiita へデプロイできるようになってからが良いかと。やるらなリポジトリは先に作っちゃってもいいかも。

## 自分の案（２）

GitHub Pages はもう少しメンバーが増えてから再検討するとして、 https://github.com/Qithub-BOT の Organization 上部の説明文に Qiita記事のリンクを貼るだけでもいいかもしれない。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2018/04/14 現在）

- GitHub Pages は不要。
    - リポジトリ名が `items` → `Qithub-ORG` に変わり、窓口が明確化された
    - Qithub-ORG リポジトリの中身 = https://qithub.tk/ であるため GitHub pages は不要

**Comment by hidao80** [comment]
Github Pages 良さげですね！

案（1）は現在の [Organization のトップページ](https://github.com/Qithub-BOT)と変わらない気がするのですが？

案（2）の「Qiita 記事へのリンク」が、**リポジトリ内の各記事への直リンクのリスト**のことだったら [Qithub-BOT/items](https://github.com/Qithub-BOT/items) ページと同じことなのでそれはどうかと思います。

念のため、私の環境（iPad、Chromeブラウザ）から見えているスクリーンショットを添付しておきます。

![iPad Pro から見える Organization のトップページ](https://user-images.githubusercontent.com/8155294/33244513-14b8aba2-d33c-11e7-82d9-911ee33f3d47.png)

### タイミング

**記事を書いてもらうのは、BOT が動き出す前でも構わない**と思いますので、すぐにでも作って公開しても問題ないと思います。

**Comment by KEINOS** [comment]
> 案（1）は現在の Organization のトップページと変わらない気がするのですが？

本当ですね。どうやら少し勘違いをしていたみたいで、`qithub.github.io`のリポジトリを作成すると https://qithub.github.io というドメインが用意されるというだけで、Organizationのトップ https://github.com/Qithub-BOT/ の表示は変わらないみたいです。（リポジトリが１つ増えただけ）

いずれにしても https://Qithub.GitHub.IO/ を用意して（`qithub.github.io`リポジトリを作成して）Qithub のウェルカムページとして以下の内容で GitHub Pages を利用するという方向でいいでしょうか？

### https://Qithub.GitHub.IO/index.html に含める内容

- Qithub のロゴ
- `items`リポジトリの説明
    - README.md へのリンク
    - issue へのリンク
- `scripts`リポジトリの説明
    - README.md へのリンク
    - issue へのリンク
- Qithub 設定資料集へのリンク

**Comment by hidao80** [comment]
ぬぬぬ。少し言葉が足りなかったみたいですね。😅

案（1）に対する「現在の Organization のトップページと変わらない」というのは、新たに作る Github Pages のコンテンツの量と質のことです。

現 Organization トップページにも

* Qithub のロゴ
* items リポジトリページへのリンク（≒README.md へのリンク）
* items リポジトリの概要
* scripts リポジトリページへのリンク（≒README.md へのリンク）
* scripts リポジトリの概要

があるので、特に必要性を感じませんでした。🤔

ただ、実際に Qithub-BOT.github.io を見てみると考えが変わるかもしれない（想像を上回る）と思いますので、まずはやって見ましょう！👍

私は Github Pages で表現したいもののイメージができないので、 @KEINOS さんたたき台を作ってもらえますか？

P.S.
ジャストアイデアですが、リポジトリ名がサブドメイン名になるということは、「Qithub-BOT.github.io」ではなく、「qithub.github.io」になる（「-BOT」が外れる）ということですよね？  
それだけでも価値があるかもしれません。

**Comment by hidao80** [comment]
Github pages、要りますか？

私は 2018/04/14 現在、不要だと考えます。Organization のトップページで十分だと感じるからです。

不要だと思われれば、👍と close 🙇‍♂️💪

**Comment by KEINOS** [comment]
Qithub-ORG とわかりやすくなっただけでなく、Qithub-ORG のリポジトリ = https://qithub.tk の DocumentRoot となるため、いずれにしても **Github pages** は不要ですね。

Close し 💪
