### ISSUE TITLE
issue のテンプレのタイトルに関して（提案・相談・質問内容）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#84]
## 提案

issue のテンプレを以下にしてどうでしょう？

```diff
- ## 提案・相談・質問内容
+ ## 提案・相談・質問・報告
```

## 自分の案

Qithub-BOT/scripts/issues/69 で、不具合とバグの違いに関する言及がありました。

それが**不具合なのかバグなのかは内部の人が決めるべき**であり、issue を開いた時に「虫」が見えるのは精神衛生上よくないため、テンプレ側で予防策を取りたいと思いました。

## TL;DR（結論 2017/12/08 現在）

- 採用。テンプレのタイトルを`提案・相談・質問・報告`に。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
👍

返事が遅れてしまって申し訳ないです。

😎👌❓

**Comment by KEINOS** [comment]
👍 の、PR #86 をマージ＆クローズで遅れマスター

**Comment by hidao80** [comment]
👍
