### ISSUE TITLE
Organization の公式ドメイン「Qithub.tk」の取得と情報

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#87]
## 報告 & TL;DR

Qithub-BOT/scripts/issues/79 で提案されていた、Qithub のドメインを以下で取得しました。問題なければ、ドキュメント化の Close でお願いし 💪 。

### Organization の公式ドメインについて

| 項目名 | 内容 | 備考 |
| :--- | :--- | :--- |
| ドメイン名 | Qithub.tk | Freenom の12ヶ月無料アカウント |
| ドメイン名制定日 | 2017/12/18 |  Qithub-BOT/scripts/issues/79 |
| ドメイン取得日 | 2017/12/21 | |
| 取得担当者 | @KEINOS | |
| 登録メアド | qithub@keinos.com | Qithub メンテナのメーリングリスト |
| 登録パスワード | @KEINOS へ問い合わせ | 要共有方法の検討 |
| 登録名 | KEINOS Qithub | 氏：Qithub ／名：KEINOS |
| 組織名 | Qithub-BOT @ GitHub | |
| SSL | Let's Encrypt での利用を予定 | |

### サブドメインについて

現在、以下のサブドメインが決定しています。なお、サブ・ドメインの詳細や取り扱いに関しては、プログラムと密接であるため [scripts の issue](https://github.com/Qithub-BOT/scripts/issues) で取り扱うこととします。

| サブ・ドメイン名 | 用途 | 備考 |
| :--- | :--- | :--- |
| なし | Qithub のトップページ | 1ページもの概要ページ。各リポジトリへの導線として。 #82 |
| api | Qithub の本番環境 | Qithub RESTful API のルート・エンドポイント。Qithub の外部WEBサービスの窓口として |
| dev | Qithub の開発環境 | Organization のメンバー毎にディレクトリが用意され、各自のフォーク・リポジトリが実行できる。Origin への PR 前の各自のテスト環境として。|
| * | その他のサブ・ドメインは、ドメインなしに転送 | ワイルドだろぉ? |

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue
    - #82 
    - Qithub-BOT/scripts/issues/79

**Comment by hidao80** [comment]
👍

ドキュメント化は任せろー😁

> ワイルドだろぉ？

🤣

**Comment by hidao80** [comment]
👍

**Comment by hidao80** [comment]
[wiki に反映しました](https://github.com/Qithub-BOT/Qithub-ORG/wiki/%E5%85%AC%E5%BC%8F%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)ので close し💪
