### ISSUE TITLE
Qiitaコラボ記事 の記述フォーマットについて（タグとライセンス）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#89]
## 相談

> 記事のタグの記述の仕様とライセンスの挿入ルールについてルールを固めたい

### タグに関して

> 記事の３行目にタグを`[tag1, tag2, tag.., tag5]` のフォーマットで良いでしょうか

現在の暫定仕様として上記のようにクォーテーションなしで記述すると、最初の５つ、DEV環境の場合は４つ＋「test」が記事のタグとしてデプロイ時に変換されるようにしています。

というのも、未実装ですが `tag1:version` の場合の処理のこともあり`タグ:tag1, tag2...` の記述は使っておりません。

が、Kobito を使っていて思ったのですが**カンマ区切りではなくスペース区切り**でもいいのではないかと感じています。

例） `[tag1 tag2 tag3 tag4 tag5:2001]` 

### ライセンスの挿入に関して

> `この記事はQiitaユーザーのコラボ記事です。[GitHub](https://github.com/Qithub-BOT/items)にプルリクをあげると編集できます。`

現在は上記の文を手動で入れるようにしていますが、以下の2点を決めたいです。なお、コラボレーターに関しては GitHub から引っ張ってこれるようになってから別途議論したいと思います。

1. 文言がしっくりこないので適切なものにしたい（ロゴも含めて）
2. ライセンスを挿入する場所は文頭か文末がいいか
3. ライセンス挿入タグを用意するべきか、自動挿入にすべきか

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue #63「Qiitaコラボ記事のライセンスは？」

----------------

## TL;DR（進捗 2017/12/23 現在）

1. タイトル：１行目に記載すること（２行目は空行のこと）
    - 記述方法： `#`で始まること（GitHub上のプレビューのため）
2. タグ：３行目に記載すること（４行目は空行こと）
    - 記述方法：審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )
3. 本文：５行目から記述すること
4. ライセンス：審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

**Comment by hidao80** [comment]
## タグに関して

スペース区切りに👍

大カッコでくくられているのは、システム上の理由でしたっけ? Kobito 準拠? もしかしたらカッコも不要かもしれません。

## ライセンスの挿入について

> この記事はQiitaユーザーのコラボ記事です。[GitHub](https://github.com/Qithub-BOT/items)にプルリクをあげると編集できます。

カタカナ語的には上記は**ライセンスと言うより、クレジット**のように見えます。クレジットのイメージは以下の通りです。

> 新聞の外電記事の入手先の外国通信社名。普通、記事の初めに書く。

(Wikipedia より引用)

文字通りライセンスなら、CC-BY-SA 4.0 のミニバナー(<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>)を貼っておけば良いと思います。

私の言うクレジットを意識されているのであれば、@KEINOS さんが書いたライセンス文で問題ないように感じます。

#### 案A

1. ライセンス文への編集は特に必要ないと感じます。それと、ロゴって何？
2. 文頭に👍。これはリスクでもありますが、 **Qithub コラボ記事であることを[ファーストビュー](https://webtan.impress.co.jp/g/%E3%83%95%E3%82%A1%E3%83%BC%E3%82%B9%E3%83%88%E3%83%93%E3%83%A5%E3%83%BC)に出し、「記事のクオリティをQithub が担保している」(=ブランディング)** することができそうだと考えています。文末だとそれが難しいと思われます。
3. 自動挿入に👍。Qithub 活用事例であることを Public Relations したいです。

**Comment by KEINOS** [comment]
おっと！！去年タブレットから返信していたつもりが、投稿されていなかったようです。すみません！

> 大カッコでくくられているのは、システム上の理由でしたっけ? Kobito 準拠? もしかしたらカッコも不要かもしれません。

タグのない記事でも`[]`で済むようにタグの行だよという程度のものですが、そもそも **3行目はタグ行として仕様上必須**なので、**カッコは不要**にしましょう。

> それと、ロゴって何？

ライセンスバナーのことです！ 🙇  クレジットとライセンスをなんかゴッチャにしていました。

### 整理

- クレジット：Qithubによる Qiitaコラボ記事である旨を明記した記載
- ライセンス：CC-BY-SA-4.0 のバナー＆リンク

### 文頭に挿入

👍 

### 自動挿入（クレジットとバナー）

> <kbd><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a> この記事はQiitaユーザーのコラボ記事です。[GitHub](https://github.com/Qithub-BOT/items)にプルリクをあげると編集できます。</kbd>

👍 

### クレジットの記載について

自動挿入に 👍 なので、いつでも変えられるため、いま決定しなくてもいいのですが、 Qithub-BOT/items/issues/60 のQiita 側の「編集リクエストも受け付ける」（Qiitaユーザーにはそっちの方が馴染みやすい）ということだったので、コラボの仕方の記事を書いて、そこにリンクを貼るのがいいのかなとも感じました。

**Comment by hidao80** [comment]
### 自動挿入（クレジットとバナー）

👍 

### クレジットの記載について

👍 。コラボの仕方を Qiita 記事にするのもアリですが、github への導線として **github 側に `collaboration.md` を作ってそちらを参照(リンクを貼っておく)してもらう**のもアリかもしれません。

ご意見お待ちして 💪 。

**Comment by KEINOS** [comment]
> github への導線として github 側に collaboration.md を作ってそちらを参照(リンクを貼っておく)してもらうのもアリ

なるほど。そちらの方がいいですね！ 👍

**Comment by hidao80** [comment]
本 Issue は、以下の内容で問題なければ wiki にまとめて close したいと思います。
👌でしたら close 🙇‍♂️💪

- タグは Markdown ファイルの3行目に、スペース区切りで先頭から4つ目までを採用する。
    - 5つ目はシステムが予約している。6つ目以降は無視する。
- クレジットは文頭に自動挿入する。

プレビュー：
> <kbd><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a> この記事はQiitaユーザーのコラボ記事です。[GitHub](https://github.com/Qithub-BOT/items)にプルリクをあげると編集できます。</kbd>

**Comment by KEINOS** [comment]
👍
