### ISSUE TITLE
BOT のネーミングとアカウント作成

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#9]
BOTのアカウントを作成するにあたり動きだすと戻しにくいので、立ち上げメンバーに**ネーミングに関して意見がないか**の確認をしたいです。

現在のネーミングは「BOTch」ですが、以下の意味合いがあります。

- 【ぼっち】一人ぼっちで頑張るヤツだから
- 【Botch】英語で「できそこない」「やらかした」など
- 【BOT】BOTなので
- 【ch】Channel。Qiita, Qiitadon, GitHub, QiitaユーザーのHUB的な役割

ダメダメBOTを「みんなでコラボして使えるヤツにしていく」ことができればいいな、と。

ただ、**いささか自虐的すぎるかな**とも感じています。

他には以下のような名前も考えましたが、上記が無機質さ含め適度な塩梅と感じました。

- 【Qiitayan】Qiitanに対抗？関西風。キャラ色が強い。
- 【Qiitaro】関東風。キャラ色が強い。ダサい
- 【QiitaBOT】まんまだけど、Qiita記事に特化しているイメージ
- 【QiitadonBOT】同じく、まんま＋ネーミング長い
- 【Qiitabiliter】Qiita+Quitability（公平性）。ネーミング長い
- 【QiitaX】 わけわかんない

**Comment by hidao80** [comment]
「Botch」、個人的には好きなんですが、コラボレータにネガティブな感情を引き起こす可能性を強く感じます。

で、対案。

1. Q-Botch：Qiita、Qiitadon感を出しつつ、原題も活かす
2. Qithub：Github、Qiita、Qiitadonのエッセンスを混ぜつつ、各システムやコラボレータ間の「Hub」たるべしという初志を活かす
3. Qithub-Bot：2. のコンセプト+Botであることを強調する

どや。

**Comment by KEINOS** [comment]
BotQiitaとか！


・・・いや、失礼。

> コラボレータにネガティブな感情を引き起こす可能性を強く感じます。

そうなんですよねぇ。私も個人的には好きなのですが、、、。

１つ、こだわりとしては「Botch」を使う場合は「BOTch」と「BOT」を大文字にしたいです。
「Botch」だとエグいので。

「BOTch」であれば「ぼっと、チ・・チャンネ・・ル？」と「ハッチポッチステーション」的な何か、と勘違いしてくれる人がいるかと（ #いねーよ ）

対案のなかでは

    Qithub

がいいですね。

次点は「Qithub-Bot」ですが、発音すると全部混ぜの「Qithubot」と「PubSubHubbub」みたいに舌をかみそうです。

Qiita, Qiitadon色を強めるなら「QiitHub」ですが、上記と同じく発音したときに「ィー」となりそうなので、「Qithub」で「Have a Qithub！」くらいがいいかも。

その場合「BOT」色より「HUB」（つながる）色が強くなるので、いいかも。

Qiitaユーザーをつなげるのが目的なわけだし。

**Comment by hidao80** [comment]
bot 名を「Qithub」、qiitadon ユーザ名（アカウント名じゃないよ！）を「Qithub (bot)」とかでどうでしょう？

きっとかわいく擬人化してもらえることでしょう。:)

**Comment by KEINOS** [comment]
決定！

# 命名「Qithub」
- 表示名：Qithub(bot)
- Qiitaアカウント名： qithub
- Qiitadonアカウント名： qithub

以下を実行したらCloseします。

- Organization名（URL）変更
- Qiitaアカウントの作成
- Qiitadonアカウントの作成

**Comment by KEINOS** [comment]
## 進捗
Organization名を変更しましたが、「Qithub」が取られていた（アカウントはBANだった）ので「**Qithub-BOT**」で登録しました。

以降の正式URLは

    https://github.com/Qithub-BOT/

になります。

- [x] <del>Organization名（URL）変更</del>
- [ ] Qiitaアカウントの作成
- [ ] Qiitadonアカウントの作成

**Comment by KEINOS** [comment]
## 進捗（Qiita）
- [x] <del>Organization名（URL）変更</del>
- [x] <del>Qiitaアカウントの作成</del>
- [ ] Qiitadonアカウントの作成
---
## 詳細

えっと、、、私はロボットなんですけども。

<img width="765" alt="2017-09-25 19 28 47" src="https://user-images.githubusercontent.com/11840938/30804940-4f232116-a22a-11e7-9471-9d504fad7ddf.png">

## Qiitaのアカウントを作成しました

<img width="779" alt="2017-09-25 20 07 12" src="https://user-images.githubusercontent.com/11840938/30805646-42faea74-a22d-11e7-9ba2-23befbb7ec7e.png">

## プロフィール情報

| 項目名 | 設定値 |
| --- | ---|
| 名前：姓 | （空欄） |
| 名前：名 | Qithub(bot) |
| 公開メールアドレス| 非公開 |
| サイト/ブログ | https://github.com/Qithub-BOT/ |
| 所属している組織・会社 | Qithub-BOT @ GitHub |
| 居住地 | Japan |
| 自己紹介 | QiitaとQiitadonのユーザ間コラボレーションを支援するためのBOTをQiitaユーザーで作るためのGitHubのOrganization用アカウントです。|
| Facebook ID | （空欄）|
| LinkedIn ID | （空欄） |
| Google+ ID | （空欄） |

## アカウント情報

<img width="774" alt="2017-09-25 20 08 52" src="https://user-images.githubusercontent.com/11840938/30805697-7d9217b6-a22d-11e7-8e92-178b0e0d2b7b.png">

| 項目名 | 設定値 |
| --- | ---|
| ユーザ名 | Qithub |
| 登録メールアドレス | `qithub@keinos.com` |

## ユーザー画面

https://qiita.com/qithub

<img width="780" alt="2017-09-25 20 10 57" src="https://user-images.githubusercontent.com/11840938/30805746-bdb7e00a-a22d-11e7-8403-78371f9b3ebe.png">

**Comment by KEINOS** [comment]
## 進捗（Qiita）
- [x] <del>Organization名（URL）変更</del>
- [x] <del>Qiitaアカウントの作成</del>
- [x] <del>Qiitadonアカウントの作成</del>
---
## Qiitadonのアカウント作成しました
https://qiitadon.com/@Qithub

### プロフィール設定内容

|項目名|設定内容|
| --- | --- |
| 表示名 | Qithub(bot) |
|プロフィール| QiitaとQiitadonのユーザ間コラボレーションを支援するためのBOTです。このBOT自体もQiitaユーザのコラボによって作られています。[α版 2017/09/27 現在] |
| Qiitaアカウント | qithub |

<img width="728" alt="2017-09-27 1 50 25" src="https://user-images.githubusercontent.com/11840938/30872805-485398dc-a326-11e7-84db-eb7877a34b4c.png">
<img width="683" alt="2017-09-27 1 48 25" src="https://user-images.githubusercontent.com/11840938/30872752-1dc193a8-a326-11e7-8977-41d624f3d1fa.png">
<img width="944" alt="2017-09-27 1 36 27" src="https://user-images.githubusercontent.com/11840938/30872356-bab9ece8-a324-11e7-92bf-f4c3261eb336.png">

**Comment by hidao80** [comment]
:thumbsup:

**Comment by KEINOS** [comment]
登録用のメアド（ qithub@keinos.com ）ですが、これをOrganizationメンバーのメールにも転送させるようにしますので、お手すきに [@KEINOS@Qiitadon.com](https://qiitadon.com/@KEINOS) にダイレクトトゥートしてください。

では、一旦クローズ
