### ISSUE TITLE
Qithub CLI クライアントの作成とリポジトリの引っ越し

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#92]
## 相談

1. @KEINOS の個人 REPO にある [Qithub の PHP版 CLI クライアント](https://github.com/KEINOS/Qithub_Client-PHP-CLI)を Organization に移したい。
2. クライアントが動くか試して欲しい。

## 自分の案

PHP（Phar）で作成した CLI クライアントが割と良い感じなので、Organization 側で管理したいです。本当は GoLang で（環境依存しないバイナリで）提供したかったのですが、まだアチキのラベルでは無理チンっぽいので。

https://github.com/KEINOS/Qithub_Client-PHP-CLI

言語ごとにブランチを切って、`master` には各言語のクライアントだけというのもいいかもしれませんが、それは別途話し合いたいと思います。

やっている事は単純で、コマンドの引数を Qithub REST API に投げて受け取った Qithub エンコードをデコードして表示しているだけです。

### インストール
1. [CLI クライアント「qithub.phar」をダウンロード](https://github.com/KEINOS/Qithub_Client-PHP-CLI/raw/master/qithub.phar)
2. `chmod 0755 qithub.phar`でコマンド実行を可能にする

### 使い方

コマンドラインから以下のように実行するとプラグインの実行結果を取得できます。

#### フォーマット
`$ php qithub.phar <name_plugin> [options]`

#### サンプル
`$ php qithub.phar roll-dice --help`
`$ php qithub.phar roll-dice --version`
`$ php qithub.phar roll-dice 3d6`
`$ php qithub.phar roll-dice 4d5 --use_emoji`

### 注意点

エンドポイントが `https://blog.keinos.com/qithub_dev/` と古い＋`phar`を作成する`box.phar`や`phpDocumentor.phar`などがリポジトリの`bin`に含まれてしまっているので、実際の REPO の引っ越しはサーバーの引っ越し後が良いかもしれません。まずは、他の環境でも `qithub.phar` が動くか試してみてください。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗 2018/07/01 現在）

- [x] script の実行環境の引っ越し Xrea -> SakuraVPS
- [x] ~~[該当リポジトリ](https://github.com/KEINOS/Qithub_Client-PHP-CLI)の引っ越し~~
- [x] [新規リポジトリの作成（`Qithub-CORE`）](https://github.com/Qithub-BOT/Qithub-CORE/commit/a38e69a5d063b8cb57023992786e4f68d9fe6252)
    - [x] [TravisCI で PHPUnit をパス](https://github.com/Qithub-BOT/Qithub-CORE/commit/ec46e1b4fd872c1588d1c776964635b8e4763abc)
    - [x] [Side CI をパス](https://github.com/Qithub-BOT/Qithub-CORE/commit/f7b96a33e9e3cc8062f21efcfb9774c0799555e8)
    - [x] Composer でインストール可能にする（`vendor/qithub-bot/qithub-core`にリポジトリ内容がインストールされる状態）
- [ ] 新規で API 用のエンジン（コマンド実行のみに絞ったプログラム）を作ることに（[`Qithub-CORE`](https://github.com/Qithub-BOT/Qithub-CORE)）→ 対応中（HARD CORE KISS なう 2018/07/01）

**Comment by hidao80** [comment]
👍

テスト & プラグインのデバッグ環境に良さそうですね！ Organization に統合しましよう！

**Comment by hidao80** [comment]
あああ、まだローカルにダウンロードして試せてないです。😓

結果が出たら報告します！

**Comment by KEINOS** [comment]
試してもサーバーの API がダウンしているため動かないと思います。

あ、エンドポイントが旧サーバのままだから動くことは動くのか。。。

お手すきでよろしくお願いしますー

**Comment by hidao80** [comment]
勝手に Qithub-API をローカルに建てようかと思ったけど、動作検証にQiitadonを使うのなら、冬眠中の今はふさわしくないですね。

トゥートパラメータを「非公開」にすればテストできる…？

> あ、エンドポイントが旧サーバのままだから動くことは動くのか。。。

ためしてみよう

**Comment by KEINOS** [comment]
Qithub(bot) の以前のアクセストークンは削除したので、bot が動くことはないと思います。

> 勝手に Qithub-API をローカルに建てようかと思ったけど、動作検証にQiitadonを
> 使うのなら、冬眠中の今はふさわしくないですね

アクセストークンを自分のアカウントのものにすれば大丈夫だと思います。
ただ、CLIクライアントの方はエンドポイントを変えないといけないです。

改めてソースを見ても「あー、ここはこうしかったな」となります。w

**Comment by KEINOS** [comment]
ローカルに落として試して見ましたが、NGでした。

現在、Qithub コマンド（旧プラグイン）の仕様として [Wiki を書いている](https://github.com/Qithub-BOT/Qithub-CMD/wiki)のですが、やはり「テスト & プラグインのデバッグ環境」的なローカルで動作するツールは必要かなと思いました。

トゥート・コマンドを入力すると Qithub コマンドを叩く（トゥートをQithubエンコードして Qithub コマンドに渡して実行するだけの）シンプルなツールが必要だと感じます。（と言うより作っている最中なのですが）

また、ツールを作る他のメリットとして、TravisCI などでテストを行う際にツールをダウンロードさせて、実行結果によってテストを行うこともできそうだというのもあります。

その場合、Qithub-CLI と呼んでいいのか、ちょっと用途が違う気もします。Qithub-CLI は Electron などのフロントエンドのように API を叩いて結果を表示するだけですが、テストツールは API の動作とほぼ同等の動作をローカルで行うからです。

Qithub-API（旧`scripts`）の再発明に近いものがあるかもしれませんが、むしろ **Qithub-API に取り込むエンジン部分の開発**と割り切って、Qithub-CLI の引っ越しではなく、別途新しいリポジトリを作成した方がいいかなと思っています。（Qithub-CMD-Testerみたいな）

それとも、Qithub-CLI を早々に引っ越してしまって、API経由でもローカルでもテストできるものにするとか。

お手すきに、意見お待ちしており 💪

**Comment by hidao80** [comment]
> Qithub-API に取り込むエンジン部分の開発と割り切って

この発想の方が良いと思います。  
[テストドライバ](http://www.itmedia.co.jp/im/articles/1111/07/news183.html)として、「ローカルのプラグインを実行して結果を返すだけ」のツールがあると、プラグイン開発がはかどることはもちろんのこと、**TravisCIと組み合わせることで、プラグインの自動テストも可能になるのではないか**と期待します。

また、API層（仮に「Qithub-UI」と呼びます）とテストドライバ（仮に「Qithub-Core」と呼びます）を組み合わせて本番環境ができるのではないかと考えています。  

参考１：本番環境のデータの流れのイメージ  
```
ユーザー → Qithub-UI → Qithub-Core → プラグイン → Qithub-Core → Qiitadon
```

参考２：テスト環境のデータの流れのイメージ
```
TravisCI → Qithub-Core → TravisCIで正しいかチェック
```

**Comment by KEINOS** [comment]
>> Qithub-API に取り込むエンジン部分の開発と割り切って
>
> この発想の方が良いと思います。

`Qithub-Core`いいですね。かっちょいい。

では、「**ローカル（Coreと同じ環境下）にあるコマンド（旧プラグイン）を実行して返すだけ**」のエンジンを作る方向で、新しいリポジトリを作成したいと思います！ → TL;DR 更新

以下の要件で "HelloWorld" だけのシンプルなリポジトリが出来たら報告いたしますので、その際に本案件 Close お願いし 💪 

(2018/04/29 23:53 タスクを TL;DR に移動）

**Comment by KEINOS** [comment]
Issue #112 により、[Qithub-CORE](https://github.com/Qithub-BOT/Qithub-CORE) のライブラリを用いた CLI ツールを公開する場合は、別途リポジトリを用意するのではなく、 [`tools` ディレクトリ](https://github.com/Qithub-BOT/Qithub-ORG/tree/master/tools)下で提供することになったので、本 issue はクローズします。

なお、アプリの性質上、やはり別リポジトリ（個別リポジトリ）が必要がでた場合は、別途 issue をあげて決めたいと思います。
