### ISSUE TITLE
OrganizationのメンバーがGithubにサインインしてない人から見えないことの対応策

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#93]
## 報告

表題の件、Githubユーザ以外の人が問い合わせる先のユーザを見つけることができない問題で、
解決策が分かりましたのでご報告します。

## 自分の案

* Organization→Peopleページのメンバーリストから、公開範囲をPublicにする。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2018/04/14 現在）

- Organization メンバーのアカウントをパブリックにした
- https://qithub.tk/ にて Qiitadon OAuth でログインした場合に「Organization 参加」ボタンを設置する

**Comment by KEINOS** [comment]
おー、PC+別（テスト）アカウントで People にメンバーが表示されるのを確認しました。→ 私も Public に変えてみました。

ただ、モバイル端末だと People タブが出てこないですね。（Android携帯）

## 対案

> https://qithub.tk/ で Qiitadon の OAuth 認証を設け、ログイン後に表示される「Organization参加」ボタンを押すとメンバーに追加される

という機能を設けてどうでしょう？Organization 追加後は https://dev.qithub.tk/ が使えるようになる。

下記 Issue #87 で議論しているのでコメントアウト

### ~~ドメインの役割~~

- ~~https://qithub.tk/<br>Qiitadon ユーザーが利用できるサービス提供。~~
    - ~~`items`の編集~~
    - ~~BOT の使い方やプラグイン作成の情報~~
    - ~~Qiitadon サイネージのブックマークレット提供~~
    - ~~Qiitaのキュレーション済み記事一覧~~
    - ~~など~~
- ~~https://dev.qithub.tk/<br>Qithub-BOT 全体の開発メンバーの集いの場~~
- ~~https://api.qithub.tk/<br>Qithub-BOT のルート・エンドポイント~~

**Comment by KEINOS** [comment]
> Organization→Peopleページのメンバーリストから、公開範囲をPublicにする。

これを行っておかないと GitHub にログインしても Organization メンバーでないと表示されないようです。

**Comment by hidao80** [comment]
> https://qithub.tk/ で Qiitadon の OAuth 認証を設け、ログイン後に表示される「Organization参加」ボタンを押すとメンバーに追加される

Qithub-BOT Organizationを製品としてみるとスマートでよいと思います。👍
ですが、BOTがforkされる場合を考慮すると、**Github連携をBOT機能の一部にしてしまうのはやりすぎなのではないか**と考えます。🤔

もしこの機能を実装した場合、BOTをforkしたとき以下のケースが発生すると想定しています。

1. fork者がOrganization管理ツールをGithub縛りで登録or無視する判断をしなくてはいけなくなる
1. ぼっちforkを作る場合、そもそもOrganizationを必要としないため冗長な機能になる

これはBOT本来の目的となる機能ではないので**KISSでない**と感じました。

拡張機能としては大変優秀で、**チームでBOTを管理したい需要がある場合は非常に有効である**とも考えます。👍

## 案A

* 「Organizationに追加」ボタンはBOT(scripts repo)には追加しない

## ドメインの役割

👍

**Comment by KEINOS** [comment]
> もしこの機能を実装した場合、BOTをforkしたとき

そうか。ある意味、再帰的な状態になりますね。

案A の

> 「Organizationに追加」ボタンはBOT(scripts repo)には追加しない

に 👍 

BOT(`/scripts` repo）は https://api.qithub.tk/ に特化させ、ログイン系は https://dev.qithub.tk/ 同様に  https://qithub.tk/ のサイトにコーディングするようにしてみます。

**Comment by hidao80** [comment]
案A で結論のようなので、問題なければ close 🙇‍♂️💪。

ログイン系を実装した場合、本 issue に **close したまま追記**していただけると状況が追跡できて良いかと思います。

…追記したら Reopen するんでしたっけ？🤔

**Comment by KEINOS** [comment]
案A で結論で 👍 

https://qithub.tk/ のログイン実装や Organization 参加リクエストも Qithub-ORG に UP しますが、issue 表題の「メンバーがみえない」件に関しては解決済みだと思うので Close し 💪 

追記は Close のままでできると思いますが、おそらく別 issue となると思うので、その際にこの issue をメンションするようにしましょう。
