### ISSUE TITLE
新年度（2018）の Organization のリポジトリ整理

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#94]
## 提案

やりたいことが多すぎて、アッシの脳がいささかチャンポンになってきているので、 Qithub-BOT Organization 内の**リポジトリのリネームおよび整理をしたい**です。

## 自分の案

新年度（2018）も始まり、そろそろコラボレータも増やしたい今日この頃。頭の整理もかねて以下のようにリポジトリを整理したいと思います。基本的には **repo 毎に役割をシンプルにわけたい**という内容です。

ご意見お待ちしており 💪 

|旧 repo 名||新 repo 名|備考|
|:--:|:--:|:--:|:---|
| items |→| Qithub-DEV | Organization 全般用。<br>Qiita 記事の items は隔離し下記 Qiita-items の repo へ。<br>Qiita 記事以外の従来の md ファイルは残し http://dev.qithub.tk/ で表示。|
| 🆕 |→| Qiita-items | 旧 items のうち **Qiita 記事のみ**の引っ越し先 repo。 |
| scripts |→| Qithub-API | https://api.qithub.tk/ で提供する機能。<br>**Qithub-BOT のコア部分のみ**とし、plugins は隔離→ Qithub-CMD へ。|
| 🆕 |→| Qithub-CMD | 旧 scripts 内の plugins。新旧いずれも単体では動作しない。 |

### items の隔離について（items -> Qiita-items）

以前、[Qithub の設定資料](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md) が私の不手際で Qiita に公開されていたのですが、（先日）気づいた時にはメンテナから差し戻されていたこともあり、やはり **Qiita 記事に特化した方がいい**と感じたからです。

しかし、当 items リポジトリは組織の取りまとめ repo として稼働済みであるため、Qiitaコラボ記事 の items （mdファイル）は専用の repo に引っ越し、残された Qithub の設定資料などは https://dev.qithub.tk/ ででも見れればいいのかな、と。（ https://dev.qithub.tk/ では md ファイルから自動で目次が付く機能は実装済みです。）

また、リポジトリからの WebHook も、隔離する（Qiitaコラボ記事に特化する）ことで**シンプルに実装できる**と思うからです。

### scripts の隔離について（scripts/plugins -> Qiita-CMD）

qithub(bot) の今後の目玉の１つである **「コマンド実行」がコラボ可能であることをシンプルに見せたい** のと、本体スクリプト（API のコア部分）を読まなくても良いようにして**敷居を下げたい**のが１番の理由です。

２番目の理由は、本体スクリプトを開発するときにプラグインが本体にブラ下がっていると開発しづらいことに気づいたからです。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗・結論 2018/04/14 現在）

- 新・旧リポジトリの名称と役割は下記表を参照
- 全リポジトリの issue は本リポジトリ（Qithub-ORG）でとりまとめる

|repo|概要|対象URL|備考|
|:---|:---|:---|:---|
|Qithub-ORG| Organization メンバー用 repo。<br>旧 `items` repo。|https://qithub.tk/|Org全体のとりまとめ（ issue や Org ルールなど）|
|Qithub-API| Qithub-BOT の本体スクリプト。<br>旧 `scripts` repo。|https://api.qithub.tk/|Wiki は API の制定仕様に限定|
|Qithub-CMD| Qithub コマンド（旧プラグイン）用repo。<br>新設。|なし|Wiki はコマンドの作り方や仕様など|
|Qithub-DEV| Organization メンバー用の各自の任意のリポジトリの clone および実行環境提供用。<br>新設。|https://dev.qithub.tk/||
|Qiita-items| Qiitaコラボ記事置き場。<br>新設。 |https://qiita.com/Qithub|現在は Wiki は無し|

**Comment by hidao80** [comment]
- qiita記事に特化したrepo
- プラグインに特化したrepo

とてもいいアイデアだと思います！

ただ、qithub-DEV に関しては**独自ドメインからアクセスできることに優位性を感じません**。
開発関係はGithubに集約しませんか？

## 案A

qithub-API repoにwikiをつけることを提案します。
開発に関するドキュメントは、wikiを使いませんか？

**Comment by KEINOS** [comment]
> 開発に関するドキュメントは、wikiを使いませんか？

ｳｷｯ Σ(･ω･ノ)ノ! ｿﾉﾃｶﾞｱｯﾀｶﾀｰﾝ

👍では、仕様に関するドキュメントは Wiki の方向で！

## 案B

ただ、`https://dev.qithub.tk/<Orgユーザ>/<Orgユーザの任意のrepo clone>`は実現したいので、items の変わりに、その操作用の PHP スクリプトを置かせてもらいたいです。

また、以下はサーバーのプログラム言語などの**基本環境の再構築後に行う流れ**ですが、あわせていかがでしょう？ご意見お待ちしており〼

1. Repo名の整理と新規追加
1. 旧`scripts`にある開発Docsは、新`Qithub-DEV`のWikiに移動
1. 新`Qithub-DEV`のrepo内には `https://dev.qithub.tk/` のソースを置く
1. Qithub コマンド（旧プラグイン）の作り方なども `Qithub-CMD` の Wiki にまとめる。

|repo|概要|対象URL|備考|
|:---|:---|:---|:---|
|Qiita-items| Qiitaコラボ記事置き場 |https://qiita.com/Qithub|現在は Wiki は無し|
|Qithub-DEV| Organization メンバー用 repo|https://dev.qithub.tk/|Org全体のとりまとめ（ issue や Org ルールなど）|
|Qithub-API| Qithub-BOT の本体スクリプト|https://api.qithub.tk/|Wiki は API の叩き方など|
|Qithub-CMD| Qithub コマンド（旧プラグイン）|なし|Wiki はコマンドの作り方や仕様など|
|???| Qiitadon一般ユーザー向けサービス用|https://qithub.tk/|ChQiitaやブックマークレットなど、非Orgユーザ向けの提供先として（予備）|

**Comment by KEINOS** [comment]
## 案C

`Qithub-DEV`（旧`items`） の repo 名は、むしろ `Qithub-ORG` にして repo 内には `https://qithub.tk/` のコンテンツを置けばいいだけなのではと思ってきました。

そして別途 `Qithub-DEV` の repo 内には JSON ファイルを置いて Orgユーザーがマウントさせたい repo を記載してマージされたら clone される程度のシンプルさで良いような気も。

```repos.json
[
    {
        "name_title": "Masto Filter",
        "name_dir": "MastoFilter",
        "name_user": "hidao80",
        "url_git": "https:\/\/github.com\/hidao80\/MastoFilter.git"
    },
    {
        "name_title": "Masto Filter [Fork]",
        "name_dir": "Fork_MastoFilter",
        "name_user": "KEINOS",
        "url_git": "https:\/\/github.com\/KEINOS\/Fork_MastoFilter.git"
    }
]
```

**Comment by hidao80** [comment]
うお！コメント編集中に新しいコメントが！

-------

**Issueが分散することに抵抗を感じます。**

今までは、Issue & PRは基本Itemsにまとめる方針でしたが、**ドキュメントとIssue & PRをひとつのrepoに入れられる今、プロジェクトにかかわるIssue & PRを分散させたくない**と考えています。

## 案D

DEV、API、CMDのうち、Issueを活かすのは1 repoのみにしませんか？

Githubの仕掛け上、PRは封じようがありませんが、Issueは封じることができるので、メインとなるrepo（例：Qithub-ORG）だけIssuesを活かし他のIssues機能を殺すことで、相談や質問の分散を防ぎたいと考えています。

現在でもQKBがどのrepoか分からず、相談内容を振り返ろうとしたときに見つかりづらいのです。
たとえば、「古いissueにコメントがついて、出先でスマホ等でのぞき、既読になってしまった投稿を自宅PC等で探し出す」などです。

-------

現在も事故的にitemsともscriptsともつかないissueがどちらにあったか迷うので、**Issuesを統一したいと切に望みます。**

**Comment by KEINOS** [comment]
> プロジェクトにかかわるIssue & PRを分散させたくない

これは同意です。PR は仕方ないとしても **issue は統一repo** で行うに賛成です。

> Qithub-ORG（旧`items`）リポジトリで全 repo の issue を受付
> 他 repo の issue は KILL して KISS

で OK バブリー？

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
では repo の整理は一旦 😎 で進めて 👌？

**Comment by hidao80** [comment]
👌🙏🙇‍♂️

**Comment by KEINOS** [comment]
以下の整理を行いました。

以前よりは[リポジトリの役割がシンプルになった](https://github.com/Qithub-BOT)と思いますがいかがでしょう？
特に問題なければ Close お願いし 💪 

- 各リポジトリのリネームと新設
- 各リポジトリの Issue の統廃合
    - 他リポジトリの Issue, Project 閉鎖（Wiki の閉鎖は一部 repo を除く）
    - 旧 script （現 Qithub-API）の issue を ORG の Wiki への引っ越し（Issue #96）
