### ISSUE TITLE
Qithub設定資料集、ページを分けて良い？

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/Qithub-ORG#95]
## 提案

Qithub設定資料集ページ、雑多な内容が1ページに収まっていて非常に読みづらいです。  
セクションごとに別ページにしてもいいですか？

## 自分の案（案A）

- Level 2 の箇条ごとに別ページとする。

## 補足

- 編集作業は @hidao80 がやります。

## TL;DR（進捗・結論 2018/04/14 現在）

- ~~審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )~~
- @hidao が、Level 2 の過剰ごとに別ページとする作業をすることで合意
- ページ分割完了。元ページは削除しました。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
👍 
一見した時の質量を分散させる意味でもページの関数化（セクションか）良いと思います。
お手数ですが、よろしくお願いし 💪 ! 🙇
