### ISSUE TITLE
Qithub-API（旧scripts）の issue 引っ越しは必要か

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#96]
## 相談

Qithub-API（旧`scripts`）の issue をどうしましょう？

### 統一？今日かい？

リポジトリの整理にともない、Organization 内の全リポジトリの issue は [Qithub-ORG（旧`items`）に統一する方向に決まりました](#94)。

**他のリポジトリの設定はほぼ終わっている**ものの、残る Qithub-API（旧`scripts`）で相談があります。

現在 Qithub-API には 45件の issue があり、うち open なものが 10 件あります。

新規 **issue を立てないのであれば急ぎではないと思う**のですが、どげんとせんと。いかんせん issue 統一のためリポジトリの issue 機能を閉じると、今度は検索できなくなるということもあり、相談したいと思いもす。

一番の課題は、「過去の`scripts`時代の issue は検索、開くことはできず、他リポジトリの issue からのリンクは切れる」ことだと思いますが、これらは人力を使った方法しか思いつきませんでした。

### 案A

- バツンっと閉じてしまい、仕切り直す。
    メリット
    - 楽

    デメリット
    - 過去の`scripts`時代の issue は検索、開くことはできない

### 案B

- Open な物だけ手動で引っ越す
    メリット
    - 早い段階で新体制に移れる

    デメリット
    - 過去の`scripts`時代の closed issue （30件）は検索、開くことはできない

### 案C

- GitHub API を使った引っ越しツールを使う
    メリット
    - 同一リポジトリで検索対象になる

    デメリット
    - 引っ越し先のラベル等の情報がすべてリセットされる
    - issue を立ち上げた人が引き継がれない（引っ越し人の名義に変わる）
    - 相対パスのリンクが壊れる

### 案D（案A と 案B の mix）

- issue をテキストに落とし、旧ログとして Wiki に貼り付ける（過去の事例検索対策）
    メリット
    - 同一リポジトリで検索対象になる

    デメリット
    - issue のテキスト吸い出しツールが必要（あるのか？）

### 案E（遅れて）

- 現在 Qithub-API で Open なもの（10件）だけ Close されるまで待ち（新規 issue はNG）、クリアになったら 案 A を実行する。
    メリット
    - 新旧の運営ルールの区切りを付けられる

    デメリット
    - 過去の`scripts`時代の issue は検索、開くことはできない

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗・結論 2018/04/24 現在）

- [x] issue を [Wiki に引っ越し](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Issue-list-of-Qithub-API) 済み
    - Qithub-API（旧`scripts`）リポジトリの issue をスクレイピングでテキストを抜き出し後、本リポジトリ（Qithub-ORG。旧`items`）の**Wiki**に貼り付ける
- [x] issue 機能はオンのまま、新規 issue は禁止
    - 当面の issue 間のリンク切れ対策として

**Comment by hidao80** [comment]
案Dに👍
その上で、新規 issue を禁止しましょう。

### FYI：

こんなものを見つけました。ご存知かとは思いますが。

[GitHubのIssues縛りから抜け出す方法【禁断のマルパ○リ編】(https://qiita.com/Geany/items/e13f77139d5c0e80373b)](https://qiita.com/Geany/items/e13f77139d5c0e80373b)

お代官様、これでなにとぞ一つよろしくお願いします…😎

**Comment by KEINOS** [comment]
> 案Dに👍
> その上で、新規 issue を禁止しましょう。

(｀_´)ゞﾊｯ
( ﾟДﾟ)ゞ ﾘｮｰｶｲ!

> こんなものを見つけました。ご存知かとは思いますが。

これはヌケますなぁ。越後屋、お主も悪よのぅ。

**Comment by hidao80** [comment]
進捗のタイムスタンプが未来になっとる…！

ドクがタイムサーキットを完成させた？😉

**Comment by KEINOS** [comment]
貴奴が未来からやってきて書き換えたようです。修正しました → TL;DR

明後日（18日）に改めて更新してみます。変化があるか確認してみましょう。

変化がない場合、もしかすると我々はタイムリープしているのかもしれません。

**Comment by hidao80** [comment]
Issues のテキスト抜き出すことができましたら、wikiの1ページにまとめて貼り付けといて 👌です。

私がよしなにしておきます。

**Comment by KEINOS** [comment]
[Issue を markdown で書き出すスクリプト](https://github.com/KEINOS/GitHub_Issue-DL-As-MD)を使い Issues の抜き出しと [Wiki の貼り付け](https://github.com/Qithub-BOT/Qithub-ORG/wiki/Issue-list-of-Qithub-API)を行いました。

貼り付けと言うより、Wiki のリポジトリを `clone` して `issues` ディレクトリを作成し、その中に抜き出したファイルをごっそりと設置しました。（ディレクトリを作成しても Wiki の表示は階層化されないようです）

ご確認よろしくお願いし 💪

**Comment by KEINOS** [comment]
とりあえず Issue をぶっこ抜いて Wiki にぶっこむ要件は網羅したと思うので、特に問題なければ close お願いし 💪

**Comment by hidao80** [comment]
すごい！ 思ってたよりキレイに移行できてる！

索引は作っていただけたんでしょうか？ ありがとうございます！🙇‍♂️👌

**Comment by KEINOS** [comment]
> 索引は作っていただけたんでしょうか？

抜き出す時に索引も一緒に吐き出すようにさせました！ 👍
