### ISSUE TITLE
Qithub(bot) のトゥート削除

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#97]
## 報告

もろもろの整理の一貫として Bot が吐き出していたトゥートの削除を開始いたしました。

最後にアナウンスしたトゥート以外の全削除が済みしだい close いたします。

- [Mastodon 全トゥート削除スクリプト](https://github.com/KEINOS/Mastodon_Simple-Toot-Deleter)を基本ノンストップ型に修正して手元のラズパイで実行しています。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連issue [Qithub-BOT の一時停止と体制の見直し](Qithub-BOT/Qithub-API/issues/94) @ Qithub-API

----------------

## TL;DR（結果 2018/04/15 現在）

- 20:38 最後の挨拶トゥート１件を残して全削除完了しました。
    - https://qiitadon.com/web/accounts/12774

**Comment by KEINOS** [comment]
最後の挨拶トゥート１件を残して全削除完了しました！（思ったより早く削除できました）
- https://qiitadon.com/web/accounts/12774

問題なければ Close お願いし 💪

**Comment by hidao80** [comment]
👍
