### ISSUE TITLE
サイト Qithub.tk のディレクトリ構造とサイトの自動更新

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#98]
## 報告

下記 URL を叩くと当リポジトリ（/Qithub-BOT/Qithub-ORG.git）が https://Qithub.tk の Web サーバに `fetch` （`git fetch origin`）され、リポジトリ内容がサーバに反映されるようにしました。

http://Qithub.tk/api/update/

[Qithub-BOT/Qithub-ORG/index.php](https://github.com/Qithub-BOT/Qithub-ORG/blob/master/index.php) などを適当に編集・プッシュして実行してみてください。（ブランチ切りやプルリクは必要ありません）

## 相談

現在は誰でも叩けば反映されてしまうので、ゆくゆくはトークンなどを発行してマージ時の WebHook で動作するようにしたいのですが、その前に呼び出し時の URL （ディレクトリ構成／エンドポイント）に関して相談があります。

上記 URL では `/api/update/` ディレクトリ下に更新用のスクリプトを設置していますが、 https://API.Qithub.tk とゴッチャになる気がします。どうでしょう？

### 現在想定している用途
- https://Qithub.tk/     <br>→ Qithub-BOT の窓口および要 Qiitadon OAuth ログインの SPA 提供など（一般 Qiita/Qiitadon ファン・ユーザ向け）
- https://API.Qithub.tk/  <br>→ Qithub-ORG が提供する API サービス。Qithub コマンドの WebAPI はここで動作する（外部アプリ向け）

## 自分の案（A案）

サイト更新のエンドポイントは https://Qithub.tk/update とシンプルに KISS

## 補足

マージ後の WebHook の更新は他のリポジトリでも実装する予定です。

- Qiita-items
- Qithub-API

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2018/06/14 現在）

- [x] `/api/*` へのアクセスは、アプリおよびサービスからのみアクセスに限定すべき
- [x] `/api` → `/tools/` にディレクトリ名変更することに → [済み](https://github.com/Qithub-BOT/Qithub-ORG/commit/e79b0a79b4aaf70980e0ee8c6842e6bc4af068ae)
- [x] 当面（トークンなどによる）アクセス制限は行わない。
- [x] ヘッダに 'noindex, nofollow' を設定することに → [済み](https://github.com/Qithub-BOT/Qithub-ORG/commit/f8272de6d2a56e6d3befa652481e6062679ca3bb)
- [x] https://api.qithub.tk/ → https://qithub.tk/api/ に変更
    - Qithub-CORE, Qithub-CMD, Qithub-API は Composer ライブラリ開発用とする

**Comment by hidao80** [comment]
> Web サーバに fetch （git fetch origin）され、

`git merge`しないの？🤔

さておき。
現在の`/api/*`は **プログラムからアクセスされないので、「api」という名前がふさわしくない** と考えます。

# B案

1. `/api/`を`/tools/`に変更する
2. サブドメインは使わず、`/api/`にアクセスしてQithub-APIを利用してもらう

Qithub への入り口を一元化させたい狙いです。

**Comment by KEINOS** [comment]
> git mergeしないの？🤔

具体的には `git fetch origin` で master を更新したのち `git reset --hard origin/master` しています。

`pull` や `fetch+merge` しないのは、Web サーバ側で意図しないコミットやマージがあった場合 `merge` されても気づきにくいので、強制的に GitHub-ORG リポジトリと同じ状態にするためです。

> B案-1
> `/api/` を `/tools/` に変更する

👍 おー、いいですね。そうしましょう。

> B案-2
> サブドメインは使わず、`/api/` にアクセスして Qithub-API を利用してもらう
> Qithub への入り口を一元化させたい狙いです。

🤔「Qithub の入り口を１つに」というのはわかるのですが、そうなると API のリポジトリを作成する必要がなぜあったのか。実は、思い出せません。 😭 

Qithub-CORE と Qithub-CMD は composer で入れられる方向にしているので、そうすると Qithub-API は必要ないし、`/api/` 下で開発した方が合理的かつわかりやすい。なぜだ。

ちょっとひっかかるので、一晩考えます。とりあえず、まずは `api` → `tools` に変更しまーす。

**Comment by KEINOS** [comment]
> `api` → `tools` に変更

しましたー。[Commit e79b0a](https://github.com/Qithub-BOT/Qithub-ORG/commit/e79b0a79b4aaf70980e0ee8c6842e6bc4af068ae)

**Comment by hidao80** [comment]
> API のリポジトリを作成する必要がなぜあったのか。

うっすらとした記憶をたどると、**system系（現API repo）とplugin系（現CMD repo）に分れており、system系にはトークンの使用など特権があり**、そこで分岐したのかと。

repo分けの根拠までは…記憶にございません🤔

**Comment by KEINOS** [comment]
> system系にはトークンの使用など特権があり

あー、そこらへんで何かあったかも。(￣^￣ ;) ｳｰﾝ

もう少し整理してみたいと思いますが、まずはサイトの自動更新をちょっと触っています。

**Comment by KEINOS** [comment]
一晩考えることを忘れてました！今晩、考えることにします。

**Comment by hidao80** [comment]
Qithub-API リポジトリの源流は`Qithub-BOT/scripts`でしたね。Qithub-APIのissuesを取り出したwiki見て気が付きました。

scriptsからpluginsを取り出したのがQithub-CMDの源流でしょうか。

scriptsが主、pluginsが従。
`Qithub-API==scripts and Qithub-CMD==plugins` ですね。

「Qithub-APIを作った」というより、「Qithub-CMDがスピンアウトした」イメージですね。
今となってはQithub-API≒Qithub-Coreですが…

**Comment by KEINOS** [comment]
> 今となってはQithub-API≒Qithub-Coreですが…

なるほど！それがワケワカメになった原因か。

では、`https://API.Qithub.tk/` はやめて、`https://Qithub.tk/api/` にしましょう！

リポジトリ Qithub-API は Qithub-CORE を拡張した composer のライブラリとして進めたいと思います。

- `Qithub-CMD extends Qithub-CORE`
- `Qithub-API extends Qithub-CORE`

なイメージです。（`Qithub-CORE` は Qithub エンコード／デコードの基本クラス）

∴ 下記リポジトリは composer ライブラリ開発用として利用されるもので、直接的な Web サービスなどには関係ない

1. Qithub-CORE
2. Qithub-CMD
3. Qithub-API

**Comment by hidao80** [comment]
この issue、もう close してもいいのかな…？

**Comment by KEINOS** [comment]
そうですね、Close しましょう ＆ → TL;DR 済み
