### ISSUE TITLE
【報告】Word2Vec をインストールしました

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#99]
## 報告

Word2Vec (Python) をインストールしました。

https://qithub.tk/tools/version/?key=Python+package+installed&type=program

どこかでサンプル・スクリプトが動作したら close します。

## TL;DR（結論 2018/07/26 現在）

- word2vec v0.9.2 
- [ ] 動作検証

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 issue [Qithub-API issue#91](https://github.com/Qithub-BOT/Qithub-API/issues/91)

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
これも手を付ける余力がないため、一旦クローズで。

OS 移行後、いずれコンテナ化して再スタートさせたいと思います。
